// Code generated by ent, DO NOT EDIT.

package info

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the info type in the database.
	Label = "info"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "info_id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldCreateBy holds the string denoting the create_by field in the database.
	FieldCreateBy = "create_by"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateBy holds the string denoting the update_by field in the database.
	FieldUpdateBy = "update_by"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldFileURL holds the string denoting the file_url field in the database.
	FieldFileURL = "file_url"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPeriod holds the string denoting the period field in the database.
	FieldPeriod = "period"
	// FieldDispersionMeasure holds the string denoting the dispersion_measure field in the database.
	FieldDispersionMeasure = "dispersion_measure"
	// FieldRaDeg holds the string denoting the ra_deg field in the database.
	FieldRaDeg = "ra_deg"
	// FieldDecDeg holds the string denoting the dec_deg field in the database.
	FieldDecDeg = "dec_deg"
	// FieldGalacticLongitude holds the string denoting the galactic_longitude field in the database.
	FieldGalacticLongitude = "galactic_longitude"
	// FieldGalacticLatitude holds the string denoting the galactic_latitude field in the database.
	FieldGalacticLatitude = "galactic_latitude"
	// FieldSurveyName holds the string denoting the survey_name field in the database.
	FieldSurveyName = "survey_name"
	// Table holds the table name of the info in the database.
	Table = "stellar_info"
)

// Columns holds all SQL columns for info fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldCreateBy,
	FieldCreateTime,
	FieldUpdateBy,
	FieldUpdateTime,
	FieldRemark,
	FieldVersion,
	FieldFileURL,
	FieldName,
	FieldPeriod,
	FieldDispersionMeasure,
	FieldRaDeg,
	FieldDecDeg,
	FieldGalacticLongitude,
	FieldGalacticLatitude,
	FieldSurveyName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	RemarkValidator func(string) error
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int32
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(int32) error
	// FileURLValidator is a validator for the "file_url" field. It is called by the builders before save.
	FileURLValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SurveyNameValidator is a validator for the "survey_name" field. It is called by the builders before save.
	SurveyNameValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Info queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByCreateBy orders the results by the create_by field.
func ByCreateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateBy, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateBy orders the results by the update_by field.
func ByUpdateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateBy, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByFileURL orders the results by the file_url field.
func ByFileURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileURL, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPeriod orders the results by the period field.
func ByPeriod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriod, opts...).ToFunc()
}

// ByDispersionMeasure orders the results by the dispersion_measure field.
func ByDispersionMeasure(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDispersionMeasure, opts...).ToFunc()
}

// ByRaDeg orders the results by the ra_deg field.
func ByRaDeg(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRaDeg, opts...).ToFunc()
}

// ByDecDeg orders the results by the dec_deg field.
func ByDecDeg(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDecDeg, opts...).ToFunc()
}

// ByGalacticLongitude orders the results by the galactic_longitude field.
func ByGalacticLongitude(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGalacticLongitude, opts...).ToFunc()
}

// ByGalacticLatitude orders the results by the galactic_latitude field.
func ByGalacticLatitude(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGalacticLatitude, opts...).ToFunc()
}

// BySurveyName orders the results by the survey_name field.
func BySurveyName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSurveyName, opts...).ToFunc()
}
