// Code generated by ent, DO NOT EDIT.

package info

import (
	"lersosa/app/stellar/service/internal/infrastructure/info/gatewayimpl/database/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Info {
	return predicate.Info(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Info {
	return predicate.Info(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Info {
	return predicate.Info(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Info {
	return predicate.Info(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Info {
	return predicate.Info(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Info {
	return predicate.Info(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Info {
	return predicate.Info(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldTenantID, v))
}

// CreateBy applies equality check predicate on the "create_by" field. It's identical to CreateByEQ.
func CreateBy(v int64) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldCreateBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateBy applies equality check predicate on the "update_by" field. It's identical to UpdateByEQ.
func UpdateBy(v int64) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldUpdateBy, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldUpdateTime, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldRemark, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int32) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldVersion, v))
}

// FileURL applies equality check predicate on the "file_url" field. It's identical to FileURLEQ.
func FileURL(v string) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldFileURL, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldName, v))
}

// Period applies equality check predicate on the "period" field. It's identical to PeriodEQ.
func Period(v float64) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldPeriod, v))
}

// DispersionMeasure applies equality check predicate on the "dispersion_measure" field. It's identical to DispersionMeasureEQ.
func DispersionMeasure(v float64) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldDispersionMeasure, v))
}

// RaDeg applies equality check predicate on the "ra_deg" field. It's identical to RaDegEQ.
func RaDeg(v float64) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldRaDeg, v))
}

// DecDeg applies equality check predicate on the "dec_deg" field. It's identical to DecDegEQ.
func DecDeg(v float64) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldDecDeg, v))
}

// GalacticLongitude applies equality check predicate on the "galactic_longitude" field. It's identical to GalacticLongitudeEQ.
func GalacticLongitude(v float64) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldGalacticLongitude, v))
}

// GalacticLatitude applies equality check predicate on the "galactic_latitude" field. It's identical to GalacticLatitudeEQ.
func GalacticLatitude(v float64) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldGalacticLatitude, v))
}

// SurveyName applies equality check predicate on the "survey_name" field. It's identical to SurveyNameEQ.
func SurveyName(v string) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldSurveyName, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.Info {
	return predicate.Info(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.Info {
	return predicate.Info(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.Info {
	return predicate.Info(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.Info {
	return predicate.Info(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.Info {
	return predicate.Info(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.Info {
	return predicate.Info(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.Info {
	return predicate.Info(sql.FieldLTE(FieldTenantID, v))
}

// CreateByEQ applies the EQ predicate on the "create_by" field.
func CreateByEQ(v int64) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldCreateBy, v))
}

// CreateByNEQ applies the NEQ predicate on the "create_by" field.
func CreateByNEQ(v int64) predicate.Info {
	return predicate.Info(sql.FieldNEQ(FieldCreateBy, v))
}

// CreateByIn applies the In predicate on the "create_by" field.
func CreateByIn(vs ...int64) predicate.Info {
	return predicate.Info(sql.FieldIn(FieldCreateBy, vs...))
}

// CreateByNotIn applies the NotIn predicate on the "create_by" field.
func CreateByNotIn(vs ...int64) predicate.Info {
	return predicate.Info(sql.FieldNotIn(FieldCreateBy, vs...))
}

// CreateByGT applies the GT predicate on the "create_by" field.
func CreateByGT(v int64) predicate.Info {
	return predicate.Info(sql.FieldGT(FieldCreateBy, v))
}

// CreateByGTE applies the GTE predicate on the "create_by" field.
func CreateByGTE(v int64) predicate.Info {
	return predicate.Info(sql.FieldGTE(FieldCreateBy, v))
}

// CreateByLT applies the LT predicate on the "create_by" field.
func CreateByLT(v int64) predicate.Info {
	return predicate.Info(sql.FieldLT(FieldCreateBy, v))
}

// CreateByLTE applies the LTE predicate on the "create_by" field.
func CreateByLTE(v int64) predicate.Info {
	return predicate.Info(sql.FieldLTE(FieldCreateBy, v))
}

// CreateByIsNil applies the IsNil predicate on the "create_by" field.
func CreateByIsNil() predicate.Info {
	return predicate.Info(sql.FieldIsNull(FieldCreateBy))
}

// CreateByNotNil applies the NotNil predicate on the "create_by" field.
func CreateByNotNil() predicate.Info {
	return predicate.Info(sql.FieldNotNull(FieldCreateBy))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Info {
	return predicate.Info(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Info {
	return predicate.Info(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Info {
	return predicate.Info(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Info {
	return predicate.Info(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Info {
	return predicate.Info(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Info {
	return predicate.Info(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Info {
	return predicate.Info(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.Info {
	return predicate.Info(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.Info {
	return predicate.Info(sql.FieldNotNull(FieldCreateTime))
}

// UpdateByEQ applies the EQ predicate on the "update_by" field.
func UpdateByEQ(v int64) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldUpdateBy, v))
}

// UpdateByNEQ applies the NEQ predicate on the "update_by" field.
func UpdateByNEQ(v int64) predicate.Info {
	return predicate.Info(sql.FieldNEQ(FieldUpdateBy, v))
}

// UpdateByIn applies the In predicate on the "update_by" field.
func UpdateByIn(vs ...int64) predicate.Info {
	return predicate.Info(sql.FieldIn(FieldUpdateBy, vs...))
}

// UpdateByNotIn applies the NotIn predicate on the "update_by" field.
func UpdateByNotIn(vs ...int64) predicate.Info {
	return predicate.Info(sql.FieldNotIn(FieldUpdateBy, vs...))
}

// UpdateByGT applies the GT predicate on the "update_by" field.
func UpdateByGT(v int64) predicate.Info {
	return predicate.Info(sql.FieldGT(FieldUpdateBy, v))
}

// UpdateByGTE applies the GTE predicate on the "update_by" field.
func UpdateByGTE(v int64) predicate.Info {
	return predicate.Info(sql.FieldGTE(FieldUpdateBy, v))
}

// UpdateByLT applies the LT predicate on the "update_by" field.
func UpdateByLT(v int64) predicate.Info {
	return predicate.Info(sql.FieldLT(FieldUpdateBy, v))
}

// UpdateByLTE applies the LTE predicate on the "update_by" field.
func UpdateByLTE(v int64) predicate.Info {
	return predicate.Info(sql.FieldLTE(FieldUpdateBy, v))
}

// UpdateByIsNil applies the IsNil predicate on the "update_by" field.
func UpdateByIsNil() predicate.Info {
	return predicate.Info(sql.FieldIsNull(FieldUpdateBy))
}

// UpdateByNotNil applies the NotNil predicate on the "update_by" field.
func UpdateByNotNil() predicate.Info {
	return predicate.Info(sql.FieldNotNull(FieldUpdateBy))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Info {
	return predicate.Info(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Info {
	return predicate.Info(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Info {
	return predicate.Info(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Info {
	return predicate.Info(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Info {
	return predicate.Info(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Info {
	return predicate.Info(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Info {
	return predicate.Info(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.Info {
	return predicate.Info(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.Info {
	return predicate.Info(sql.FieldNotNull(FieldUpdateTime))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.Info {
	return predicate.Info(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.Info {
	return predicate.Info(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.Info {
	return predicate.Info(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.Info {
	return predicate.Info(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.Info {
	return predicate.Info(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.Info {
	return predicate.Info(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.Info {
	return predicate.Info(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.Info {
	return predicate.Info(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.Info {
	return predicate.Info(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.Info {
	return predicate.Info(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.Info {
	return predicate.Info(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.Info {
	return predicate.Info(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.Info {
	return predicate.Info(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.Info {
	return predicate.Info(sql.FieldContainsFold(FieldRemark, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int32) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int32) predicate.Info {
	return predicate.Info(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int32) predicate.Info {
	return predicate.Info(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int32) predicate.Info {
	return predicate.Info(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int32) predicate.Info {
	return predicate.Info(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int32) predicate.Info {
	return predicate.Info(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int32) predicate.Info {
	return predicate.Info(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int32) predicate.Info {
	return predicate.Info(sql.FieldLTE(FieldVersion, v))
}

// FileURLEQ applies the EQ predicate on the "file_url" field.
func FileURLEQ(v string) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldFileURL, v))
}

// FileURLNEQ applies the NEQ predicate on the "file_url" field.
func FileURLNEQ(v string) predicate.Info {
	return predicate.Info(sql.FieldNEQ(FieldFileURL, v))
}

// FileURLIn applies the In predicate on the "file_url" field.
func FileURLIn(vs ...string) predicate.Info {
	return predicate.Info(sql.FieldIn(FieldFileURL, vs...))
}

// FileURLNotIn applies the NotIn predicate on the "file_url" field.
func FileURLNotIn(vs ...string) predicate.Info {
	return predicate.Info(sql.FieldNotIn(FieldFileURL, vs...))
}

// FileURLGT applies the GT predicate on the "file_url" field.
func FileURLGT(v string) predicate.Info {
	return predicate.Info(sql.FieldGT(FieldFileURL, v))
}

// FileURLGTE applies the GTE predicate on the "file_url" field.
func FileURLGTE(v string) predicate.Info {
	return predicate.Info(sql.FieldGTE(FieldFileURL, v))
}

// FileURLLT applies the LT predicate on the "file_url" field.
func FileURLLT(v string) predicate.Info {
	return predicate.Info(sql.FieldLT(FieldFileURL, v))
}

// FileURLLTE applies the LTE predicate on the "file_url" field.
func FileURLLTE(v string) predicate.Info {
	return predicate.Info(sql.FieldLTE(FieldFileURL, v))
}

// FileURLContains applies the Contains predicate on the "file_url" field.
func FileURLContains(v string) predicate.Info {
	return predicate.Info(sql.FieldContains(FieldFileURL, v))
}

// FileURLHasPrefix applies the HasPrefix predicate on the "file_url" field.
func FileURLHasPrefix(v string) predicate.Info {
	return predicate.Info(sql.FieldHasPrefix(FieldFileURL, v))
}

// FileURLHasSuffix applies the HasSuffix predicate on the "file_url" field.
func FileURLHasSuffix(v string) predicate.Info {
	return predicate.Info(sql.FieldHasSuffix(FieldFileURL, v))
}

// FileURLEqualFold applies the EqualFold predicate on the "file_url" field.
func FileURLEqualFold(v string) predicate.Info {
	return predicate.Info(sql.FieldEqualFold(FieldFileURL, v))
}

// FileURLContainsFold applies the ContainsFold predicate on the "file_url" field.
func FileURLContainsFold(v string) predicate.Info {
	return predicate.Info(sql.FieldContainsFold(FieldFileURL, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Info {
	return predicate.Info(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Info {
	return predicate.Info(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Info {
	return predicate.Info(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Info {
	return predicate.Info(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Info {
	return predicate.Info(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Info {
	return predicate.Info(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Info {
	return predicate.Info(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Info {
	return predicate.Info(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Info {
	return predicate.Info(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Info {
	return predicate.Info(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Info {
	return predicate.Info(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Info {
	return predicate.Info(sql.FieldContainsFold(FieldName, v))
}

// PeriodEQ applies the EQ predicate on the "period" field.
func PeriodEQ(v float64) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldPeriod, v))
}

// PeriodNEQ applies the NEQ predicate on the "period" field.
func PeriodNEQ(v float64) predicate.Info {
	return predicate.Info(sql.FieldNEQ(FieldPeriod, v))
}

// PeriodIn applies the In predicate on the "period" field.
func PeriodIn(vs ...float64) predicate.Info {
	return predicate.Info(sql.FieldIn(FieldPeriod, vs...))
}

// PeriodNotIn applies the NotIn predicate on the "period" field.
func PeriodNotIn(vs ...float64) predicate.Info {
	return predicate.Info(sql.FieldNotIn(FieldPeriod, vs...))
}

// PeriodGT applies the GT predicate on the "period" field.
func PeriodGT(v float64) predicate.Info {
	return predicate.Info(sql.FieldGT(FieldPeriod, v))
}

// PeriodGTE applies the GTE predicate on the "period" field.
func PeriodGTE(v float64) predicate.Info {
	return predicate.Info(sql.FieldGTE(FieldPeriod, v))
}

// PeriodLT applies the LT predicate on the "period" field.
func PeriodLT(v float64) predicate.Info {
	return predicate.Info(sql.FieldLT(FieldPeriod, v))
}

// PeriodLTE applies the LTE predicate on the "period" field.
func PeriodLTE(v float64) predicate.Info {
	return predicate.Info(sql.FieldLTE(FieldPeriod, v))
}

// PeriodIsNil applies the IsNil predicate on the "period" field.
func PeriodIsNil() predicate.Info {
	return predicate.Info(sql.FieldIsNull(FieldPeriod))
}

// PeriodNotNil applies the NotNil predicate on the "period" field.
func PeriodNotNil() predicate.Info {
	return predicate.Info(sql.FieldNotNull(FieldPeriod))
}

// DispersionMeasureEQ applies the EQ predicate on the "dispersion_measure" field.
func DispersionMeasureEQ(v float64) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldDispersionMeasure, v))
}

// DispersionMeasureNEQ applies the NEQ predicate on the "dispersion_measure" field.
func DispersionMeasureNEQ(v float64) predicate.Info {
	return predicate.Info(sql.FieldNEQ(FieldDispersionMeasure, v))
}

// DispersionMeasureIn applies the In predicate on the "dispersion_measure" field.
func DispersionMeasureIn(vs ...float64) predicate.Info {
	return predicate.Info(sql.FieldIn(FieldDispersionMeasure, vs...))
}

// DispersionMeasureNotIn applies the NotIn predicate on the "dispersion_measure" field.
func DispersionMeasureNotIn(vs ...float64) predicate.Info {
	return predicate.Info(sql.FieldNotIn(FieldDispersionMeasure, vs...))
}

// DispersionMeasureGT applies the GT predicate on the "dispersion_measure" field.
func DispersionMeasureGT(v float64) predicate.Info {
	return predicate.Info(sql.FieldGT(FieldDispersionMeasure, v))
}

// DispersionMeasureGTE applies the GTE predicate on the "dispersion_measure" field.
func DispersionMeasureGTE(v float64) predicate.Info {
	return predicate.Info(sql.FieldGTE(FieldDispersionMeasure, v))
}

// DispersionMeasureLT applies the LT predicate on the "dispersion_measure" field.
func DispersionMeasureLT(v float64) predicate.Info {
	return predicate.Info(sql.FieldLT(FieldDispersionMeasure, v))
}

// DispersionMeasureLTE applies the LTE predicate on the "dispersion_measure" field.
func DispersionMeasureLTE(v float64) predicate.Info {
	return predicate.Info(sql.FieldLTE(FieldDispersionMeasure, v))
}

// DispersionMeasureIsNil applies the IsNil predicate on the "dispersion_measure" field.
func DispersionMeasureIsNil() predicate.Info {
	return predicate.Info(sql.FieldIsNull(FieldDispersionMeasure))
}

// DispersionMeasureNotNil applies the NotNil predicate on the "dispersion_measure" field.
func DispersionMeasureNotNil() predicate.Info {
	return predicate.Info(sql.FieldNotNull(FieldDispersionMeasure))
}

// RaDegEQ applies the EQ predicate on the "ra_deg" field.
func RaDegEQ(v float64) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldRaDeg, v))
}

// RaDegNEQ applies the NEQ predicate on the "ra_deg" field.
func RaDegNEQ(v float64) predicate.Info {
	return predicate.Info(sql.FieldNEQ(FieldRaDeg, v))
}

// RaDegIn applies the In predicate on the "ra_deg" field.
func RaDegIn(vs ...float64) predicate.Info {
	return predicate.Info(sql.FieldIn(FieldRaDeg, vs...))
}

// RaDegNotIn applies the NotIn predicate on the "ra_deg" field.
func RaDegNotIn(vs ...float64) predicate.Info {
	return predicate.Info(sql.FieldNotIn(FieldRaDeg, vs...))
}

// RaDegGT applies the GT predicate on the "ra_deg" field.
func RaDegGT(v float64) predicate.Info {
	return predicate.Info(sql.FieldGT(FieldRaDeg, v))
}

// RaDegGTE applies the GTE predicate on the "ra_deg" field.
func RaDegGTE(v float64) predicate.Info {
	return predicate.Info(sql.FieldGTE(FieldRaDeg, v))
}

// RaDegLT applies the LT predicate on the "ra_deg" field.
func RaDegLT(v float64) predicate.Info {
	return predicate.Info(sql.FieldLT(FieldRaDeg, v))
}

// RaDegLTE applies the LTE predicate on the "ra_deg" field.
func RaDegLTE(v float64) predicate.Info {
	return predicate.Info(sql.FieldLTE(FieldRaDeg, v))
}

// DecDegEQ applies the EQ predicate on the "dec_deg" field.
func DecDegEQ(v float64) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldDecDeg, v))
}

// DecDegNEQ applies the NEQ predicate on the "dec_deg" field.
func DecDegNEQ(v float64) predicate.Info {
	return predicate.Info(sql.FieldNEQ(FieldDecDeg, v))
}

// DecDegIn applies the In predicate on the "dec_deg" field.
func DecDegIn(vs ...float64) predicate.Info {
	return predicate.Info(sql.FieldIn(FieldDecDeg, vs...))
}

// DecDegNotIn applies the NotIn predicate on the "dec_deg" field.
func DecDegNotIn(vs ...float64) predicate.Info {
	return predicate.Info(sql.FieldNotIn(FieldDecDeg, vs...))
}

// DecDegGT applies the GT predicate on the "dec_deg" field.
func DecDegGT(v float64) predicate.Info {
	return predicate.Info(sql.FieldGT(FieldDecDeg, v))
}

// DecDegGTE applies the GTE predicate on the "dec_deg" field.
func DecDegGTE(v float64) predicate.Info {
	return predicate.Info(sql.FieldGTE(FieldDecDeg, v))
}

// DecDegLT applies the LT predicate on the "dec_deg" field.
func DecDegLT(v float64) predicate.Info {
	return predicate.Info(sql.FieldLT(FieldDecDeg, v))
}

// DecDegLTE applies the LTE predicate on the "dec_deg" field.
func DecDegLTE(v float64) predicate.Info {
	return predicate.Info(sql.FieldLTE(FieldDecDeg, v))
}

// GalacticLongitudeEQ applies the EQ predicate on the "galactic_longitude" field.
func GalacticLongitudeEQ(v float64) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldGalacticLongitude, v))
}

// GalacticLongitudeNEQ applies the NEQ predicate on the "galactic_longitude" field.
func GalacticLongitudeNEQ(v float64) predicate.Info {
	return predicate.Info(sql.FieldNEQ(FieldGalacticLongitude, v))
}

// GalacticLongitudeIn applies the In predicate on the "galactic_longitude" field.
func GalacticLongitudeIn(vs ...float64) predicate.Info {
	return predicate.Info(sql.FieldIn(FieldGalacticLongitude, vs...))
}

// GalacticLongitudeNotIn applies the NotIn predicate on the "galactic_longitude" field.
func GalacticLongitudeNotIn(vs ...float64) predicate.Info {
	return predicate.Info(sql.FieldNotIn(FieldGalacticLongitude, vs...))
}

// GalacticLongitudeGT applies the GT predicate on the "galactic_longitude" field.
func GalacticLongitudeGT(v float64) predicate.Info {
	return predicate.Info(sql.FieldGT(FieldGalacticLongitude, v))
}

// GalacticLongitudeGTE applies the GTE predicate on the "galactic_longitude" field.
func GalacticLongitudeGTE(v float64) predicate.Info {
	return predicate.Info(sql.FieldGTE(FieldGalacticLongitude, v))
}

// GalacticLongitudeLT applies the LT predicate on the "galactic_longitude" field.
func GalacticLongitudeLT(v float64) predicate.Info {
	return predicate.Info(sql.FieldLT(FieldGalacticLongitude, v))
}

// GalacticLongitudeLTE applies the LTE predicate on the "galactic_longitude" field.
func GalacticLongitudeLTE(v float64) predicate.Info {
	return predicate.Info(sql.FieldLTE(FieldGalacticLongitude, v))
}

// GalacticLongitudeIsNil applies the IsNil predicate on the "galactic_longitude" field.
func GalacticLongitudeIsNil() predicate.Info {
	return predicate.Info(sql.FieldIsNull(FieldGalacticLongitude))
}

// GalacticLongitudeNotNil applies the NotNil predicate on the "galactic_longitude" field.
func GalacticLongitudeNotNil() predicate.Info {
	return predicate.Info(sql.FieldNotNull(FieldGalacticLongitude))
}

// GalacticLatitudeEQ applies the EQ predicate on the "galactic_latitude" field.
func GalacticLatitudeEQ(v float64) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldGalacticLatitude, v))
}

// GalacticLatitudeNEQ applies the NEQ predicate on the "galactic_latitude" field.
func GalacticLatitudeNEQ(v float64) predicate.Info {
	return predicate.Info(sql.FieldNEQ(FieldGalacticLatitude, v))
}

// GalacticLatitudeIn applies the In predicate on the "galactic_latitude" field.
func GalacticLatitudeIn(vs ...float64) predicate.Info {
	return predicate.Info(sql.FieldIn(FieldGalacticLatitude, vs...))
}

// GalacticLatitudeNotIn applies the NotIn predicate on the "galactic_latitude" field.
func GalacticLatitudeNotIn(vs ...float64) predicate.Info {
	return predicate.Info(sql.FieldNotIn(FieldGalacticLatitude, vs...))
}

// GalacticLatitudeGT applies the GT predicate on the "galactic_latitude" field.
func GalacticLatitudeGT(v float64) predicate.Info {
	return predicate.Info(sql.FieldGT(FieldGalacticLatitude, v))
}

// GalacticLatitudeGTE applies the GTE predicate on the "galactic_latitude" field.
func GalacticLatitudeGTE(v float64) predicate.Info {
	return predicate.Info(sql.FieldGTE(FieldGalacticLatitude, v))
}

// GalacticLatitudeLT applies the LT predicate on the "galactic_latitude" field.
func GalacticLatitudeLT(v float64) predicate.Info {
	return predicate.Info(sql.FieldLT(FieldGalacticLatitude, v))
}

// GalacticLatitudeLTE applies the LTE predicate on the "galactic_latitude" field.
func GalacticLatitudeLTE(v float64) predicate.Info {
	return predicate.Info(sql.FieldLTE(FieldGalacticLatitude, v))
}

// GalacticLatitudeIsNil applies the IsNil predicate on the "galactic_latitude" field.
func GalacticLatitudeIsNil() predicate.Info {
	return predicate.Info(sql.FieldIsNull(FieldGalacticLatitude))
}

// GalacticLatitudeNotNil applies the NotNil predicate on the "galactic_latitude" field.
func GalacticLatitudeNotNil() predicate.Info {
	return predicate.Info(sql.FieldNotNull(FieldGalacticLatitude))
}

// SurveyNameEQ applies the EQ predicate on the "survey_name" field.
func SurveyNameEQ(v string) predicate.Info {
	return predicate.Info(sql.FieldEQ(FieldSurveyName, v))
}

// SurveyNameNEQ applies the NEQ predicate on the "survey_name" field.
func SurveyNameNEQ(v string) predicate.Info {
	return predicate.Info(sql.FieldNEQ(FieldSurveyName, v))
}

// SurveyNameIn applies the In predicate on the "survey_name" field.
func SurveyNameIn(vs ...string) predicate.Info {
	return predicate.Info(sql.FieldIn(FieldSurveyName, vs...))
}

// SurveyNameNotIn applies the NotIn predicate on the "survey_name" field.
func SurveyNameNotIn(vs ...string) predicate.Info {
	return predicate.Info(sql.FieldNotIn(FieldSurveyName, vs...))
}

// SurveyNameGT applies the GT predicate on the "survey_name" field.
func SurveyNameGT(v string) predicate.Info {
	return predicate.Info(sql.FieldGT(FieldSurveyName, v))
}

// SurveyNameGTE applies the GTE predicate on the "survey_name" field.
func SurveyNameGTE(v string) predicate.Info {
	return predicate.Info(sql.FieldGTE(FieldSurveyName, v))
}

// SurveyNameLT applies the LT predicate on the "survey_name" field.
func SurveyNameLT(v string) predicate.Info {
	return predicate.Info(sql.FieldLT(FieldSurveyName, v))
}

// SurveyNameLTE applies the LTE predicate on the "survey_name" field.
func SurveyNameLTE(v string) predicate.Info {
	return predicate.Info(sql.FieldLTE(FieldSurveyName, v))
}

// SurveyNameContains applies the Contains predicate on the "survey_name" field.
func SurveyNameContains(v string) predicate.Info {
	return predicate.Info(sql.FieldContains(FieldSurveyName, v))
}

// SurveyNameHasPrefix applies the HasPrefix predicate on the "survey_name" field.
func SurveyNameHasPrefix(v string) predicate.Info {
	return predicate.Info(sql.FieldHasPrefix(FieldSurveyName, v))
}

// SurveyNameHasSuffix applies the HasSuffix predicate on the "survey_name" field.
func SurveyNameHasSuffix(v string) predicate.Info {
	return predicate.Info(sql.FieldHasSuffix(FieldSurveyName, v))
}

// SurveyNameIsNil applies the IsNil predicate on the "survey_name" field.
func SurveyNameIsNil() predicate.Info {
	return predicate.Info(sql.FieldIsNull(FieldSurveyName))
}

// SurveyNameNotNil applies the NotNil predicate on the "survey_name" field.
func SurveyNameNotNil() predicate.Info {
	return predicate.Info(sql.FieldNotNull(FieldSurveyName))
}

// SurveyNameEqualFold applies the EqualFold predicate on the "survey_name" field.
func SurveyNameEqualFold(v string) predicate.Info {
	return predicate.Info(sql.FieldEqualFold(FieldSurveyName, v))
}

// SurveyNameContainsFold applies the ContainsFold predicate on the "survey_name" field.
func SurveyNameContainsFold(v string) predicate.Info {
	return predicate.Info(sql.FieldContainsFold(FieldSurveyName, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Info) predicate.Info {
	return predicate.Info(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Info) predicate.Info {
	return predicate.Info(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Info) predicate.Info {
	return predicate.Info(sql.NotPredicates(p))
}
