// Code generated by ent, DO NOT EDIT.

package ent

import (
	"lersosa/app/resource/service/internal/infrastructure/file/gatewayimpl/database/ent/file"
	"lersosa/app/resource/service/internal/infrastructure/file/gatewayimpl/database/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	fileMixin := schema.File{}.Mixin()
	fileMixinFields0 := fileMixin[0].Fields()
	_ = fileMixinFields0
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescCreateTime is the schema descriptor for create_time field.
	fileDescCreateTime := fileMixinFields0[3].Descriptor()
	// file.DefaultCreateTime holds the default value on creation for the create_time field.
	file.DefaultCreateTime = fileDescCreateTime.Default.(func() time.Time)
	// fileDescUpdateTime is the schema descriptor for update_time field.
	fileDescUpdateTime := fileMixinFields0[5].Descriptor()
	// file.DefaultUpdateTime holds the default value on creation for the update_time field.
	file.DefaultUpdateTime = fileDescUpdateTime.Default.(func() time.Time)
	// file.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	file.UpdateDefaultUpdateTime = fileDescUpdateTime.UpdateDefault.(func() time.Time)
	// fileDescRemark is the schema descriptor for remark field.
	fileDescRemark := fileMixinFields0[6].Descriptor()
	// file.RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	file.RemarkValidator = fileDescRemark.Validators[0].(func(string) error)
	// fileDescVersion is the schema descriptor for version field.
	fileDescVersion := fileMixinFields0[7].Descriptor()
	// file.DefaultVersion holds the default value on creation for the version field.
	file.DefaultVersion = fileDescVersion.Default.(int32)
	// file.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	file.VersionValidator = fileDescVersion.Validators[0].(func(int32) error)
	// fileDescFileName is the schema descriptor for file_name field.
	fileDescFileName := fileFields[1].Descriptor()
	// file.DefaultFileName holds the default value on creation for the file_name field.
	file.DefaultFileName = fileDescFileName.Default.(string)
	// file.FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	file.FileNameValidator = func() func(string) error {
		validators := fileDescFileName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(file_name string) error {
			for _, fn := range fns {
				if err := fn(file_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// fileDescOriginalName is the schema descriptor for original_name field.
	fileDescOriginalName := fileFields[2].Descriptor()
	// file.DefaultOriginalName holds the default value on creation for the original_name field.
	file.DefaultOriginalName = fileDescOriginalName.Default.(string)
	// file.OriginalNameValidator is a validator for the "original_name" field. It is called by the builders before save.
	file.OriginalNameValidator = func() func(string) error {
		validators := fileDescOriginalName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(original_name string) error {
			for _, fn := range fns {
				if err := fn(original_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// fileDescFileSuffix is the schema descriptor for file_suffix field.
	fileDescFileSuffix := fileFields[3].Descriptor()
	// file.DefaultFileSuffix holds the default value on creation for the file_suffix field.
	file.DefaultFileSuffix = fileDescFileSuffix.Default.(string)
	// file.FileSuffixValidator is a validator for the "file_suffix" field. It is called by the builders before save.
	file.FileSuffixValidator = func() func(string) error {
		validators := fileDescFileSuffix.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(file_suffix string) error {
			for _, fn := range fns {
				if err := fn(file_suffix); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// fileDescURL is the schema descriptor for url field.
	fileDescURL := fileFields[4].Descriptor()
	// file.DefaultURL holds the default value on creation for the url field.
	file.DefaultURL = fileDescURL.Default.(string)
	// file.URLValidator is a validator for the "url" field. It is called by the builders before save.
	file.URLValidator = func() func(string) error {
		validators := fileDescURL.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(url string) error {
			for _, fn := range fns {
				if err := fn(url); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// fileDescExt1 is the schema descriptor for ext1 field.
	fileDescExt1 := fileFields[5].Descriptor()
	// file.DefaultExt1 holds the default value on creation for the ext1 field.
	file.DefaultExt1 = fileDescExt1.Default.(string)
	// file.Ext1Validator is a validator for the "ext1" field. It is called by the builders before save.
	file.Ext1Validator = fileDescExt1.Validators[0].(func(string) error)
	// fileDescService is the schema descriptor for service field.
	fileDescService := fileFields[7].Descriptor()
	// file.DefaultService holds the default value on creation for the service field.
	file.DefaultService = fileDescService.Default.(string)
	// file.ServiceValidator is a validator for the "service" field. It is called by the builders before save.
	file.ServiceValidator = fileDescService.Validators[0].(func(string) error)
	// fileDescID is the schema descriptor for id field.
	fileDescID := fileFields[0].Descriptor()
	// file.DefaultID holds the default value on creation for the id field.
	file.DefaultID = fileDescID.Default.(func() uuid.UUID)
}
