// Code generated by ent, DO NOT EDIT.

package file

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the file type in the database.
	Label = "file"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "oss_id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldCreateBy holds the string denoting the create_by field in the database.
	FieldCreateBy = "create_by"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateBy holds the string denoting the update_by field in the database.
	FieldUpdateBy = "update_by"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldFileName holds the string denoting the file_name field in the database.
	FieldFileName = "file_name"
	// FieldOriginalName holds the string denoting the original_name field in the database.
	FieldOriginalName = "original_name"
	// FieldFileSuffix holds the string denoting the file_suffix field in the database.
	FieldFileSuffix = "file_suffix"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldExt1 holds the string denoting the ext1 field in the database.
	FieldExt1 = "ext1"
	// FieldCreateDept holds the string denoting the create_dept field in the database.
	FieldCreateDept = "create_dept"
	// FieldService holds the string denoting the service field in the database.
	FieldService = "service"
	// Table holds the table name of the file in the database.
	Table = "sys_file"
)

// Columns holds all SQL columns for file fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldCreateBy,
	FieldCreateTime,
	FieldUpdateBy,
	FieldUpdateTime,
	FieldRemark,
	FieldVersion,
	FieldFileName,
	FieldOriginalName,
	FieldFileSuffix,
	FieldURL,
	FieldExt1,
	FieldCreateDept,
	FieldService,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	RemarkValidator func(string) error
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int32
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(int32) error
	// DefaultFileName holds the default value on creation for the "file_name" field.
	DefaultFileName string
	// FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	FileNameValidator func(string) error
	// DefaultOriginalName holds the default value on creation for the "original_name" field.
	DefaultOriginalName string
	// OriginalNameValidator is a validator for the "original_name" field. It is called by the builders before save.
	OriginalNameValidator func(string) error
	// DefaultFileSuffix holds the default value on creation for the "file_suffix" field.
	DefaultFileSuffix string
	// FileSuffixValidator is a validator for the "file_suffix" field. It is called by the builders before save.
	FileSuffixValidator func(string) error
	// DefaultURL holds the default value on creation for the "url" field.
	DefaultURL string
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// DefaultExt1 holds the default value on creation for the "ext1" field.
	DefaultExt1 string
	// Ext1Validator is a validator for the "ext1" field. It is called by the builders before save.
	Ext1Validator func(string) error
	// DefaultService holds the default value on creation for the "service" field.
	DefaultService string
	// ServiceValidator is a validator for the "service" field. It is called by the builders before save.
	ServiceValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the File queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByCreateBy orders the results by the create_by field.
func ByCreateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateBy, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateBy orders the results by the update_by field.
func ByUpdateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateBy, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByFileName orders the results by the file_name field.
func ByFileName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileName, opts...).ToFunc()
}

// ByOriginalName orders the results by the original_name field.
func ByOriginalName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalName, opts...).ToFunc()
}

// ByFileSuffix orders the results by the file_suffix field.
func ByFileSuffix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileSuffix, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByExt1 orders the results by the ext1 field.
func ByExt1(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExt1, opts...).ToFunc()
}

// ByCreateDept orders the results by the create_dept field.
func ByCreateDept(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateDept, opts...).ToFunc()
}

// ByService orders the results by the service field.
func ByService(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldService, opts...).ToFunc()
}
