// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: resource/service/v1/file/proto/file_remove.proto

package generate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 删除文件请求
type FileRemoveRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Files         []*FileRemoveRequest_File `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRemoveRequest) Reset() {
	*x = FileRemoveRequest{}
	mi := &file_resource_service_v1_file_proto_file_remove_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRemoveRequest) ProtoMessage() {}

func (x *FileRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_service_v1_file_proto_file_remove_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRemoveRequest.ProtoReflect.Descriptor instead.
func (*FileRemoveRequest) Descriptor() ([]byte, []int) {
	return file_resource_service_v1_file_proto_file_remove_proto_rawDescGZIP(), []int{0}
}

func (x *FileRemoveRequest) GetFiles() []*FileRemoveRequest_File {
	if x != nil {
		return x.Files
	}
	return nil
}

// 删除文件响应
type FileRemoveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRemoveReply) Reset() {
	*x = FileRemoveReply{}
	mi := &file_resource_service_v1_file_proto_file_remove_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRemoveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRemoveReply) ProtoMessage() {}

func (x *FileRemoveReply) ProtoReflect() protoreflect.Message {
	mi := &file_resource_service_v1_file_proto_file_remove_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRemoveReply.ProtoReflect.Descriptor instead.
func (*FileRemoveReply) Descriptor() ([]byte, []int) {
	return file_resource_service_v1_file_proto_file_remove_proto_rawDescGZIP(), []int{1}
}

// 文件
type FileRemoveRequest_File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OssId         string                 `protobuf:"bytes,1,opt,name=oss_id,json=ossId,proto3" json:"oss_id,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRemoveRequest_File) Reset() {
	*x = FileRemoveRequest_File{}
	mi := &file_resource_service_v1_file_proto_file_remove_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRemoveRequest_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRemoveRequest_File) ProtoMessage() {}

func (x *FileRemoveRequest_File) ProtoReflect() protoreflect.Message {
	mi := &file_resource_service_v1_file_proto_file_remove_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRemoveRequest_File.ProtoReflect.Descriptor instead.
func (*FileRemoveRequest_File) Descriptor() ([]byte, []int) {
	return file_resource_service_v1_file_proto_file_remove_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FileRemoveRequest_File) GetOssId() string {
	if x != nil {
		return x.OssId
	}
	return ""
}

func (x *FileRemoveRequest_File) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_resource_service_v1_file_proto_file_remove_proto protoreflect.FileDescriptor

const file_resource_service_v1_file_proto_file_remove_proto_rawDesc = "" +
	"\n" +
	"0resource/service/v1/file/proto/file_remove.proto\x12\"api.resource.service.v1.file.proto\"\x9e\x01\n" +
	"\x11FileRemoveRequest\x12P\n" +
	"\x05files\x18\x01 \x03(\v2:.api.resource.service.v1.file.proto.FileRemoveRequest.FileR\x05files\x1a7\n" +
	"\x04File\x12\x15\n" +
	"\x06oss_id\x18\x01 \x01(\tR\x05ossId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"\x11\n" +
	"\x0fFileRemoveReplyB#Z!api/resource/service/v1/file;fileb\x06proto3"

var (
	file_resource_service_v1_file_proto_file_remove_proto_rawDescOnce sync.Once
	file_resource_service_v1_file_proto_file_remove_proto_rawDescData []byte
)

func file_resource_service_v1_file_proto_file_remove_proto_rawDescGZIP() []byte {
	file_resource_service_v1_file_proto_file_remove_proto_rawDescOnce.Do(func() {
		file_resource_service_v1_file_proto_file_remove_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_service_v1_file_proto_file_remove_proto_rawDesc), len(file_resource_service_v1_file_proto_file_remove_proto_rawDesc)))
	})
	return file_resource_service_v1_file_proto_file_remove_proto_rawDescData
}

var file_resource_service_v1_file_proto_file_remove_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_resource_service_v1_file_proto_file_remove_proto_goTypes = []any{
	(*FileRemoveRequest)(nil),      // 0: api.resource.service.v1.file.proto.FileRemoveRequest
	(*FileRemoveReply)(nil),        // 1: api.resource.service.v1.file.proto.FileRemoveReply
	(*FileRemoveRequest_File)(nil), // 2: api.resource.service.v1.file.proto.FileRemoveRequest.File
}
var file_resource_service_v1_file_proto_file_remove_proto_depIdxs = []int32{
	2, // 0: api.resource.service.v1.file.proto.FileRemoveRequest.files:type_name -> api.resource.service.v1.file.proto.FileRemoveRequest.File
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_resource_service_v1_file_proto_file_remove_proto_init() }
func file_resource_service_v1_file_proto_file_remove_proto_init() {
	if File_resource_service_v1_file_proto_file_remove_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_service_v1_file_proto_file_remove_proto_rawDesc), len(file_resource_service_v1_file_proto_file_remove_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_service_v1_file_proto_file_remove_proto_goTypes,
		DependencyIndexes: file_resource_service_v1_file_proto_file_remove_proto_depIdxs,
		MessageInfos:      file_resource_service_v1_file_proto_file_remove_proto_msgTypes,
	}.Build()
	File_resource_service_v1_file_proto_file_remove_proto = out.File
	file_resource_service_v1_file_proto_file_remove_proto_goTypes = nil
	file_resource_service_v1_file_proto_file_remove_proto_depIdxs = nil
}
