// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: resource/interface/v1/file/proto/file.proto

package generate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	File_SaveFile_FullMethodName   = "/api.resource.interface.v1.file.proto.File/SaveFile"
	File_ModifyFile_FullMethodName = "/api.resource.interface.v1.file.proto.File/ModifyFile"
	File_RemoveFile_FullMethodName = "/api.resource.interface.v1.file.proto.File/RemoveFile"
	File_GetFile_FullMethodName    = "/api.resource.interface.v1.file.proto.File/GetFile"
	File_PageFile_FullMethodName   = "/api.resource.interface.v1.file.proto.File/PageFile"
	File_UploadFile_FullMethodName = "/api.resource.interface.v1.file.proto.File/UploadFile"
)

// FileClient is the client API for File service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 文件服务
type FileClient interface {
	// 新增文件
	SaveFile(ctx context.Context, in *FileSaveRequest, opts ...grpc.CallOption) (*FileSaveReply, error)
	// 修改文件
	ModifyFile(ctx context.Context, in *FileModifyRequest, opts ...grpc.CallOption) (*FileModifyReply, error)
	// 删除文件
	RemoveFile(ctx context.Context, in *FileRemoveRequest, opts ...grpc.CallOption) (*FileRemoveReply, error)
	// 获取文件
	GetFile(ctx context.Context, in *FileGetRequest, opts ...grpc.CallOption) (*FileGetReply, error)
	// 分页查询文件列表
	PageFile(ctx context.Context, in *FilePageRequest, opts ...grpc.CallOption) (*FilePageReply, error)
	// 上传文件
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileUploadRequest, FileUploadReply], error)
}

type fileClient struct {
	cc grpc.ClientConnInterface
}

func NewFileClient(cc grpc.ClientConnInterface) FileClient {
	return &fileClient{cc}
}

func (c *fileClient) SaveFile(ctx context.Context, in *FileSaveRequest, opts ...grpc.CallOption) (*FileSaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileSaveReply)
	err := c.cc.Invoke(ctx, File_SaveFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) ModifyFile(ctx context.Context, in *FileModifyRequest, opts ...grpc.CallOption) (*FileModifyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileModifyReply)
	err := c.cc.Invoke(ctx, File_ModifyFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) RemoveFile(ctx context.Context, in *FileRemoveRequest, opts ...grpc.CallOption) (*FileRemoveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileRemoveReply)
	err := c.cc.Invoke(ctx, File_RemoveFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) GetFile(ctx context.Context, in *FileGetRequest, opts ...grpc.CallOption) (*FileGetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileGetReply)
	err := c.cc.Invoke(ctx, File_GetFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) PageFile(ctx context.Context, in *FilePageRequest, opts ...grpc.CallOption) (*FilePageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilePageReply)
	err := c.cc.Invoke(ctx, File_PageFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileUploadRequest, FileUploadReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &File_ServiceDesc.Streams[0], File_UploadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileUploadRequest, FileUploadReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type File_UploadFileClient = grpc.ClientStreamingClient[FileUploadRequest, FileUploadReply]

// FileServer is the server API for File service.
// All implementations must embed UnimplementedFileServer
// for forward compatibility.
//
// 文件服务
type FileServer interface {
	// 新增文件
	SaveFile(context.Context, *FileSaveRequest) (*FileSaveReply, error)
	// 修改文件
	ModifyFile(context.Context, *FileModifyRequest) (*FileModifyReply, error)
	// 删除文件
	RemoveFile(context.Context, *FileRemoveRequest) (*FileRemoveReply, error)
	// 获取文件
	GetFile(context.Context, *FileGetRequest) (*FileGetReply, error)
	// 分页查询文件列表
	PageFile(context.Context, *FilePageRequest) (*FilePageReply, error)
	// 上传文件
	UploadFile(grpc.ClientStreamingServer[FileUploadRequest, FileUploadReply]) error
	mustEmbedUnimplementedFileServer()
}

// UnimplementedFileServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServer struct{}

func (UnimplementedFileServer) SaveFile(context.Context, *FileSaveRequest) (*FileSaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveFile not implemented")
}
func (UnimplementedFileServer) ModifyFile(context.Context, *FileModifyRequest) (*FileModifyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyFile not implemented")
}
func (UnimplementedFileServer) RemoveFile(context.Context, *FileRemoveRequest) (*FileRemoveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFile not implemented")
}
func (UnimplementedFileServer) GetFile(context.Context, *FileGetRequest) (*FileGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedFileServer) PageFile(context.Context, *FilePageRequest) (*FilePageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PageFile not implemented")
}
func (UnimplementedFileServer) UploadFile(grpc.ClientStreamingServer[FileUploadRequest, FileUploadReply]) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedFileServer) mustEmbedUnimplementedFileServer() {}
func (UnimplementedFileServer) testEmbeddedByValue()              {}

// UnsafeFileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServer will
// result in compilation errors.
type UnsafeFileServer interface {
	mustEmbedUnimplementedFileServer()
}

func RegisterFileServer(s grpc.ServiceRegistrar, srv FileServer) {
	// If the following call pancis, it indicates UnimplementedFileServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&File_ServiceDesc, srv)
}

func _File_SaveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).SaveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_SaveFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).SaveFile(ctx, req.(*FileSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_ModifyFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileModifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).ModifyFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_ModifyFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).ModifyFile(ctx, req.(*FileModifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_RemoveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).RemoveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_RemoveFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).RemoveFile(ctx, req.(*FileRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_GetFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).GetFile(ctx, req.(*FileGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_PageFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).PageFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_PageFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).PageFile(ctx, req.(*FilePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileServer).UploadFile(&grpc.GenericServerStream[FileUploadRequest, FileUploadReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type File_UploadFileServer = grpc.ClientStreamingServer[FileUploadRequest, FileUploadReply]

// File_ServiceDesc is the grpc.ServiceDesc for File service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var File_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.resource.interface.v1.file.proto.File",
	HandlerType: (*FileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveFile",
			Handler:    _File_SaveFile_Handler,
		},
		{
			MethodName: "ModifyFile",
			Handler:    _File_ModifyFile_Handler,
		},
		{
			MethodName: "RemoveFile",
			Handler:    _File_RemoveFile_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _File_GetFile_Handler,
		},
		{
			MethodName: "PageFile",
			Handler:    _File_PageFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _File_UploadFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "resource/interface/v1/file/proto/file.proto",
}
