// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: resource/interface/v1/file/proto/file.proto

package generate

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_resource_interface_v1_file_proto_file_proto protoreflect.FileDescriptor

const file_resource_interface_v1_file_proto_file_proto_rawDesc = "" +
	"\n" +
	"+resource/interface/v1/file/proto/file.proto\x12$api.resource.interface.v1.file.proto\x1a\x1cgoogle/api/annotations.proto\x1a0resource/interface/v1/file/proto/file_save.proto\x1a2resource/interface/v1/file/proto/file_modify.proto\x1a2resource/interface/v1/file/proto/file_remove.proto\x1a/resource/interface/v1/file/proto/file_get.proto\x1a0resource/interface/v1/file/proto/file_page.proto\x1a2resource/interface/v1/file/proto/file_upload.proto2\x85\a\n" +
	"\x04File\x12\x94\x01\n" +
	"\bSaveFile\x125.api.resource.interface.v1.file.proto.FileSaveRequest\x1a3.api.resource.interface.v1.file.proto.FileSaveReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/resource/v1/file\x12\x9a\x01\n" +
	"\n" +
	"ModifyFile\x127.api.resource.interface.v1.file.proto.FileModifyRequest\x1a5.api.resource.interface.v1.file.proto.FileModifyReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/resource/v1/file\x12\x97\x01\n" +
	"\n" +
	"RemoveFile\x127.api.resource.interface.v1.file.proto.FileRemoveRequest\x1a5.api.resource.interface.v1.file.proto.FileRemoveReply\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/resource/v1/file\x12\x97\x01\n" +
	"\aGetFile\x124.api.resource.interface.v1.file.proto.FileGetRequest\x1a2.api.resource.interface.v1.file.proto.FileGetReply\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/resource/v1/file/{oss_id}\x12\x91\x01\n" +
	"\bPageFile\x125.api.resource.interface.v1.file.proto.FilePageRequest\x1a3.api.resource.interface.v1.file.proto.FilePageReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/resource/v1/file\x12\x80\x01\n" +
	"\n" +
	"UploadFile\x127.api.resource.interface.v1.file.proto.FileUploadRequest\x1a5.api.resource.interface.v1.file.proto.FileUploadReply\"\x00(\x01B%Z#api/resource/interface/v1/file;fileb\x06proto3"

var file_resource_interface_v1_file_proto_file_proto_goTypes = []any{
	(*FileSaveRequest)(nil),   // 0: api.resource.interface.v1.file.proto.FileSaveRequest
	(*FileModifyRequest)(nil), // 1: api.resource.interface.v1.file.proto.FileModifyRequest
	(*FileRemoveRequest)(nil), // 2: api.resource.interface.v1.file.proto.FileRemoveRequest
	(*FileGetRequest)(nil),    // 3: api.resource.interface.v1.file.proto.FileGetRequest
	(*FilePageRequest)(nil),   // 4: api.resource.interface.v1.file.proto.FilePageRequest
	(*FileUploadRequest)(nil), // 5: api.resource.interface.v1.file.proto.FileUploadRequest
	(*FileSaveReply)(nil),     // 6: api.resource.interface.v1.file.proto.FileSaveReply
	(*FileModifyReply)(nil),   // 7: api.resource.interface.v1.file.proto.FileModifyReply
	(*FileRemoveReply)(nil),   // 8: api.resource.interface.v1.file.proto.FileRemoveReply
	(*FileGetReply)(nil),      // 9: api.resource.interface.v1.file.proto.FileGetReply
	(*FilePageReply)(nil),     // 10: api.resource.interface.v1.file.proto.FilePageReply
	(*FileUploadReply)(nil),   // 11: api.resource.interface.v1.file.proto.FileUploadReply
}
var file_resource_interface_v1_file_proto_file_proto_depIdxs = []int32{
	0,  // 0: api.resource.interface.v1.file.proto.File.SaveFile:input_type -> api.resource.interface.v1.file.proto.FileSaveRequest
	1,  // 1: api.resource.interface.v1.file.proto.File.ModifyFile:input_type -> api.resource.interface.v1.file.proto.FileModifyRequest
	2,  // 2: api.resource.interface.v1.file.proto.File.RemoveFile:input_type -> api.resource.interface.v1.file.proto.FileRemoveRequest
	3,  // 3: api.resource.interface.v1.file.proto.File.GetFile:input_type -> api.resource.interface.v1.file.proto.FileGetRequest
	4,  // 4: api.resource.interface.v1.file.proto.File.PageFile:input_type -> api.resource.interface.v1.file.proto.FilePageRequest
	5,  // 5: api.resource.interface.v1.file.proto.File.UploadFile:input_type -> api.resource.interface.v1.file.proto.FileUploadRequest
	6,  // 6: api.resource.interface.v1.file.proto.File.SaveFile:output_type -> api.resource.interface.v1.file.proto.FileSaveReply
	7,  // 7: api.resource.interface.v1.file.proto.File.ModifyFile:output_type -> api.resource.interface.v1.file.proto.FileModifyReply
	8,  // 8: api.resource.interface.v1.file.proto.File.RemoveFile:output_type -> api.resource.interface.v1.file.proto.FileRemoveReply
	9,  // 9: api.resource.interface.v1.file.proto.File.GetFile:output_type -> api.resource.interface.v1.file.proto.FileGetReply
	10, // 10: api.resource.interface.v1.file.proto.File.PageFile:output_type -> api.resource.interface.v1.file.proto.FilePageReply
	11, // 11: api.resource.interface.v1.file.proto.File.UploadFile:output_type -> api.resource.interface.v1.file.proto.FileUploadReply
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_resource_interface_v1_file_proto_file_proto_init() }
func file_resource_interface_v1_file_proto_file_proto_init() {
	if File_resource_interface_v1_file_proto_file_proto != nil {
		return
	}
	file_resource_interface_v1_file_proto_file_save_proto_init()
	file_resource_interface_v1_file_proto_file_modify_proto_init()
	file_resource_interface_v1_file_proto_file_remove_proto_init()
	file_resource_interface_v1_file_proto_file_get_proto_init()
	file_resource_interface_v1_file_proto_file_page_proto_init()
	file_resource_interface_v1_file_proto_file_upload_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_interface_v1_file_proto_file_proto_rawDesc), len(file_resource_interface_v1_file_proto_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_interface_v1_file_proto_file_proto_goTypes,
		DependencyIndexes: file_resource_interface_v1_file_proto_file_proto_depIdxs,
	}.Build()
	File_resource_interface_v1_file_proto_file_proto = out.File
	file_resource_interface_v1_file_proto_file_proto_goTypes = nil
	file_resource_interface_v1_file_proto_file_proto_depIdxs = nil
}
