// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: resource/interface/v1/file/proto/file_modify.proto

package generate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 修改文件请求
type FileModifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OssId         string                 `protobuf:"bytes,1,opt,name=oss_id,json=ossId,proto3" json:"oss_id,omitempty"`
	OriginalName  string                 `protobuf:"bytes,2,opt,name=original_name,json=originalName,proto3" json:"original_name,omitempty"`
	Ext1          string                 `protobuf:"bytes,4,opt,name=ext1,proto3" json:"ext1,omitempty"`
	UpdateBy      int64                  `protobuf:"varint,5,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	Service       string                 `protobuf:"bytes,6,opt,name=service,proto3" json:"service,omitempty"`
	Version       int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileModifyRequest) Reset() {
	*x = FileModifyRequest{}
	mi := &file_resource_interface_v1_file_proto_file_modify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileModifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileModifyRequest) ProtoMessage() {}

func (x *FileModifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_interface_v1_file_proto_file_modify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileModifyRequest.ProtoReflect.Descriptor instead.
func (*FileModifyRequest) Descriptor() ([]byte, []int) {
	return file_resource_interface_v1_file_proto_file_modify_proto_rawDescGZIP(), []int{0}
}

func (x *FileModifyRequest) GetOssId() string {
	if x != nil {
		return x.OssId
	}
	return ""
}

func (x *FileModifyRequest) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *FileModifyRequest) GetExt1() string {
	if x != nil {
		return x.Ext1
	}
	return ""
}

func (x *FileModifyRequest) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *FileModifyRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *FileModifyRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// 修改文件响应
type FileModifyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *FileModifyReply_Data  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileModifyReply) Reset() {
	*x = FileModifyReply{}
	mi := &file_resource_interface_v1_file_proto_file_modify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileModifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileModifyReply) ProtoMessage() {}

func (x *FileModifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_resource_interface_v1_file_proto_file_modify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileModifyReply.ProtoReflect.Descriptor instead.
func (*FileModifyReply) Descriptor() ([]byte, []int) {
	return file_resource_interface_v1_file_proto_file_modify_proto_rawDescGZIP(), []int{1}
}

func (x *FileModifyReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FileModifyReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FileModifyReply) GetData() *FileModifyReply_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// 数据
type FileModifyReply_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileModifyReply_Data) Reset() {
	*x = FileModifyReply_Data{}
	mi := &file_resource_interface_v1_file_proto_file_modify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileModifyReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileModifyReply_Data) ProtoMessage() {}

func (x *FileModifyReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_resource_interface_v1_file_proto_file_modify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileModifyReply_Data.ProtoReflect.Descriptor instead.
func (*FileModifyReply_Data) Descriptor() ([]byte, []int) {
	return file_resource_interface_v1_file_proto_file_modify_proto_rawDescGZIP(), []int{1, 0}
}

var File_resource_interface_v1_file_proto_file_modify_proto protoreflect.FileDescriptor

const file_resource_interface_v1_file_proto_file_modify_proto_rawDesc = "" +
	"\n" +
	"2resource/interface/v1/file/proto/file_modify.proto\x12$api.resource.interface.v1.file.proto\"\xb4\x01\n" +
	"\x11FileModifyRequest\x12\x15\n" +
	"\x06oss_id\x18\x01 \x01(\tR\x05ossId\x12#\n" +
	"\roriginal_name\x18\x02 \x01(\tR\foriginalName\x12\x12\n" +
	"\x04ext1\x18\x04 \x01(\tR\x04ext1\x12\x1b\n" +
	"\tupdate_by\x18\x05 \x01(\x03R\bupdateBy\x12\x18\n" +
	"\aservice\x18\x06 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\"\x8f\x01\n" +
	"\x0fFileModifyReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12N\n" +
	"\x04data\x18\x03 \x01(\v2:.api.resource.interface.v1.file.proto.FileModifyReply.DataR\x04data\x1a\x06\n" +
	"\x04DataB%Z#api/resource/interface/v1/file;fileb\x06proto3"

var (
	file_resource_interface_v1_file_proto_file_modify_proto_rawDescOnce sync.Once
	file_resource_interface_v1_file_proto_file_modify_proto_rawDescData []byte
)

func file_resource_interface_v1_file_proto_file_modify_proto_rawDescGZIP() []byte {
	file_resource_interface_v1_file_proto_file_modify_proto_rawDescOnce.Do(func() {
		file_resource_interface_v1_file_proto_file_modify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_interface_v1_file_proto_file_modify_proto_rawDesc), len(file_resource_interface_v1_file_proto_file_modify_proto_rawDesc)))
	})
	return file_resource_interface_v1_file_proto_file_modify_proto_rawDescData
}

var file_resource_interface_v1_file_proto_file_modify_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_resource_interface_v1_file_proto_file_modify_proto_goTypes = []any{
	(*FileModifyRequest)(nil),    // 0: api.resource.interface.v1.file.proto.FileModifyRequest
	(*FileModifyReply)(nil),      // 1: api.resource.interface.v1.file.proto.FileModifyReply
	(*FileModifyReply_Data)(nil), // 2: api.resource.interface.v1.file.proto.FileModifyReply.Data
}
var file_resource_interface_v1_file_proto_file_modify_proto_depIdxs = []int32{
	2, // 0: api.resource.interface.v1.file.proto.FileModifyReply.data:type_name -> api.resource.interface.v1.file.proto.FileModifyReply.Data
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_resource_interface_v1_file_proto_file_modify_proto_init() }
func file_resource_interface_v1_file_proto_file_modify_proto_init() {
	if File_resource_interface_v1_file_proto_file_modify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_interface_v1_file_proto_file_modify_proto_rawDesc), len(file_resource_interface_v1_file_proto_file_modify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_interface_v1_file_proto_file_modify_proto_goTypes,
		DependencyIndexes: file_resource_interface_v1_file_proto_file_modify_proto_depIdxs,
		MessageInfos:      file_resource_interface_v1_file_proto_file_modify_proto_msgTypes,
	}.Build()
	File_resource_interface_v1_file_proto_file_modify_proto = out.File
	file_resource_interface_v1_file_proto_file_modify_proto_goTypes = nil
	file_resource_interface_v1_file_proto_file_modify_proto_depIdxs = nil
}
