// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.32.0
// source: resource/interface/v1/file/proto/file.proto

package generate

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationFileGetFile = "/api.resource.interface.v1.file.proto.File/GetFile"
const OperationFileModifyFile = "/api.resource.interface.v1.file.proto.File/ModifyFile"
const OperationFilePageFile = "/api.resource.interface.v1.file.proto.File/PageFile"
const OperationFileRemoveFile = "/api.resource.interface.v1.file.proto.File/RemoveFile"
const OperationFileSaveFile = "/api.resource.interface.v1.file.proto.File/SaveFile"

type FileHTTPServer interface {
	// GetFile 获取文件
	GetFile(context.Context, *FileGetRequest) (*FileGetReply, error)
	// ModifyFile 修改文件
	ModifyFile(context.Context, *FileModifyRequest) (*FileModifyReply, error)
	// PageFile 分页查询文件列表
	PageFile(context.Context, *FilePageRequest) (*FilePageReply, error)
	// RemoveFile 删除文件
	RemoveFile(context.Context, *FileRemoveRequest) (*FileRemoveReply, error)
	// SaveFile 新增文件
	SaveFile(context.Context, *FileSaveRequest) (*FileSaveReply, error)
}

func RegisterFileHTTPServer(s *http.Server, srv FileHTTPServer) {
	r := s.Route("/")
	r.POST("/resource/v1/file", _File_SaveFile0_HTTP_Handler(srv))
	r.PUT("/resource/v1/file", _File_ModifyFile0_HTTP_Handler(srv))
	r.DELETE("/resource/v1/file", _File_RemoveFile0_HTTP_Handler(srv))
	r.GET("/resource/v1/file/{oss_id}", _File_GetFile0_HTTP_Handler(srv))
	r.GET("/resource/v1/file", _File_PageFile0_HTTP_Handler(srv))
}

func _File_SaveFile0_HTTP_Handler(srv FileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FileSaveRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileSaveFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveFile(ctx, req.(*FileSaveRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FileSaveReply)
		return ctx.Result(200, reply)
	}
}

func _File_ModifyFile0_HTTP_Handler(srv FileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FileModifyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileModifyFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ModifyFile(ctx, req.(*FileModifyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FileModifyReply)
		return ctx.Result(200, reply)
	}
}

func _File_RemoveFile0_HTTP_Handler(srv FileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FileRemoveRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileRemoveFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveFile(ctx, req.(*FileRemoveRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FileRemoveReply)
		return ctx.Result(200, reply)
	}
}

func _File_GetFile0_HTTP_Handler(srv FileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FileGetRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileGetFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetFile(ctx, req.(*FileGetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FileGetReply)
		return ctx.Result(200, reply)
	}
}

func _File_PageFile0_HTTP_Handler(srv FileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FilePageRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFilePageFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PageFile(ctx, req.(*FilePageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FilePageReply)
		return ctx.Result(200, reply)
	}
}

type FileHTTPClient interface {
	// GetFile 获取文件
	GetFile(ctx context.Context, req *FileGetRequest, opts ...http.CallOption) (rsp *FileGetReply, err error)
	// ModifyFile 修改文件
	ModifyFile(ctx context.Context, req *FileModifyRequest, opts ...http.CallOption) (rsp *FileModifyReply, err error)
	// PageFile 分页查询文件列表
	PageFile(ctx context.Context, req *FilePageRequest, opts ...http.CallOption) (rsp *FilePageReply, err error)
	// RemoveFile 删除文件
	RemoveFile(ctx context.Context, req *FileRemoveRequest, opts ...http.CallOption) (rsp *FileRemoveReply, err error)
	// SaveFile 新增文件
	SaveFile(ctx context.Context, req *FileSaveRequest, opts ...http.CallOption) (rsp *FileSaveReply, err error)
}

type FileHTTPClientImpl struct {
	cc *http.Client
}

func NewFileHTTPClient(client *http.Client) FileHTTPClient {
	return &FileHTTPClientImpl{client}
}

// GetFile 获取文件
func (c *FileHTTPClientImpl) GetFile(ctx context.Context, in *FileGetRequest, opts ...http.CallOption) (*FileGetReply, error) {
	var out FileGetReply
	pattern := "/resource/v1/file/{oss_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFileGetFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ModifyFile 修改文件
func (c *FileHTTPClientImpl) ModifyFile(ctx context.Context, in *FileModifyRequest, opts ...http.CallOption) (*FileModifyReply, error) {
	var out FileModifyReply
	pattern := "/resource/v1/file"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFileModifyFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PageFile 分页查询文件列表
func (c *FileHTTPClientImpl) PageFile(ctx context.Context, in *FilePageRequest, opts ...http.CallOption) (*FilePageReply, error) {
	var out FilePageReply
	pattern := "/resource/v1/file"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFilePageFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RemoveFile 删除文件
func (c *FileHTTPClientImpl) RemoveFile(ctx context.Context, in *FileRemoveRequest, opts ...http.CallOption) (*FileRemoveReply, error) {
	var out FileRemoveReply
	pattern := "/resource/v1/file"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFileRemoveFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SaveFile 新增文件
func (c *FileHTTPClientImpl) SaveFile(ctx context.Context, in *FileSaveRequest, opts ...http.CallOption) (*FileSaveReply, error) {
	var out FileSaveReply
	pattern := "/resource/v1/file"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFileSaveFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
