// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lersosa/app/stellar/service/internal/infrastructure/status/gatewayimpl/database/ent/status"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// StatusCreate is the builder for creating a Status entity.
type StatusCreate struct {
	config
	mutation *StatusMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *StatusCreate) SetTenantID(v uuid.UUID) *StatusCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCreateBy sets the "create_by" field.
func (_c *StatusCreate) SetCreateBy(v int64) *StatusCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *StatusCreate) SetNillableCreateBy(v *int64) *StatusCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *StatusCreate) SetCreateTime(v time.Time) *StatusCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *StatusCreate) SetNillableCreateTime(v *time.Time) *StatusCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateBy sets the "update_by" field.
func (_c *StatusCreate) SetUpdateBy(v int64) *StatusCreate {
	_c.mutation.SetUpdateBy(v)
	return _c
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_c *StatusCreate) SetNillableUpdateBy(v *int64) *StatusCreate {
	if v != nil {
		_c.SetUpdateBy(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *StatusCreate) SetUpdateTime(v time.Time) *StatusCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *StatusCreate) SetNillableUpdateTime(v *time.Time) *StatusCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *StatusCreate) SetRemark(v string) *StatusCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *StatusCreate) SetNillableRemark(v *string) *StatusCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *StatusCreate) SetVersion(v int32) *StatusCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *StatusCreate) SetNillableVersion(v *int32) *StatusCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetInfoID sets the "info_id" field.
func (_c *StatusCreate) SetInfoID(v uuid.UUID) *StatusCreate {
	_c.mutation.SetInfoID(v)
	return _c
}

// SetScore sets the "score" field.
func (_c *StatusCreate) SetScore(v float64) *StatusCreate {
	_c.mutation.SetScore(v)
	return _c
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_c *StatusCreate) SetNillableScore(v *float64) *StatusCreate {
	if v != nil {
		_c.SetScore(*v)
	}
	return _c
}

// SetFlag sets the "flag" field.
func (_c *StatusCreate) SetFlag(v int32) *StatusCreate {
	_c.mutation.SetFlag(v)
	return _c
}

// SetNillableFlag sets the "flag" field if the given value is not nil.
func (_c *StatusCreate) SetNillableFlag(v *int32) *StatusCreate {
	if v != nil {
		_c.SetFlag(*v)
	}
	return _c
}

// SetCheck sets the "check" field.
func (_c *StatusCreate) SetCheck(v int32) *StatusCreate {
	_c.mutation.SetCheck(v)
	return _c
}

// SetNillableCheck sets the "check" field if the given value is not nil.
func (_c *StatusCreate) SetNillableCheck(v *int32) *StatusCreate {
	if v != nil {
		_c.SetCheck(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StatusCreate) SetID(v uuid.UUID) *StatusCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *StatusCreate) SetNillableID(v *uuid.UUID) *StatusCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the StatusMutation object of the builder.
func (_c *StatusCreate) Mutation() *StatusMutation {
	return _c.mutation
}

// Save creates the Status in the database.
func (_c *StatusCreate) Save(ctx context.Context) (*Status, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StatusCreate) SaveX(ctx context.Context) *Status {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StatusCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StatusCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StatusCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := status.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := status.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := status.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.Score(); !ok {
		v := status.DefaultScore
		_c.mutation.SetScore(v)
	}
	if _, ok := _c.mutation.Flag(); !ok {
		v := status.DefaultFlag
		_c.mutation.SetFlag(v)
	}
	if _, ok := _c.mutation.Check(); !ok {
		v := status.DefaultCheck
		_c.mutation.SetCheck(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := status.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StatusCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Status.tenant_id"`)}
	}
	if v, ok := _c.mutation.Remark(); ok {
		if err := status.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "Status.remark": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Status.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := status.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Status.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InfoID(); !ok {
		return &ValidationError{Name: "info_id", err: errors.New(`ent: missing required field "Status.info_id"`)}
	}
	if _, ok := _c.mutation.Score(); !ok {
		return &ValidationError{Name: "score", err: errors.New(`ent: missing required field "Status.score"`)}
	}
	if _, ok := _c.mutation.Flag(); !ok {
		return &ValidationError{Name: "flag", err: errors.New(`ent: missing required field "Status.flag"`)}
	}
	if _, ok := _c.mutation.Check(); !ok {
		return &ValidationError{Name: "check", err: errors.New(`ent: missing required field "Status.check"`)}
	}
	return nil
}

func (_c *StatusCreate) sqlSave(ctx context.Context) (*Status, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StatusCreate) createSpec() (*Status, *sqlgraph.CreateSpec) {
	var (
		_node = &Status{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(status.Table, sqlgraph.NewFieldSpec(status.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(status.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(status.FieldCreateBy, field.TypeInt64, value)
		_node.CreateBy = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(status.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateBy(); ok {
		_spec.SetField(status.FieldUpdateBy, field.TypeInt64, value)
		_node.UpdateBy = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(status.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(status.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(status.FieldVersion, field.TypeInt32, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.InfoID(); ok {
		_spec.SetField(status.FieldInfoID, field.TypeUUID, value)
		_node.InfoID = value
	}
	if value, ok := _c.mutation.Score(); ok {
		_spec.SetField(status.FieldScore, field.TypeFloat64, value)
		_node.Score = value
	}
	if value, ok := _c.mutation.Flag(); ok {
		_spec.SetField(status.FieldFlag, field.TypeInt32, value)
		_node.Flag = value
	}
	if value, ok := _c.mutation.Check(); ok {
		_spec.SetField(status.FieldCheck, field.TypeInt32, value)
		_node.Check = value
	}
	return _node, _spec
}

// StatusCreateBulk is the builder for creating many Status entities in bulk.
type StatusCreateBulk struct {
	config
	err      error
	builders []*StatusCreate
}

// Save creates the Status entities in the database.
func (_c *StatusCreateBulk) Save(ctx context.Context) ([]*Status, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Status, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StatusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StatusCreateBulk) SaveX(ctx context.Context) []*Status {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StatusCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StatusCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
