// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lersosa/app/stellar/service/internal/infrastructure/status/gatewayimpl/database/ent/predicate"
	"lersosa/app/stellar/service/internal/infrastructure/status/gatewayimpl/database/ent/status"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StatusUpdate is the builder for updating Status entities.
type StatusUpdate struct {
	config
	hooks    []Hook
	mutation *StatusMutation
}

// Where appends a list predicates to the StatusUpdate builder.
func (_u *StatusUpdate) Where(ps ...predicate.Status) *StatusUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *StatusUpdate) SetCreateBy(v int64) *StatusUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *StatusUpdate) SetNillableCreateBy(v *int64) *StatusUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *StatusUpdate) AddCreateBy(v int64) *StatusUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *StatusUpdate) ClearCreateBy() *StatusUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *StatusUpdate) SetUpdateBy(v int64) *StatusUpdate {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *StatusUpdate) SetNillableUpdateBy(v *int64) *StatusUpdate {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *StatusUpdate) AddUpdateBy(v int64) *StatusUpdate {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *StatusUpdate) ClearUpdateBy() *StatusUpdate {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *StatusUpdate) SetUpdateTime(v time.Time) *StatusUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *StatusUpdate) ClearUpdateTime() *StatusUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *StatusUpdate) SetRemark(v string) *StatusUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *StatusUpdate) SetNillableRemark(v *string) *StatusUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *StatusUpdate) ClearRemark() *StatusUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetVersion sets the "version" field.
func (_u *StatusUpdate) SetVersion(v int32) *StatusUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *StatusUpdate) SetNillableVersion(v *int32) *StatusUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *StatusUpdate) AddVersion(v int32) *StatusUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetScore sets the "score" field.
func (_u *StatusUpdate) SetScore(v float64) *StatusUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *StatusUpdate) SetNillableScore(v *float64) *StatusUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *StatusUpdate) AddScore(v float64) *StatusUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetFlag sets the "flag" field.
func (_u *StatusUpdate) SetFlag(v int32) *StatusUpdate {
	_u.mutation.ResetFlag()
	_u.mutation.SetFlag(v)
	return _u
}

// SetNillableFlag sets the "flag" field if the given value is not nil.
func (_u *StatusUpdate) SetNillableFlag(v *int32) *StatusUpdate {
	if v != nil {
		_u.SetFlag(*v)
	}
	return _u
}

// AddFlag adds value to the "flag" field.
func (_u *StatusUpdate) AddFlag(v int32) *StatusUpdate {
	_u.mutation.AddFlag(v)
	return _u
}

// SetCheck sets the "check" field.
func (_u *StatusUpdate) SetCheck(v int32) *StatusUpdate {
	_u.mutation.ResetCheck()
	_u.mutation.SetCheck(v)
	return _u
}

// SetNillableCheck sets the "check" field if the given value is not nil.
func (_u *StatusUpdate) SetNillableCheck(v *int32) *StatusUpdate {
	if v != nil {
		_u.SetCheck(*v)
	}
	return _u
}

// AddCheck adds value to the "check" field.
func (_u *StatusUpdate) AddCheck(v int32) *StatusUpdate {
	_u.mutation.AddCheck(v)
	return _u
}

// Mutation returns the StatusMutation object of the builder.
func (_u *StatusUpdate) Mutation() *StatusMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StatusUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StatusUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StatusUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StatusUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StatusUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok && !_u.mutation.UpdateTimeCleared() {
		v := status.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StatusUpdate) check() error {
	if v, ok := _u.mutation.Remark(); ok {
		if err := status.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "Status.remark": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := status.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Status.version": %w`, err)}
		}
	}
	return nil
}

func (_u *StatusUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(status.Table, status.Columns, sqlgraph.NewFieldSpec(status.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(status.FieldCreateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(status.FieldCreateBy, field.TypeInt64, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(status.FieldCreateBy, field.TypeInt64)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(status.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(status.FieldUpdateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(status.FieldUpdateBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(status.FieldUpdateBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(status.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(status.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(status.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(status.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(status.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(status.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(status.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(status.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Flag(); ok {
		_spec.SetField(status.FieldFlag, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedFlag(); ok {
		_spec.AddField(status.FieldFlag, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Check(); ok {
		_spec.SetField(status.FieldCheck, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedCheck(); ok {
		_spec.AddField(status.FieldCheck, field.TypeInt32, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{status.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StatusUpdateOne is the builder for updating a single Status entity.
type StatusUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StatusMutation
}

// SetCreateBy sets the "create_by" field.
func (_u *StatusUpdateOne) SetCreateBy(v int64) *StatusUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *StatusUpdateOne) SetNillableCreateBy(v *int64) *StatusUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *StatusUpdateOne) AddCreateBy(v int64) *StatusUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *StatusUpdateOne) ClearCreateBy() *StatusUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *StatusUpdateOne) SetUpdateBy(v int64) *StatusUpdateOne {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *StatusUpdateOne) SetNillableUpdateBy(v *int64) *StatusUpdateOne {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *StatusUpdateOne) AddUpdateBy(v int64) *StatusUpdateOne {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *StatusUpdateOne) ClearUpdateBy() *StatusUpdateOne {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *StatusUpdateOne) SetUpdateTime(v time.Time) *StatusUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *StatusUpdateOne) ClearUpdateTime() *StatusUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *StatusUpdateOne) SetRemark(v string) *StatusUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *StatusUpdateOne) SetNillableRemark(v *string) *StatusUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *StatusUpdateOne) ClearRemark() *StatusUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetVersion sets the "version" field.
func (_u *StatusUpdateOne) SetVersion(v int32) *StatusUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *StatusUpdateOne) SetNillableVersion(v *int32) *StatusUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *StatusUpdateOne) AddVersion(v int32) *StatusUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetScore sets the "score" field.
func (_u *StatusUpdateOne) SetScore(v float64) *StatusUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *StatusUpdateOne) SetNillableScore(v *float64) *StatusUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *StatusUpdateOne) AddScore(v float64) *StatusUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetFlag sets the "flag" field.
func (_u *StatusUpdateOne) SetFlag(v int32) *StatusUpdateOne {
	_u.mutation.ResetFlag()
	_u.mutation.SetFlag(v)
	return _u
}

// SetNillableFlag sets the "flag" field if the given value is not nil.
func (_u *StatusUpdateOne) SetNillableFlag(v *int32) *StatusUpdateOne {
	if v != nil {
		_u.SetFlag(*v)
	}
	return _u
}

// AddFlag adds value to the "flag" field.
func (_u *StatusUpdateOne) AddFlag(v int32) *StatusUpdateOne {
	_u.mutation.AddFlag(v)
	return _u
}

// SetCheck sets the "check" field.
func (_u *StatusUpdateOne) SetCheck(v int32) *StatusUpdateOne {
	_u.mutation.ResetCheck()
	_u.mutation.SetCheck(v)
	return _u
}

// SetNillableCheck sets the "check" field if the given value is not nil.
func (_u *StatusUpdateOne) SetNillableCheck(v *int32) *StatusUpdateOne {
	if v != nil {
		_u.SetCheck(*v)
	}
	return _u
}

// AddCheck adds value to the "check" field.
func (_u *StatusUpdateOne) AddCheck(v int32) *StatusUpdateOne {
	_u.mutation.AddCheck(v)
	return _u
}

// Mutation returns the StatusMutation object of the builder.
func (_u *StatusUpdateOne) Mutation() *StatusMutation {
	return _u.mutation
}

// Where appends a list predicates to the StatusUpdate builder.
func (_u *StatusUpdateOne) Where(ps ...predicate.Status) *StatusUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StatusUpdateOne) Select(field string, fields ...string) *StatusUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Status entity.
func (_u *StatusUpdateOne) Save(ctx context.Context) (*Status, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StatusUpdateOne) SaveX(ctx context.Context) *Status {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StatusUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StatusUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StatusUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok && !_u.mutation.UpdateTimeCleared() {
		v := status.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StatusUpdateOne) check() error {
	if v, ok := _u.mutation.Remark(); ok {
		if err := status.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "Status.remark": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := status.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Status.version": %w`, err)}
		}
	}
	return nil
}

func (_u *StatusUpdateOne) sqlSave(ctx context.Context) (_node *Status, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(status.Table, status.Columns, sqlgraph.NewFieldSpec(status.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Status.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, status.FieldID)
		for _, f := range fields {
			if !status.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != status.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(status.FieldCreateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(status.FieldCreateBy, field.TypeInt64, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(status.FieldCreateBy, field.TypeInt64)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(status.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(status.FieldUpdateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(status.FieldUpdateBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(status.FieldUpdateBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(status.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(status.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(status.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(status.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(status.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(status.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(status.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(status.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Flag(); ok {
		_spec.SetField(status.FieldFlag, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedFlag(); ok {
		_spec.AddField(status.FieldFlag, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Check(); ok {
		_spec.SetField(status.FieldCheck, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedCheck(); ok {
		_spec.AddField(status.FieldCheck, field.TypeInt32, value)
	}
	_node = &Status{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{status.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
