syntax = "proto3";

package api.resource.interface.v1.file.proto;

option go_package = "api/resource/interface/v1/file;file";

// 获取文件分页请求
message FilePageRequest {
  int64 page_num = 1;
  int64 page_size = 2;
}

// 获取文件分页响应
message FilePageReply {
  // 文件
  message File {
    string oss_id = 1;
    string file_name = 2;
    string original_name = 3;
    string file_suffix = 4;
    string url = 5;
    string ext1 = 6;
    string service = 7;
    int32 version = 8;
  }

  int32 code = 1;
  string msg = 2;
  repeated File rows = 3;
  int64 total = 4;
}
