syntax = "proto3";

package api.resource.interface.v1.ossconfig.proto;

import "google/api/annotations.proto";

import "resource/interface/v1/ossconfig/proto/oss_config_save.proto";
import "resource/interface/v1/ossconfig/proto/oss_config_modify.proto";
import "resource/interface/v1/ossconfig/proto/oss_config_remove.proto";
import "resource/interface/v1/ossconfig/proto/oss_config_get.proto";
import "resource/interface/v1/ossconfig/proto/oss_config_page.proto";

option go_package = "api/resource/interface/v1/ossconfig;ossconfig";

// 资源配置服务
service OssConfig {
  // 新增资源配置
  rpc SaveOssConfig(OssConfigSaveRequest) returns (OssConfigSaveReply) {
    option (google.api.http) = {
      post: "/resource/v1/oss-config"
      body: "*"
    };
  }

  // 修改资源配置
  rpc ModifyOssConfig(OssConfigModifyRequest) returns (OssConfigModifyReply) {
    option (google.api.http) = {
      put: "/resource/v1/oss-config"
      body: "*"
    };
  }

  // 删除资源配置
  rpc RemoveOssConfig(OssConfigRemoveRequest) returns (OssConfigRemoveReply) {
    option (google.api.http) = {
      delete: "/resource/v1/oss-config"
    };
  }

  // 获取资源配置
  rpc GetOssConfig(OssConfigGetRequest) returns (OssConfigGetReply) {
    option (google.api.http) = {
      get: "/resource/v1/oss-config/{oss_config_id}"
    };
  }

  // 分页查询资源配置列表
  rpc PageOssConfig(OssConfigPageRequest) returns (OssConfigPageReply) {
    option (google.api.http) = {
      get: "/resource/v1/oss-config"
    };
  }
}
