// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lersosa/app/resource/service/internal/infrastructure/ossconfig/gatewayimpl/database/ent/ossconfig"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// OssConfigCreate is the builder for creating a OssConfig entity.
type OssConfigCreate struct {
	config
	mutation *OssConfigMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *OssConfigCreate) SetTenantID(v uuid.UUID) *OssConfigCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCreateBy sets the "create_by" field.
func (_c *OssConfigCreate) SetCreateBy(v int64) *OssConfigCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillableCreateBy(v *int64) *OssConfigCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *OssConfigCreate) SetCreateTime(v time.Time) *OssConfigCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillableCreateTime(v *time.Time) *OssConfigCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateBy sets the "update_by" field.
func (_c *OssConfigCreate) SetUpdateBy(v int64) *OssConfigCreate {
	_c.mutation.SetUpdateBy(v)
	return _c
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillableUpdateBy(v *int64) *OssConfigCreate {
	if v != nil {
		_c.SetUpdateBy(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *OssConfigCreate) SetUpdateTime(v time.Time) *OssConfigCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillableUpdateTime(v *time.Time) *OssConfigCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *OssConfigCreate) SetRemark(v string) *OssConfigCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillableRemark(v *string) *OssConfigCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *OssConfigCreate) SetVersion(v int32) *OssConfigCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillableVersion(v *int32) *OssConfigCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetConfigKey sets the "config_key" field.
func (_c *OssConfigCreate) SetConfigKey(v string) *OssConfigCreate {
	_c.mutation.SetConfigKey(v)
	return _c
}

// SetAccessKey sets the "access_key" field.
func (_c *OssConfigCreate) SetAccessKey(v string) *OssConfigCreate {
	_c.mutation.SetAccessKey(v)
	return _c
}

// SetNillableAccessKey sets the "access_key" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillableAccessKey(v *string) *OssConfigCreate {
	if v != nil {
		_c.SetAccessKey(*v)
	}
	return _c
}

// SetSecretKey sets the "secret_key" field.
func (_c *OssConfigCreate) SetSecretKey(v string) *OssConfigCreate {
	_c.mutation.SetSecretKey(v)
	return _c
}

// SetNillableSecretKey sets the "secret_key" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillableSecretKey(v *string) *OssConfigCreate {
	if v != nil {
		_c.SetSecretKey(*v)
	}
	return _c
}

// SetBucketName sets the "bucket_name" field.
func (_c *OssConfigCreate) SetBucketName(v string) *OssConfigCreate {
	_c.mutation.SetBucketName(v)
	return _c
}

// SetNillableBucketName sets the "bucket_name" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillableBucketName(v *string) *OssConfigCreate {
	if v != nil {
		_c.SetBucketName(*v)
	}
	return _c
}

// SetPrefix sets the "prefix" field.
func (_c *OssConfigCreate) SetPrefix(v string) *OssConfigCreate {
	_c.mutation.SetPrefix(v)
	return _c
}

// SetNillablePrefix sets the "prefix" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillablePrefix(v *string) *OssConfigCreate {
	if v != nil {
		_c.SetPrefix(*v)
	}
	return _c
}

// SetEndpoint sets the "endpoint" field.
func (_c *OssConfigCreate) SetEndpoint(v string) *OssConfigCreate {
	_c.mutation.SetEndpoint(v)
	return _c
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillableEndpoint(v *string) *OssConfigCreate {
	if v != nil {
		_c.SetEndpoint(*v)
	}
	return _c
}

// SetDomain sets the "domain" field.
func (_c *OssConfigCreate) SetDomain(v string) *OssConfigCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillableDomain(v *string) *OssConfigCreate {
	if v != nil {
		_c.SetDomain(*v)
	}
	return _c
}

// SetIsHTTPS sets the "is_https" field.
func (_c *OssConfigCreate) SetIsHTTPS(v string) *OssConfigCreate {
	_c.mutation.SetIsHTTPS(v)
	return _c
}

// SetNillableIsHTTPS sets the "is_https" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillableIsHTTPS(v *string) *OssConfigCreate {
	if v != nil {
		_c.SetIsHTTPS(*v)
	}
	return _c
}

// SetRegion sets the "region" field.
func (_c *OssConfigCreate) SetRegion(v string) *OssConfigCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillableRegion(v *string) *OssConfigCreate {
	if v != nil {
		_c.SetRegion(*v)
	}
	return _c
}

// SetAccessPolicy sets the "access_policy" field.
func (_c *OssConfigCreate) SetAccessPolicy(v string) *OssConfigCreate {
	_c.mutation.SetAccessPolicy(v)
	return _c
}

// SetNillableAccessPolicy sets the "access_policy" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillableAccessPolicy(v *string) *OssConfigCreate {
	if v != nil {
		_c.SetAccessPolicy(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OssConfigCreate) SetStatus(v string) *OssConfigCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillableStatus(v *string) *OssConfigCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExt1 sets the "ext1" field.
func (_c *OssConfigCreate) SetExt1(v string) *OssConfigCreate {
	_c.mutation.SetExt1(v)
	return _c
}

// SetNillableExt1 sets the "ext1" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillableExt1(v *string) *OssConfigCreate {
	if v != nil {
		_c.SetExt1(*v)
	}
	return _c
}

// SetCreateDept sets the "create_dept" field.
func (_c *OssConfigCreate) SetCreateDept(v int64) *OssConfigCreate {
	_c.mutation.SetCreateDept(v)
	return _c
}

// SetNillableCreateDept sets the "create_dept" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillableCreateDept(v *int64) *OssConfigCreate {
	if v != nil {
		_c.SetCreateDept(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OssConfigCreate) SetID(v uuid.UUID) *OssConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OssConfigCreate) SetNillableID(v *uuid.UUID) *OssConfigCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the OssConfigMutation object of the builder.
func (_c *OssConfigCreate) Mutation() *OssConfigMutation {
	return _c.mutation
}

// Save creates the OssConfig in the database.
func (_c *OssConfigCreate) Save(ctx context.Context) (*OssConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OssConfigCreate) SaveX(ctx context.Context) *OssConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OssConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OssConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OssConfigCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := ossconfig.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := ossconfig.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := ossconfig.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.AccessKey(); !ok {
		v := ossconfig.DefaultAccessKey
		_c.mutation.SetAccessKey(v)
	}
	if _, ok := _c.mutation.SecretKey(); !ok {
		v := ossconfig.DefaultSecretKey
		_c.mutation.SetSecretKey(v)
	}
	if _, ok := _c.mutation.BucketName(); !ok {
		v := ossconfig.DefaultBucketName
		_c.mutation.SetBucketName(v)
	}
	if _, ok := _c.mutation.Prefix(); !ok {
		v := ossconfig.DefaultPrefix
		_c.mutation.SetPrefix(v)
	}
	if _, ok := _c.mutation.Endpoint(); !ok {
		v := ossconfig.DefaultEndpoint
		_c.mutation.SetEndpoint(v)
	}
	if _, ok := _c.mutation.Domain(); !ok {
		v := ossconfig.DefaultDomain
		_c.mutation.SetDomain(v)
	}
	if _, ok := _c.mutation.IsHTTPS(); !ok {
		v := ossconfig.DefaultIsHTTPS
		_c.mutation.SetIsHTTPS(v)
	}
	if _, ok := _c.mutation.Region(); !ok {
		v := ossconfig.DefaultRegion
		_c.mutation.SetRegion(v)
	}
	if _, ok := _c.mutation.AccessPolicy(); !ok {
		v := ossconfig.DefaultAccessPolicy
		_c.mutation.SetAccessPolicy(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := ossconfig.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Ext1(); !ok {
		v := ossconfig.DefaultExt1
		_c.mutation.SetExt1(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := ossconfig.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OssConfigCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "OssConfig.tenant_id"`)}
	}
	if v, ok := _c.mutation.Remark(); ok {
		if err := ossconfig.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "OssConfig.remark": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "OssConfig.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := ossconfig.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "OssConfig.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ConfigKey(); !ok {
		return &ValidationError{Name: "config_key", err: errors.New(`ent: missing required field "OssConfig.config_key"`)}
	}
	if v, ok := _c.mutation.ConfigKey(); ok {
		if err := ossconfig.ConfigKeyValidator(v); err != nil {
			return &ValidationError{Name: "config_key", err: fmt.Errorf(`ent: validator failed for field "OssConfig.config_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccessKey(); !ok {
		return &ValidationError{Name: "access_key", err: errors.New(`ent: missing required field "OssConfig.access_key"`)}
	}
	if v, ok := _c.mutation.AccessKey(); ok {
		if err := ossconfig.AccessKeyValidator(v); err != nil {
			return &ValidationError{Name: "access_key", err: fmt.Errorf(`ent: validator failed for field "OssConfig.access_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SecretKey(); !ok {
		return &ValidationError{Name: "secret_key", err: errors.New(`ent: missing required field "OssConfig.secret_key"`)}
	}
	if v, ok := _c.mutation.SecretKey(); ok {
		if err := ossconfig.SecretKeyValidator(v); err != nil {
			return &ValidationError{Name: "secret_key", err: fmt.Errorf(`ent: validator failed for field "OssConfig.secret_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BucketName(); !ok {
		return &ValidationError{Name: "bucket_name", err: errors.New(`ent: missing required field "OssConfig.bucket_name"`)}
	}
	if v, ok := _c.mutation.BucketName(); ok {
		if err := ossconfig.BucketNameValidator(v); err != nil {
			return &ValidationError{Name: "bucket_name", err: fmt.Errorf(`ent: validator failed for field "OssConfig.bucket_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Prefix(); !ok {
		return &ValidationError{Name: "prefix", err: errors.New(`ent: missing required field "OssConfig.prefix"`)}
	}
	if v, ok := _c.mutation.Prefix(); ok {
		if err := ossconfig.PrefixValidator(v); err != nil {
			return &ValidationError{Name: "prefix", err: fmt.Errorf(`ent: validator failed for field "OssConfig.prefix": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Endpoint(); !ok {
		return &ValidationError{Name: "endpoint", err: errors.New(`ent: missing required field "OssConfig.endpoint"`)}
	}
	if v, ok := _c.mutation.Endpoint(); ok {
		if err := ossconfig.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "OssConfig.endpoint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "OssConfig.domain"`)}
	}
	if v, ok := _c.mutation.Domain(); ok {
		if err := ossconfig.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "OssConfig.domain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsHTTPS(); !ok {
		return &ValidationError{Name: "is_https", err: errors.New(`ent: missing required field "OssConfig.is_https"`)}
	}
	if v, ok := _c.mutation.IsHTTPS(); ok {
		if err := ossconfig.IsHTTPSValidator(v); err != nil {
			return &ValidationError{Name: "is_https", err: fmt.Errorf(`ent: validator failed for field "OssConfig.is_https": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Region(); !ok {
		return &ValidationError{Name: "region", err: errors.New(`ent: missing required field "OssConfig.region"`)}
	}
	if v, ok := _c.mutation.Region(); ok {
		if err := ossconfig.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "OssConfig.region": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccessPolicy(); !ok {
		return &ValidationError{Name: "access_policy", err: errors.New(`ent: missing required field "OssConfig.access_policy"`)}
	}
	if v, ok := _c.mutation.AccessPolicy(); ok {
		if err := ossconfig.AccessPolicyValidator(v); err != nil {
			return &ValidationError{Name: "access_policy", err: fmt.Errorf(`ent: validator failed for field "OssConfig.access_policy": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OssConfig.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := ossconfig.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OssConfig.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Ext1(); !ok {
		return &ValidationError{Name: "ext1", err: errors.New(`ent: missing required field "OssConfig.ext1"`)}
	}
	if v, ok := _c.mutation.Ext1(); ok {
		if err := ossconfig.Ext1Validator(v); err != nil {
			return &ValidationError{Name: "ext1", err: fmt.Errorf(`ent: validator failed for field "OssConfig.ext1": %w`, err)}
		}
	}
	return nil
}

func (_c *OssConfigCreate) sqlSave(ctx context.Context) (*OssConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OssConfigCreate) createSpec() (*OssConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &OssConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ossconfig.Table, sqlgraph.NewFieldSpec(ossconfig.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(ossconfig.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(ossconfig.FieldCreateBy, field.TypeInt64, value)
		_node.CreateBy = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(ossconfig.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateBy(); ok {
		_spec.SetField(ossconfig.FieldUpdateBy, field.TypeInt64, value)
		_node.UpdateBy = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(ossconfig.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(ossconfig.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(ossconfig.FieldVersion, field.TypeInt32, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.ConfigKey(); ok {
		_spec.SetField(ossconfig.FieldConfigKey, field.TypeString, value)
		_node.ConfigKey = value
	}
	if value, ok := _c.mutation.AccessKey(); ok {
		_spec.SetField(ossconfig.FieldAccessKey, field.TypeString, value)
		_node.AccessKey = value
	}
	if value, ok := _c.mutation.SecretKey(); ok {
		_spec.SetField(ossconfig.FieldSecretKey, field.TypeString, value)
		_node.SecretKey = value
	}
	if value, ok := _c.mutation.BucketName(); ok {
		_spec.SetField(ossconfig.FieldBucketName, field.TypeString, value)
		_node.BucketName = value
	}
	if value, ok := _c.mutation.Prefix(); ok {
		_spec.SetField(ossconfig.FieldPrefix, field.TypeString, value)
		_node.Prefix = value
	}
	if value, ok := _c.mutation.Endpoint(); ok {
		_spec.SetField(ossconfig.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(ossconfig.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.IsHTTPS(); ok {
		_spec.SetField(ossconfig.FieldIsHTTPS, field.TypeString, value)
		_node.IsHTTPS = value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(ossconfig.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if value, ok := _c.mutation.AccessPolicy(); ok {
		_spec.SetField(ossconfig.FieldAccessPolicy, field.TypeString, value)
		_node.AccessPolicy = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(ossconfig.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Ext1(); ok {
		_spec.SetField(ossconfig.FieldExt1, field.TypeString, value)
		_node.Ext1 = value
	}
	if value, ok := _c.mutation.CreateDept(); ok {
		_spec.SetField(ossconfig.FieldCreateDept, field.TypeInt64, value)
		_node.CreateDept = value
	}
	return _node, _spec
}

// OssConfigCreateBulk is the builder for creating many OssConfig entities in bulk.
type OssConfigCreateBulk struct {
	config
	err      error
	builders []*OssConfigCreate
}

// Save creates the OssConfig entities in the database.
func (_c *OssConfigCreateBulk) Save(ctx context.Context) ([]*OssConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OssConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OssConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OssConfigCreateBulk) SaveX(ctx context.Context) []*OssConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OssConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OssConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
