// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"lersosa/app/resource/service/internal/infrastructure/ossconfig/gatewayimpl/database/ent/ossconfig"
	"lersosa/app/resource/service/internal/infrastructure/ossconfig/gatewayimpl/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OssConfigDelete is the builder for deleting a OssConfig entity.
type OssConfigDelete struct {
	config
	hooks    []Hook
	mutation *OssConfigMutation
}

// Where appends a list predicates to the OssConfigDelete builder.
func (_d *OssConfigDelete) Where(ps ...predicate.OssConfig) *OssConfigDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OssConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OssConfigDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OssConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ossconfig.Table, sqlgraph.NewFieldSpec(ossconfig.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OssConfigDeleteOne is the builder for deleting a single OssConfig entity.
type OssConfigDeleteOne struct {
	_d *OssConfigDelete
}

// Where appends a list predicates to the OssConfigDelete builder.
func (_d *OssConfigDeleteOne) Where(ps ...predicate.OssConfig) *OssConfigDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OssConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ossconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OssConfigDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
