// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"lersosa/app/stellar/interface/internal/client/info"
	"lersosa/app/stellar/interface/internal/client/status"
	"lersosa/app/stellar/interface/internal/controller/web"
	info2 "lersosa/app/stellar/interface/internal/executor/info"
	status2 "lersosa/app/stellar/interface/internal/executor/status"
	"lersosa/app/stellar/interface/internal/infrastructure/conf"
	"lersosa/app/stellar/interface/internal/server"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, client *conf.Client, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	infoClient, err := info.ProvideClient(client)
	if err != nil {
		return nil, nil, err
	}
	client2 := info.NewClient(infoClient)
	statusClient, err := status.ProvideClient(client)
	if err != nil {
		return nil, nil, err
	}
	client3 := status.NewClient(statusClient)
	executor := info2.NewExecutor(client2, client3)
	infoController := web.NewInfoController(executor)
	statusExecutor := status2.NewExecutor(client3)
	statusController := web.NewStatusController(statusExecutor)
	grpcServer := server.NewGRPCServer(confServer, infoController, statusController, logger)
	httpServer := server.NewHTTPServer(confServer, infoController, statusController, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
