# =========================== 服务器配置 ===========================
server:
  port: ${SERVER_PORT:9206}
  ssl:
    enabled: @SSL-ENABLED@
    key-store: classpath:scg-keystore.p12
    key-alias: ${spring.application.name}
    key-store-type: PKCS12
    key-store-password: Zcx@223852//
  http2:
    enabled: @SSL-ENABLED@
  forward-headers-strategy: framework
  shutdown: graceful

# =========================== Spring 配置 ===========================
spring:
  application:
    name: @pom.parent.artifactId@
  profiles:
    active: @PROFILE-ACTIVE@

# ========================== Nacos 配置 ===========================
---
spring:
  cloud:
    nacos:
      server-addr: @NACOS-SERVER-ADDRESS@
      username: @NACOS-USERNAME@
      password: @NACOS-PASSWORD@
      discovery:
        secure: @SSL-ENABLED@
        namespace: @NACOS-NAMESPACE@
        group: @NACOS-SERVICE-GROUP@
        cluster-name: ${spring.application.name}
      config:
        namespace: @NACOS-NAMESPACE@
        file-extension: yml
  config:
    import:
      - optional:nacos:application-common.${spring.cloud.nacos.config.file-extension}?group=@NACOS-DEFAULT-GROUP@
      - optional:nacos:datasource.${spring.cloud.nacos.config.file-extension}?group=@NACOS-DEFAULT-GROUP@
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}?group=@NACOS-SERVICE-GROUP@
