version: '3.8'

services:
  #####################################################################
  ###################                       基础组件                       ###################
  #####################################################################

  lersosa-mysql:
    image: mysql:latest
    container_name: lersosa-mysql-prod
    build:
      context: ./lersosa
    networks:
      lersosa-network-prod:
        aliases:
          - lersosa-mysql
    ports:
      - "3307:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: Zcx@223852//
      MYSQL_DATABASE: lersosa-cloud
    volumes:
      - ./lersosa/mysql/conf:/etc/mysql/conf.d
      - ./lersosa/mysql/logs:/logs
      - ./lersosa/mysql/data:/var/lib/mysql
    privileged: true

  lersosa-redis:
    image: redis:latest
    container_name: lersosa-redis-prod
    build:
      context: ./lersosa
    networks:
      lersosa-network-prod:
        aliases:
          - lersosa-redis
    ports:
      - "6380:6379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./lersosa/redis/conf:/redis/config
      - ./lersosa/redis/data/:/redis/data/
    command: "redis-server /redis/config/redis.conf"
    privileged: true

  lersosa-minio:
    image: minio/minio:latest
    container_name: lersosa-minio-prod
    build:
      context: ./lersosa
    networks:
      lersosa-network-prod:
        aliases:
          - lersosa-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: lersosa
      MINIO_ROOT_PASSWORD: Zcx@223852//
      MINIO_COMPRESS: "o"
      MINIO_COMPRESS_EXTENSIONS: ""
      MINIO_COMPRESS_MIME_TYPES: ""
    volumes:
      - ./lersosa/minio/data:/data
      - ./lersosa/minio/config:/root/.minio/
    command: server --address ':9000' --console-address ':9001' /data
    privileged: true

  #####################################################################
  ###################                       界面模块                       ###################
  #####################################################################

  lersosa-nginx:
    image: nginx:latest
    container_name: lersosa-nginx-prod
    build:
      context: ./lersosa
    networks:
      lersosa-network-prod:
        aliases:
          - lersosa-nginx
    ports:
      - "85:80"
      - "443:443"
    volumes:
      - ./lersosa/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./lersosa/nginx/logs:/var/log/nginx
      - ./lersosa/nginx/cert:/etc/nginx/cert
      - ./lersosa/nginx/html:/usr/share/nginx/html
    privileged: true
    depends_on:
      - lersosa-gateway
    links:
      - lersosa-gateway

  #####################################################################
  ###################                       管理模块                       ###################
  #####################################################################

  lersosa-nacos:
    image: crpi-qn9wg7g2bv3rmafm.cn-hangzhou.personal.cr.aliyuncs.com/leyramu/lersosa-visual-nacos:3.0.0
    container_name: lersosa-nacos-prod
    build:
      context: ./lersosa
    networks:
      lersosa-network-prod:
        aliases:
          - lersosa-nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    environment:
      TZ: Asia/Shanghai
      JAVA_OPTS: "-Xms256m -Xmx512m"
    volumes:
      - ./lersosa/lersosa-visual-nacos/logs/:/root/nacos/logs
    depends_on:
      - lersosa-mysql

  lersosa-sentinel:
    image: crpi-qn9wg7g2bv3rmafm.cn-hangzhou.personal.cr.aliyuncs.com/leyramu/lersosa-visual-sentinel:3.0.0
    container_name: lersosa-sentinel-prod
    build:
      context: ./lersosa
    networks:
      lersosa-network-prod:
        aliases:
          - lersosa-sentinel
    ports:
      - "8718:8718"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./lersosa/lersosa-visual-sentinel/logs/:/lersosa/sentinel/visual/logs
      - ./skywalking/agent/:/lersosa/skywalking/agent
    restart: always

  lersosa-seata:
    image: crpi-qn9wg7g2bv3rmafm.cn-hangzhou.personal.cr.aliyuncs.com/leyramu/lersosa-visual-seata:3.0.0
    container_name: lersosa-seata-prod
    build:
      context: ./lersosa
    networks:
      lersosa-network-prod:
        aliases:
          - lersosa-seata
    ports:
      - "8091:8091"
      - "7091:7091"
    environment:
      TZ: Asia/Shanghai
      SEATA_PORT: 8091
    volumes:
      - ./lersosa/lersosa-visual-seata/logs/:/lersosa/visual/seata/logs
      - ./skywalking/agent/:/lersosa/skywalking/agent
    privileged: true
    depends_on:
      - lersosa-mysql

  lersosa-snailjob:
    image: crpi-qn9wg7g2bv3rmafm.cn-hangzhou.personal.cr.aliyuncs.com/leyramu/lersosa-visual-snailjob:3.0.0
    container_name: lersosa-snailjob-prod
    build:
      context: ./lersosa
    networks:
      lersosa-network-prod:
        aliases:
          - lersosa-snailjob
    ports:
      - "8800:8800"
      - "17888:17888"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./lersosa/lersosa-visual-snailjob/logs/:/lersosa/visual/snailjob/logs
    depends_on:
      - lersosa-mysql

  lersosa-monitor:
    image: crpi-qn9wg7g2bv3rmafm.cn-hangzhou.personal.cr.aliyuncs.com/leyramu/lersosa-visual-monitor:3.0.0
    container_name: lersosa-monitor-prod
    build:
      context: ./lersosa
    networks:
      lersosa-network-prod:
        aliases:
          - lersosa-monitor
    ports:
      - "9120:9120"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./lersosa/lersosa-visual-monitor/logs/:/lersosa/visual/monitor/logs
      - ./skywalking/agent/:/lersosa/skywalking/agent
    privileged: true

  #####################################################################
  ###################                       网关模块                       ###################
  #####################################################################

  lersosa-gateway:
    image: crpi-qn9wg7g2bv3rmafm.cn-hangzhou.personal.cr.aliyuncs.com/leyramu/lersosa-gateway-api:3.0.0
    container_name: lersosa-gateway-prod
    build:
      context: ./lersosa
    networks:
      lersosa-network-prod:
        aliases:
          - lersosa-gateway
    ports:
      - "8980:8080"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./lersosa/lersosa-gateway-api/logs/:/lersosa/gateway/api/logs
      - ./lersosa/skywalking/agent/:/lersosa/skywalking/agent
    privileged: true

  #####################################################################
  ###################                       业务模块                       ###################
  #####################################################################

  lersosa-auth:
    image: crpi-qn9wg7g2bv3rmafm.cn-hangzhou.personal.cr.aliyuncs.com/leyramu/lersosa-service-auth:3.0.0
    container_name: lersosa-auth-prod
    build:
      context: ./lersosa
    networks:
      lersosa-network-prod:
        aliases:
          - lersosa-auth
    ports:
      - "9310:9310"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./lersosa/lersosa-service-auth/logs/:/lersosa/service/auth/logs
      - ./lersosa/skywalking/agent/:/lersosa/skywalking/agent
    privileged: true

  lersosa-system:
    image: crpi-qn9wg7g2bv3rmafm.cn-hangzhou.personal.cr.aliyuncs.com/leyramu/lersosa-service-system:3.0.0
    container_name: lersosa-system-prod
    build:
      context: ./lersosa
    networks:
      lersosa-network-prod:
        aliases:
          - lersosa-system
    ports:
      - "9201:9201"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./lersosa/lersosa-service-system/logs/:/lersosa/service/system/logs
      - ./lersosa/skywalking/agent/:/lersosa/skywalking/agent
    privileged: true

  lersosa-gen:
    image: crpi-qn9wg7g2bv3rmafm.cn-hangzhou.personal.cr.aliyuncs.com/leyramu/lersosa-service-gen:3.0.0
    container_name: lersosa-gen-prod
    build:
      context: ./lersosa
    networks:
      lersosa-network-prod:
        aliases:
          - lersosa-gen
    ports:
      - "9202:9202"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./lersosa/lersosa-service-gen/logs/:/lersosa/service/gen/logs
      - ./lersosa/skywalking/agent/:/lersosa/skywalking/agent
    privileged: true

  lersosa-job:
    image: crpi-qn9wg7g2bv3rmafm.cn-hangzhou.personal.cr.aliyuncs.com/leyramu/lersosa-service-job:3.0.0
    container_name: lersosa-job-prod
    build:
      context: ./lersosa
    networks:
      lersosa-network-prod:
        aliases:
          - lersosa-job
    ports:
      - "9203:9203"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./lersosa/lersosa-service-job/logs/:/lersosa/service/job/logs
      - ./lersosa/skywalking/agent/:/lersosa/skywalking/agent
    privileged: true

  lersosa-resource:
    image: crpi-qn9wg7g2bv3rmafm.cn-hangzhou.personal.cr.aliyuncs.com/leyramu/lersosa-service-resource:3.0.0
    container_name: lersosa-resource-prod
    build:
      context: ./lersosa
    networks:
      lersosa-network-prod:
        aliases:
          - lersosa-resource
    ports:
      - "9204:9204"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./lersosa/lersosa-service-resource/logs/:/lersosa/service/resource/logs
      - ./lersosa/skywalking/agent/:/lersosa/skywalking/agent
    privileged: true

  lersosa-workflow:
    image: crpi-qn9wg7g2bv3rmafm.cn-hangzhou.personal.cr.aliyuncs.com/leyramu/lersosa-service-workflow:3.0.0
    container_name: lersosa-workflow-prod
    build:
      context: ./lersosa
    networks:
      lersosa-network-prod:
        aliases:
          - lersosa-workflow
    ports:
      - "9205:9205"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./lersosa/lersosa-service-workflow/logs/:/lersosa/service/workflow/logs
      - ./lersosa/skywalking/agent/:/lersosa/skywalking/agent
    privileged: true

#####################################################################
###################                       环境网络                       ###################
#####################################################################

networks:
  lersosa-network-prod:
    name: lersosa-network-prod
    driver: bridge
    ipam:
      config:
        - subnet: 176.17.0.0/16
          gateway: 176.17.0.1
