// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: resource/interface/v1/ossconfig/proto/oss_config_remove.proto

package generate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 删除资源配置请求
type OssConfigRemoveRequest struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	OssConfigs    []*OssConfigRemoveRequest_OssConfig `protobuf:"bytes,1,rep,name=oss_configs,json=ossConfigs,proto3" json:"oss_configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OssConfigRemoveRequest) Reset() {
	*x = OssConfigRemoveRequest{}
	mi := &file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OssConfigRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OssConfigRemoveRequest) ProtoMessage() {}

func (x *OssConfigRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OssConfigRemoveRequest.ProtoReflect.Descriptor instead.
func (*OssConfigRemoveRequest) Descriptor() ([]byte, []int) {
	return file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_rawDescGZIP(), []int{0}
}

func (x *OssConfigRemoveRequest) GetOssConfigs() []*OssConfigRemoveRequest_OssConfig {
	if x != nil {
		return x.OssConfigs
	}
	return nil
}

// 删除资源配置响应
type OssConfigRemoveReply struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Code          int32                      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *OssConfigRemoveReply_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OssConfigRemoveReply) Reset() {
	*x = OssConfigRemoveReply{}
	mi := &file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OssConfigRemoveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OssConfigRemoveReply) ProtoMessage() {}

func (x *OssConfigRemoveReply) ProtoReflect() protoreflect.Message {
	mi := &file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OssConfigRemoveReply.ProtoReflect.Descriptor instead.
func (*OssConfigRemoveReply) Descriptor() ([]byte, []int) {
	return file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_rawDescGZIP(), []int{1}
}

func (x *OssConfigRemoveReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OssConfigRemoveReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OssConfigRemoveReply) GetData() *OssConfigRemoveReply_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// 资源配置
type OssConfigRemoveRequest_OssConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OssConfigId   string                 `protobuf:"bytes,1,opt,name=oss_config_id,json=ossConfigId,proto3" json:"oss_config_id,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OssConfigRemoveRequest_OssConfig) Reset() {
	*x = OssConfigRemoveRequest_OssConfig{}
	mi := &file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OssConfigRemoveRequest_OssConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OssConfigRemoveRequest_OssConfig) ProtoMessage() {}

func (x *OssConfigRemoveRequest_OssConfig) ProtoReflect() protoreflect.Message {
	mi := &file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OssConfigRemoveRequest_OssConfig.ProtoReflect.Descriptor instead.
func (*OssConfigRemoveRequest_OssConfig) Descriptor() ([]byte, []int) {
	return file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_rawDescGZIP(), []int{0, 0}
}

func (x *OssConfigRemoveRequest_OssConfig) GetOssConfigId() string {
	if x != nil {
		return x.OssConfigId
	}
	return ""
}

func (x *OssConfigRemoveRequest_OssConfig) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// 数据
type OssConfigRemoveReply_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OssConfigRemoveReply_Data) Reset() {
	*x = OssConfigRemoveReply_Data{}
	mi := &file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OssConfigRemoveReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OssConfigRemoveReply_Data) ProtoMessage() {}

func (x *OssConfigRemoveReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OssConfigRemoveReply_Data.ProtoReflect.Descriptor instead.
func (*OssConfigRemoveReply_Data) Descriptor() ([]byte, []int) {
	return file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_rawDescGZIP(), []int{1, 0}
}

var File_resource_interface_v1_ossconfig_proto_oss_config_remove_proto protoreflect.FileDescriptor

const file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_rawDesc = "" +
	"\n" +
	"=resource/interface/v1/ossconfig/proto/oss_config_remove.proto\x12)api.resource.interface.v1.ossconfig.proto\"\xd1\x01\n" +
	"\x16OssConfigRemoveRequest\x12l\n" +
	"\voss_configs\x18\x01 \x03(\v2K.api.resource.interface.v1.ossconfig.proto.OssConfigRemoveRequest.OssConfigR\n" +
	"ossConfigs\x1aI\n" +
	"\tOssConfig\x12\"\n" +
	"\ross_config_id\x18\x01 \x01(\tR\vossConfigId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"\x9e\x01\n" +
	"\x14OssConfigRemoveReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12X\n" +
	"\x04data\x18\x03 \x01(\v2D.api.resource.interface.v1.ossconfig.proto.OssConfigRemoveReply.DataR\x04data\x1a\x06\n" +
	"\x04DataB/Z-api/resource/interface/v1/ossconfig;ossconfigb\x06proto3"

var (
	file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_rawDescOnce sync.Once
	file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_rawDescData []byte
)

func file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_rawDescGZIP() []byte {
	file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_rawDescOnce.Do(func() {
		file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_rawDesc), len(file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_rawDesc)))
	})
	return file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_rawDescData
}

var file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_goTypes = []any{
	(*OssConfigRemoveRequest)(nil),           // 0: api.resource.interface.v1.ossconfig.proto.OssConfigRemoveRequest
	(*OssConfigRemoveReply)(nil),             // 1: api.resource.interface.v1.ossconfig.proto.OssConfigRemoveReply
	(*OssConfigRemoveRequest_OssConfig)(nil), // 2: api.resource.interface.v1.ossconfig.proto.OssConfigRemoveRequest.OssConfig
	(*OssConfigRemoveReply_Data)(nil),        // 3: api.resource.interface.v1.ossconfig.proto.OssConfigRemoveReply.Data
}
var file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_depIdxs = []int32{
	2, // 0: api.resource.interface.v1.ossconfig.proto.OssConfigRemoveRequest.oss_configs:type_name -> api.resource.interface.v1.ossconfig.proto.OssConfigRemoveRequest.OssConfig
	3, // 1: api.resource.interface.v1.ossconfig.proto.OssConfigRemoveReply.data:type_name -> api.resource.interface.v1.ossconfig.proto.OssConfigRemoveReply.Data
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_init() }
func file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_init() {
	if File_resource_interface_v1_ossconfig_proto_oss_config_remove_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_rawDesc), len(file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_goTypes,
		DependencyIndexes: file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_depIdxs,
		MessageInfos:      file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_msgTypes,
	}.Build()
	File_resource_interface_v1_ossconfig_proto_oss_config_remove_proto = out.File
	file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_goTypes = nil
	file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_depIdxs = nil
}
