// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: resource/interface/v1/ossconfig/proto/oss_config.proto

package generate

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_resource_interface_v1_ossconfig_proto_oss_config_proto protoreflect.FileDescriptor

const file_resource_interface_v1_ossconfig_proto_oss_config_proto_rawDesc = "" +
	"\n" +
	"6resource/interface/v1/ossconfig/proto/oss_config.proto\x12)api.resource.interface.v1.ossconfig.proto\x1a\x1cgoogle/api/annotations.proto\x1a;resource/interface/v1/ossconfig/proto/oss_config_save.proto\x1a=resource/interface/v1/ossconfig/proto/oss_config_modify.proto\x1a=resource/interface/v1/ossconfig/proto/oss_config_remove.proto\x1a:resource/interface/v1/ossconfig/proto/oss_config_get.proto\x1a;resource/interface/v1/ossconfig/proto/oss_config_page.proto2\xa9\a\n" +
	"\tOssConfig\x12\xb3\x01\n" +
	"\rSaveOssConfig\x12?.api.resource.interface.v1.ossconfig.proto.OssConfigSaveRequest\x1a=.api.resource.interface.v1.ossconfig.proto.OssConfigSaveReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/resource/v1/oss-config\x12\xb9\x01\n" +
	"\x0fModifyOssConfig\x12A.api.resource.interface.v1.ossconfig.proto.OssConfigModifyRequest\x1a?.api.resource.interface.v1.ossconfig.proto.OssConfigModifyReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/resource/v1/oss-config\x12\xb6\x01\n" +
	"\x0fRemoveOssConfig\x12A.api.resource.interface.v1.ossconfig.proto.OssConfigRemoveRequest\x1a?.api.resource.interface.v1.ossconfig.proto.OssConfigRemoveReply\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/resource/v1/oss-config\x12\xbd\x01\n" +
	"\fGetOssConfig\x12>.api.resource.interface.v1.ossconfig.proto.OssConfigGetRequest\x1a<.api.resource.interface.v1.ossconfig.proto.OssConfigGetReply\"/\x82\xd3\xe4\x93\x02)\x12'/resource/v1/oss-config/{oss_config_id}\x12\xb0\x01\n" +
	"\rPageOssConfig\x12?.api.resource.interface.v1.ossconfig.proto.OssConfigPageRequest\x1a=.api.resource.interface.v1.ossconfig.proto.OssConfigPageReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/resource/v1/oss-configB/Z-api/resource/interface/v1/ossconfig;ossconfigb\x06proto3"

var file_resource_interface_v1_ossconfig_proto_oss_config_proto_goTypes = []any{
	(*OssConfigSaveRequest)(nil),   // 0: api.resource.interface.v1.ossconfig.proto.OssConfigSaveRequest
	(*OssConfigModifyRequest)(nil), // 1: api.resource.interface.v1.ossconfig.proto.OssConfigModifyRequest
	(*OssConfigRemoveRequest)(nil), // 2: api.resource.interface.v1.ossconfig.proto.OssConfigRemoveRequest
	(*OssConfigGetRequest)(nil),    // 3: api.resource.interface.v1.ossconfig.proto.OssConfigGetRequest
	(*OssConfigPageRequest)(nil),   // 4: api.resource.interface.v1.ossconfig.proto.OssConfigPageRequest
	(*OssConfigSaveReply)(nil),     // 5: api.resource.interface.v1.ossconfig.proto.OssConfigSaveReply
	(*OssConfigModifyReply)(nil),   // 6: api.resource.interface.v1.ossconfig.proto.OssConfigModifyReply
	(*OssConfigRemoveReply)(nil),   // 7: api.resource.interface.v1.ossconfig.proto.OssConfigRemoveReply
	(*OssConfigGetReply)(nil),      // 8: api.resource.interface.v1.ossconfig.proto.OssConfigGetReply
	(*OssConfigPageReply)(nil),     // 9: api.resource.interface.v1.ossconfig.proto.OssConfigPageReply
}
var file_resource_interface_v1_ossconfig_proto_oss_config_proto_depIdxs = []int32{
	0, // 0: api.resource.interface.v1.ossconfig.proto.OssConfig.SaveOssConfig:input_type -> api.resource.interface.v1.ossconfig.proto.OssConfigSaveRequest
	1, // 1: api.resource.interface.v1.ossconfig.proto.OssConfig.ModifyOssConfig:input_type -> api.resource.interface.v1.ossconfig.proto.OssConfigModifyRequest
	2, // 2: api.resource.interface.v1.ossconfig.proto.OssConfig.RemoveOssConfig:input_type -> api.resource.interface.v1.ossconfig.proto.OssConfigRemoveRequest
	3, // 3: api.resource.interface.v1.ossconfig.proto.OssConfig.GetOssConfig:input_type -> api.resource.interface.v1.ossconfig.proto.OssConfigGetRequest
	4, // 4: api.resource.interface.v1.ossconfig.proto.OssConfig.PageOssConfig:input_type -> api.resource.interface.v1.ossconfig.proto.OssConfigPageRequest
	5, // 5: api.resource.interface.v1.ossconfig.proto.OssConfig.SaveOssConfig:output_type -> api.resource.interface.v1.ossconfig.proto.OssConfigSaveReply
	6, // 6: api.resource.interface.v1.ossconfig.proto.OssConfig.ModifyOssConfig:output_type -> api.resource.interface.v1.ossconfig.proto.OssConfigModifyReply
	7, // 7: api.resource.interface.v1.ossconfig.proto.OssConfig.RemoveOssConfig:output_type -> api.resource.interface.v1.ossconfig.proto.OssConfigRemoveReply
	8, // 8: api.resource.interface.v1.ossconfig.proto.OssConfig.GetOssConfig:output_type -> api.resource.interface.v1.ossconfig.proto.OssConfigGetReply
	9, // 9: api.resource.interface.v1.ossconfig.proto.OssConfig.PageOssConfig:output_type -> api.resource.interface.v1.ossconfig.proto.OssConfigPageReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resource_interface_v1_ossconfig_proto_oss_config_proto_init() }
func file_resource_interface_v1_ossconfig_proto_oss_config_proto_init() {
	if File_resource_interface_v1_ossconfig_proto_oss_config_proto != nil {
		return
	}
	file_resource_interface_v1_ossconfig_proto_oss_config_save_proto_init()
	file_resource_interface_v1_ossconfig_proto_oss_config_modify_proto_init()
	file_resource_interface_v1_ossconfig_proto_oss_config_remove_proto_init()
	file_resource_interface_v1_ossconfig_proto_oss_config_get_proto_init()
	file_resource_interface_v1_ossconfig_proto_oss_config_page_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_interface_v1_ossconfig_proto_oss_config_proto_rawDesc), len(file_resource_interface_v1_ossconfig_proto_oss_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_interface_v1_ossconfig_proto_oss_config_proto_goTypes,
		DependencyIndexes: file_resource_interface_v1_ossconfig_proto_oss_config_proto_depIdxs,
	}.Build()
	File_resource_interface_v1_ossconfig_proto_oss_config_proto = out.File
	file_resource_interface_v1_ossconfig_proto_oss_config_proto_goTypes = nil
	file_resource_interface_v1_ossconfig_proto_oss_config_proto_depIdxs = nil
}
