// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: stellar/service/v1/info/proto/info.proto

package generate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_stellar_service_v1_info_proto_info_proto protoreflect.FileDescriptor

const file_stellar_service_v1_info_proto_info_proto_rawDesc = "" +
	"\n" +
	"(stellar/service/v1/info/proto/info.proto\x12!api.stellar.service.v1.info.proto\x1a-stellar/service/v1/info/proto/info_save.proto\x1a/stellar/service/v1/info/proto/info_modify.proto\x1a/stellar/service/v1/info/proto/info_remove.proto\x1a,stellar/service/v1/info/proto/info_get.proto\x1a-stellar/service/v1/info/proto/info_page.proto\x1a-stellar/service/v1/info/proto/info_list.proto2\xc7\x05\n" +
	"\x04Info\x12r\n" +
	"\bSaveInfo\x122.api.stellar.service.v1.info.proto.InfoSaveRequest\x1a0.api.stellar.service.v1.info.proto.InfoSaveReply\"\x00\x12x\n" +
	"\n" +
	"ModifyInfo\x124.api.stellar.service.v1.info.proto.InfoModifyRequest\x1a2.api.stellar.service.v1.info.proto.InfoModifyReply\"\x00\x12x\n" +
	"\n" +
	"RemoveInfo\x124.api.stellar.service.v1.info.proto.InfoRemoveRequest\x1a2.api.stellar.service.v1.info.proto.InfoRemoveReply\"\x00\x12o\n" +
	"\aGetInfo\x121.api.stellar.service.v1.info.proto.InfoGetRequest\x1a/.api.stellar.service.v1.info.proto.InfoGetReply\"\x00\x12r\n" +
	"\bPageInfo\x122.api.stellar.service.v1.info.proto.InfoPageRequest\x1a0.api.stellar.service.v1.info.proto.InfoPageReply\"\x00\x12r\n" +
	"\bListInfo\x122.api.stellar.service.v1.info.proto.InfoListRequest\x1a0.api.stellar.service.v1.info.proto.InfoListReply\"\x00B\"Z api/stellar/service/v1/info;infob\x06proto3"

var file_stellar_service_v1_info_proto_info_proto_goTypes = []any{
	(*InfoSaveRequest)(nil),   // 0: api.stellar.service.v1.info.proto.InfoSaveRequest
	(*InfoModifyRequest)(nil), // 1: api.stellar.service.v1.info.proto.InfoModifyRequest
	(*InfoRemoveRequest)(nil), // 2: api.stellar.service.v1.info.proto.InfoRemoveRequest
	(*InfoGetRequest)(nil),    // 3: api.stellar.service.v1.info.proto.InfoGetRequest
	(*InfoPageRequest)(nil),   // 4: api.stellar.service.v1.info.proto.InfoPageRequest
	(*InfoListRequest)(nil),   // 5: api.stellar.service.v1.info.proto.InfoListRequest
	(*InfoSaveReply)(nil),     // 6: api.stellar.service.v1.info.proto.InfoSaveReply
	(*InfoModifyReply)(nil),   // 7: api.stellar.service.v1.info.proto.InfoModifyReply
	(*InfoRemoveReply)(nil),   // 8: api.stellar.service.v1.info.proto.InfoRemoveReply
	(*InfoGetReply)(nil),      // 9: api.stellar.service.v1.info.proto.InfoGetReply
	(*InfoPageReply)(nil),     // 10: api.stellar.service.v1.info.proto.InfoPageReply
	(*InfoListReply)(nil),     // 11: api.stellar.service.v1.info.proto.InfoListReply
}
var file_stellar_service_v1_info_proto_info_proto_depIdxs = []int32{
	0,  // 0: api.stellar.service.v1.info.proto.Info.SaveInfo:input_type -> api.stellar.service.v1.info.proto.InfoSaveRequest
	1,  // 1: api.stellar.service.v1.info.proto.Info.ModifyInfo:input_type -> api.stellar.service.v1.info.proto.InfoModifyRequest
	2,  // 2: api.stellar.service.v1.info.proto.Info.RemoveInfo:input_type -> api.stellar.service.v1.info.proto.InfoRemoveRequest
	3,  // 3: api.stellar.service.v1.info.proto.Info.GetInfo:input_type -> api.stellar.service.v1.info.proto.InfoGetRequest
	4,  // 4: api.stellar.service.v1.info.proto.Info.PageInfo:input_type -> api.stellar.service.v1.info.proto.InfoPageRequest
	5,  // 5: api.stellar.service.v1.info.proto.Info.ListInfo:input_type -> api.stellar.service.v1.info.proto.InfoListRequest
	6,  // 6: api.stellar.service.v1.info.proto.Info.SaveInfo:output_type -> api.stellar.service.v1.info.proto.InfoSaveReply
	7,  // 7: api.stellar.service.v1.info.proto.Info.ModifyInfo:output_type -> api.stellar.service.v1.info.proto.InfoModifyReply
	8,  // 8: api.stellar.service.v1.info.proto.Info.RemoveInfo:output_type -> api.stellar.service.v1.info.proto.InfoRemoveReply
	9,  // 9: api.stellar.service.v1.info.proto.Info.GetInfo:output_type -> api.stellar.service.v1.info.proto.InfoGetReply
	10, // 10: api.stellar.service.v1.info.proto.Info.PageInfo:output_type -> api.stellar.service.v1.info.proto.InfoPageReply
	11, // 11: api.stellar.service.v1.info.proto.Info.ListInfo:output_type -> api.stellar.service.v1.info.proto.InfoListReply
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_stellar_service_v1_info_proto_info_proto_init() }
func file_stellar_service_v1_info_proto_info_proto_init() {
	if File_stellar_service_v1_info_proto_info_proto != nil {
		return
	}
	file_stellar_service_v1_info_proto_info_save_proto_init()
	file_stellar_service_v1_info_proto_info_modify_proto_init()
	file_stellar_service_v1_info_proto_info_remove_proto_init()
	file_stellar_service_v1_info_proto_info_get_proto_init()
	file_stellar_service_v1_info_proto_info_page_proto_init()
	file_stellar_service_v1_info_proto_info_list_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stellar_service_v1_info_proto_info_proto_rawDesc), len(file_stellar_service_v1_info_proto_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stellar_service_v1_info_proto_info_proto_goTypes,
		DependencyIndexes: file_stellar_service_v1_info_proto_info_proto_depIdxs,
	}.Build()
	File_stellar_service_v1_info_proto_info_proto = out.File
	file_stellar_service_v1_info_proto_info_proto_goTypes = nil
	file_stellar_service_v1_info_proto_info_proto_depIdxs = nil
}
