// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: stellar/service/v1/info/proto/info_remove.proto

package generate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 星体信息删除请求
type InfoRemoveRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Infos         []*InfoRemoveRequest_Info `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRemoveRequest) Reset() {
	*x = InfoRemoveRequest{}
	mi := &file_stellar_service_v1_info_proto_info_remove_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRemoveRequest) ProtoMessage() {}

func (x *InfoRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_service_v1_info_proto_info_remove_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRemoveRequest.ProtoReflect.Descriptor instead.
func (*InfoRemoveRequest) Descriptor() ([]byte, []int) {
	return file_stellar_service_v1_info_proto_info_remove_proto_rawDescGZIP(), []int{0}
}

func (x *InfoRemoveRequest) GetInfos() []*InfoRemoveRequest_Info {
	if x != nil {
		return x.Infos
	}
	return nil
}

// 星体信息删除响应
type InfoRemoveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRemoveReply) Reset() {
	*x = InfoRemoveReply{}
	mi := &file_stellar_service_v1_info_proto_info_remove_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRemoveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRemoveReply) ProtoMessage() {}

func (x *InfoRemoveReply) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_service_v1_info_proto_info_remove_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRemoveReply.ProtoReflect.Descriptor instead.
func (*InfoRemoveReply) Descriptor() ([]byte, []int) {
	return file_stellar_service_v1_info_proto_info_remove_proto_rawDescGZIP(), []int{1}
}

// 星体信息
type InfoRemoveRequest_Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoId        string                 `protobuf:"bytes,1,opt,name=info_id,json=infoId,proto3" json:"info_id,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRemoveRequest_Info) Reset() {
	*x = InfoRemoveRequest_Info{}
	mi := &file_stellar_service_v1_info_proto_info_remove_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRemoveRequest_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRemoveRequest_Info) ProtoMessage() {}

func (x *InfoRemoveRequest_Info) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_service_v1_info_proto_info_remove_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRemoveRequest_Info.ProtoReflect.Descriptor instead.
func (*InfoRemoveRequest_Info) Descriptor() ([]byte, []int) {
	return file_stellar_service_v1_info_proto_info_remove_proto_rawDescGZIP(), []int{0, 0}
}

func (x *InfoRemoveRequest_Info) GetInfoId() string {
	if x != nil {
		return x.InfoId
	}
	return ""
}

func (x *InfoRemoveRequest_Info) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_stellar_service_v1_info_proto_info_remove_proto protoreflect.FileDescriptor

const file_stellar_service_v1_info_proto_info_remove_proto_rawDesc = "" +
	"\n" +
	"/stellar/service/v1/info/proto/info_remove.proto\x12!api.stellar.service.v1.info.proto\"\x9f\x01\n" +
	"\x11InfoRemoveRequest\x12O\n" +
	"\x05infos\x18\x01 \x03(\v29.api.stellar.service.v1.info.proto.InfoRemoveRequest.InfoR\x05infos\x1a9\n" +
	"\x04Info\x12\x17\n" +
	"\ainfo_id\x18\x01 \x01(\tR\x06infoId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"\x11\n" +
	"\x0fInfoRemoveReplyB\"Z api/stellar/service/v1/info;infob\x06proto3"

var (
	file_stellar_service_v1_info_proto_info_remove_proto_rawDescOnce sync.Once
	file_stellar_service_v1_info_proto_info_remove_proto_rawDescData []byte
)

func file_stellar_service_v1_info_proto_info_remove_proto_rawDescGZIP() []byte {
	file_stellar_service_v1_info_proto_info_remove_proto_rawDescOnce.Do(func() {
		file_stellar_service_v1_info_proto_info_remove_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stellar_service_v1_info_proto_info_remove_proto_rawDesc), len(file_stellar_service_v1_info_proto_info_remove_proto_rawDesc)))
	})
	return file_stellar_service_v1_info_proto_info_remove_proto_rawDescData
}

var file_stellar_service_v1_info_proto_info_remove_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_stellar_service_v1_info_proto_info_remove_proto_goTypes = []any{
	(*InfoRemoveRequest)(nil),      // 0: api.stellar.service.v1.info.proto.InfoRemoveRequest
	(*InfoRemoveReply)(nil),        // 1: api.stellar.service.v1.info.proto.InfoRemoveReply
	(*InfoRemoveRequest_Info)(nil), // 2: api.stellar.service.v1.info.proto.InfoRemoveRequest.Info
}
var file_stellar_service_v1_info_proto_info_remove_proto_depIdxs = []int32{
	2, // 0: api.stellar.service.v1.info.proto.InfoRemoveRequest.infos:type_name -> api.stellar.service.v1.info.proto.InfoRemoveRequest.Info
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stellar_service_v1_info_proto_info_remove_proto_init() }
func file_stellar_service_v1_info_proto_info_remove_proto_init() {
	if File_stellar_service_v1_info_proto_info_remove_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stellar_service_v1_info_proto_info_remove_proto_rawDesc), len(file_stellar_service_v1_info_proto_info_remove_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stellar_service_v1_info_proto_info_remove_proto_goTypes,
		DependencyIndexes: file_stellar_service_v1_info_proto_info_remove_proto_depIdxs,
		MessageInfos:      file_stellar_service_v1_info_proto_info_remove_proto_msgTypes,
	}.Build()
	File_stellar_service_v1_info_proto_info_remove_proto = out.File
	file_stellar_service_v1_info_proto_info_remove_proto_goTypes = nil
	file_stellar_service_v1_info_proto_info_remove_proto_depIdxs = nil
}
