// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: stellar/service/v1/info/proto/info_save.proto

package generate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 添加星体信息请求
type InfoSaveRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FileUrl           string                 `protobuf:"bytes,2,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	Period            float64                `protobuf:"fixed64,3,opt,name=period,proto3" json:"period,omitempty"`
	DispersionMeasure float64                `protobuf:"fixed64,4,opt,name=dispersion_measure,json=dispersionMeasure,proto3" json:"dispersion_measure,omitempty"`
	RaDeg             float64                `protobuf:"fixed64,5,opt,name=ra_deg,json=raDeg,proto3" json:"ra_deg,omitempty"`
	DecDeg            float64                `protobuf:"fixed64,6,opt,name=dec_deg,json=decDeg,proto3" json:"dec_deg,omitempty"`
	GalacticLongitude float64                `protobuf:"fixed64,7,opt,name=galactic_longitude,json=galacticLongitude,proto3" json:"galactic_longitude,omitempty"`
	GalacticLatitude  float64                `protobuf:"fixed64,8,opt,name=galactic_latitude,json=galacticLatitude,proto3" json:"galactic_latitude,omitempty"`
	SurveyName        string                 `protobuf:"bytes,9,opt,name=survey_name,json=surveyName,proto3" json:"survey_name,omitempty"`
	CreateBy          int64                  `protobuf:"varint,10,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	Remark            string                 `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InfoSaveRequest) Reset() {
	*x = InfoSaveRequest{}
	mi := &file_stellar_service_v1_info_proto_info_save_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoSaveRequest) ProtoMessage() {}

func (x *InfoSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_service_v1_info_proto_info_save_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoSaveRequest.ProtoReflect.Descriptor instead.
func (*InfoSaveRequest) Descriptor() ([]byte, []int) {
	return file_stellar_service_v1_info_proto_info_save_proto_rawDescGZIP(), []int{0}
}

func (x *InfoSaveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoSaveRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *InfoSaveRequest) GetPeriod() float64 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *InfoSaveRequest) GetDispersionMeasure() float64 {
	if x != nil {
		return x.DispersionMeasure
	}
	return 0
}

func (x *InfoSaveRequest) GetRaDeg() float64 {
	if x != nil {
		return x.RaDeg
	}
	return 0
}

func (x *InfoSaveRequest) GetDecDeg() float64 {
	if x != nil {
		return x.DecDeg
	}
	return 0
}

func (x *InfoSaveRequest) GetGalacticLongitude() float64 {
	if x != nil {
		return x.GalacticLongitude
	}
	return 0
}

func (x *InfoSaveRequest) GetGalacticLatitude() float64 {
	if x != nil {
		return x.GalacticLatitude
	}
	return 0
}

func (x *InfoSaveRequest) GetSurveyName() string {
	if x != nil {
		return x.SurveyName
	}
	return ""
}

func (x *InfoSaveRequest) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *InfoSaveRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 添加星体信息响应
type InfoSaveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoSaveReply) Reset() {
	*x = InfoSaveReply{}
	mi := &file_stellar_service_v1_info_proto_info_save_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoSaveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoSaveReply) ProtoMessage() {}

func (x *InfoSaveReply) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_service_v1_info_proto_info_save_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoSaveReply.ProtoReflect.Descriptor instead.
func (*InfoSaveReply) Descriptor() ([]byte, []int) {
	return file_stellar_service_v1_info_proto_info_save_proto_rawDescGZIP(), []int{1}
}

var File_stellar_service_v1_info_proto_info_save_proto protoreflect.FileDescriptor

const file_stellar_service_v1_info_proto_info_save_proto_rawDesc = "" +
	"\n" +
	"-stellar/service/v1/info/proto/info_save.proto\x12!api.stellar.service.v1.info.proto\"\xe9\x02\n" +
	"\x0fInfoSaveRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bfile_url\x18\x02 \x01(\tR\afileUrl\x12\x16\n" +
	"\x06period\x18\x03 \x01(\x01R\x06period\x12-\n" +
	"\x12dispersion_measure\x18\x04 \x01(\x01R\x11dispersionMeasure\x12\x15\n" +
	"\x06ra_deg\x18\x05 \x01(\x01R\x05raDeg\x12\x17\n" +
	"\adec_deg\x18\x06 \x01(\x01R\x06decDeg\x12-\n" +
	"\x12galactic_longitude\x18\a \x01(\x01R\x11galacticLongitude\x12+\n" +
	"\x11galactic_latitude\x18\b \x01(\x01R\x10galacticLatitude\x12\x1f\n" +
	"\vsurvey_name\x18\t \x01(\tR\n" +
	"surveyName\x12\x1b\n" +
	"\tcreate_by\x18\n" +
	" \x01(\x03R\bcreateBy\x12\x16\n" +
	"\x06remark\x18\v \x01(\tR\x06remark\"\x0f\n" +
	"\rInfoSaveReplyB\"Z api/stellar/service/v1/info;infob\x06proto3"

var (
	file_stellar_service_v1_info_proto_info_save_proto_rawDescOnce sync.Once
	file_stellar_service_v1_info_proto_info_save_proto_rawDescData []byte
)

func file_stellar_service_v1_info_proto_info_save_proto_rawDescGZIP() []byte {
	file_stellar_service_v1_info_proto_info_save_proto_rawDescOnce.Do(func() {
		file_stellar_service_v1_info_proto_info_save_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stellar_service_v1_info_proto_info_save_proto_rawDesc), len(file_stellar_service_v1_info_proto_info_save_proto_rawDesc)))
	})
	return file_stellar_service_v1_info_proto_info_save_proto_rawDescData
}

var file_stellar_service_v1_info_proto_info_save_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stellar_service_v1_info_proto_info_save_proto_goTypes = []any{
	(*InfoSaveRequest)(nil), // 0: api.stellar.service.v1.info.proto.InfoSaveRequest
	(*InfoSaveReply)(nil),   // 1: api.stellar.service.v1.info.proto.InfoSaveReply
}
var file_stellar_service_v1_info_proto_info_save_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stellar_service_v1_info_proto_info_save_proto_init() }
func file_stellar_service_v1_info_proto_info_save_proto_init() {
	if File_stellar_service_v1_info_proto_info_save_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stellar_service_v1_info_proto_info_save_proto_rawDesc), len(file_stellar_service_v1_info_proto_info_save_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stellar_service_v1_info_proto_info_save_proto_goTypes,
		DependencyIndexes: file_stellar_service_v1_info_proto_info_save_proto_depIdxs,
		MessageInfos:      file_stellar_service_v1_info_proto_info_save_proto_msgTypes,
	}.Build()
	File_stellar_service_v1_info_proto_info_save_proto = out.File
	file_stellar_service_v1_info_proto_info_save_proto_goTypes = nil
	file_stellar_service_v1_info_proto_info_save_proto_depIdxs = nil
}
