// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: stellar/interface/v1/status/proto/status_modify.proto

package generate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 星体状态修改请求
type StatusModifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusId      string                 `protobuf:"bytes,1,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	Flag          int32                  `protobuf:"varint,2,opt,name=flag,proto3" json:"flag,omitempty"`
	Check         int32                  `protobuf:"varint,3,opt,name=check,proto3" json:"check,omitempty"`
	UpdateBy      int64                  `protobuf:"varint,4,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Version       int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusModifyRequest) Reset() {
	*x = StatusModifyRequest{}
	mi := &file_stellar_interface_v1_status_proto_status_modify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusModifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusModifyRequest) ProtoMessage() {}

func (x *StatusModifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_interface_v1_status_proto_status_modify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusModifyRequest.ProtoReflect.Descriptor instead.
func (*StatusModifyRequest) Descriptor() ([]byte, []int) {
	return file_stellar_interface_v1_status_proto_status_modify_proto_rawDescGZIP(), []int{0}
}

func (x *StatusModifyRequest) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

func (x *StatusModifyRequest) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *StatusModifyRequest) GetCheck() int32 {
	if x != nil {
		return x.Check
	}
	return 0
}

func (x *StatusModifyRequest) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *StatusModifyRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *StatusModifyRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// 星体状态修改响应
type StatusModifyReply struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Code          int32                   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *StatusModifyReply_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusModifyReply) Reset() {
	*x = StatusModifyReply{}
	mi := &file_stellar_interface_v1_status_proto_status_modify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusModifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusModifyReply) ProtoMessage() {}

func (x *StatusModifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_interface_v1_status_proto_status_modify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusModifyReply.ProtoReflect.Descriptor instead.
func (*StatusModifyReply) Descriptor() ([]byte, []int) {
	return file_stellar_interface_v1_status_proto_status_modify_proto_rawDescGZIP(), []int{1}
}

func (x *StatusModifyReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StatusModifyReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *StatusModifyReply) GetData() *StatusModifyReply_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// 数据
type StatusModifyReply_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusModifyReply_Data) Reset() {
	*x = StatusModifyReply_Data{}
	mi := &file_stellar_interface_v1_status_proto_status_modify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusModifyReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusModifyReply_Data) ProtoMessage() {}

func (x *StatusModifyReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_interface_v1_status_proto_status_modify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusModifyReply_Data.ProtoReflect.Descriptor instead.
func (*StatusModifyReply_Data) Descriptor() ([]byte, []int) {
	return file_stellar_interface_v1_status_proto_status_modify_proto_rawDescGZIP(), []int{1, 0}
}

var File_stellar_interface_v1_status_proto_status_modify_proto protoreflect.FileDescriptor

const file_stellar_interface_v1_status_proto_status_modify_proto_rawDesc = "" +
	"\n" +
	"5stellar/interface/v1/status/proto/status_modify.proto\x12%api.stellar.interface.v1.status.proto\"\xab\x01\n" +
	"\x13StatusModifyRequest\x12\x1b\n" +
	"\tstatus_id\x18\x01 \x01(\tR\bstatusId\x12\x12\n" +
	"\x04flag\x18\x02 \x01(\x05R\x04flag\x12\x14\n" +
	"\x05check\x18\x03 \x01(\x05R\x05check\x12\x1b\n" +
	"\tupdate_by\x18\x04 \x01(\x03R\bupdateBy\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\"\x94\x01\n" +
	"\x11StatusModifyReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12Q\n" +
	"\x04data\x18\x03 \x01(\v2=.api.stellar.interface.v1.status.proto.StatusModifyReply.DataR\x04data\x1a\x06\n" +
	"\x04DataB(Z&api/stellar/interface/v1/status;statusb\x06proto3"

var (
	file_stellar_interface_v1_status_proto_status_modify_proto_rawDescOnce sync.Once
	file_stellar_interface_v1_status_proto_status_modify_proto_rawDescData []byte
)

func file_stellar_interface_v1_status_proto_status_modify_proto_rawDescGZIP() []byte {
	file_stellar_interface_v1_status_proto_status_modify_proto_rawDescOnce.Do(func() {
		file_stellar_interface_v1_status_proto_status_modify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stellar_interface_v1_status_proto_status_modify_proto_rawDesc), len(file_stellar_interface_v1_status_proto_status_modify_proto_rawDesc)))
	})
	return file_stellar_interface_v1_status_proto_status_modify_proto_rawDescData
}

var file_stellar_interface_v1_status_proto_status_modify_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_stellar_interface_v1_status_proto_status_modify_proto_goTypes = []any{
	(*StatusModifyRequest)(nil),    // 0: api.stellar.interface.v1.status.proto.StatusModifyRequest
	(*StatusModifyReply)(nil),      // 1: api.stellar.interface.v1.status.proto.StatusModifyReply
	(*StatusModifyReply_Data)(nil), // 2: api.stellar.interface.v1.status.proto.StatusModifyReply.Data
}
var file_stellar_interface_v1_status_proto_status_modify_proto_depIdxs = []int32{
	2, // 0: api.stellar.interface.v1.status.proto.StatusModifyReply.data:type_name -> api.stellar.interface.v1.status.proto.StatusModifyReply.Data
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stellar_interface_v1_status_proto_status_modify_proto_init() }
func file_stellar_interface_v1_status_proto_status_modify_proto_init() {
	if File_stellar_interface_v1_status_proto_status_modify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stellar_interface_v1_status_proto_status_modify_proto_rawDesc), len(file_stellar_interface_v1_status_proto_status_modify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stellar_interface_v1_status_proto_status_modify_proto_goTypes,
		DependencyIndexes: file_stellar_interface_v1_status_proto_status_modify_proto_depIdxs,
		MessageInfos:      file_stellar_interface_v1_status_proto_status_modify_proto_msgTypes,
	}.Build()
	File_stellar_interface_v1_status_proto_status_modify_proto = out.File
	file_stellar_interface_v1_status_proto_status_modify_proto_goTypes = nil
	file_stellar_interface_v1_status_proto_status_modify_proto_depIdxs = nil
}
