// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: stellar/interface/v1/status/proto/status.proto

package generate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Status_SaveStatus_FullMethodName   = "/api.stellar.interface.v1.status.proto.Status/SaveStatus"
	Status_ModifyStatus_FullMethodName = "/api.stellar.interface.v1.status.proto.Status/ModifyStatus"
	Status_RemoveStatus_FullMethodName = "/api.stellar.interface.v1.status.proto.Status/RemoveStatus"
	Status_GetStatus_FullMethodName    = "/api.stellar.interface.v1.status.proto.Status/GetStatus"
	Status_PageStatus_FullMethodName   = "/api.stellar.interface.v1.status.proto.Status/PageStatus"
)

// StatusClient is the client API for Status service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatusClient interface {
	// 新增星体状态
	SaveStatus(ctx context.Context, in *StatusSaveRequest, opts ...grpc.CallOption) (*StatusSaveReply, error)
	// 修改星体状态
	ModifyStatus(ctx context.Context, in *StatusModifyRequest, opts ...grpc.CallOption) (*StatusModifyReply, error)
	// 删除星体状态
	RemoveStatus(ctx context.Context, in *StatusRemoveRequest, opts ...grpc.CallOption) (*StatusRemoveReply, error)
	// 获取星体状态
	GetStatus(ctx context.Context, in *StatusGetRequest, opts ...grpc.CallOption) (*StatusGetReply, error)
	// 分页查询星体状态列表
	PageStatus(ctx context.Context, in *StatusPageRequest, opts ...grpc.CallOption) (*StatusPageReply, error)
}

type statusClient struct {
	cc grpc.ClientConnInterface
}

func NewStatusClient(cc grpc.ClientConnInterface) StatusClient {
	return &statusClient{cc}
}

func (c *statusClient) SaveStatus(ctx context.Context, in *StatusSaveRequest, opts ...grpc.CallOption) (*StatusSaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusSaveReply)
	err := c.cc.Invoke(ctx, Status_SaveStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statusClient) ModifyStatus(ctx context.Context, in *StatusModifyRequest, opts ...grpc.CallOption) (*StatusModifyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusModifyReply)
	err := c.cc.Invoke(ctx, Status_ModifyStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statusClient) RemoveStatus(ctx context.Context, in *StatusRemoveRequest, opts ...grpc.CallOption) (*StatusRemoveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusRemoveReply)
	err := c.cc.Invoke(ctx, Status_RemoveStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statusClient) GetStatus(ctx context.Context, in *StatusGetRequest, opts ...grpc.CallOption) (*StatusGetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusGetReply)
	err := c.cc.Invoke(ctx, Status_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statusClient) PageStatus(ctx context.Context, in *StatusPageRequest, opts ...grpc.CallOption) (*StatusPageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusPageReply)
	err := c.cc.Invoke(ctx, Status_PageStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatusServer is the server API for Status service.
// All implementations must embed UnimplementedStatusServer
// for forward compatibility.
type StatusServer interface {
	// 新增星体状态
	SaveStatus(context.Context, *StatusSaveRequest) (*StatusSaveReply, error)
	// 修改星体状态
	ModifyStatus(context.Context, *StatusModifyRequest) (*StatusModifyReply, error)
	// 删除星体状态
	RemoveStatus(context.Context, *StatusRemoveRequest) (*StatusRemoveReply, error)
	// 获取星体状态
	GetStatus(context.Context, *StatusGetRequest) (*StatusGetReply, error)
	// 分页查询星体状态列表
	PageStatus(context.Context, *StatusPageRequest) (*StatusPageReply, error)
	mustEmbedUnimplementedStatusServer()
}

// UnimplementedStatusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatusServer struct{}

func (UnimplementedStatusServer) SaveStatus(context.Context, *StatusSaveRequest) (*StatusSaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveStatus not implemented")
}
func (UnimplementedStatusServer) ModifyStatus(context.Context, *StatusModifyRequest) (*StatusModifyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyStatus not implemented")
}
func (UnimplementedStatusServer) RemoveStatus(context.Context, *StatusRemoveRequest) (*StatusRemoveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveStatus not implemented")
}
func (UnimplementedStatusServer) GetStatus(context.Context, *StatusGetRequest) (*StatusGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedStatusServer) PageStatus(context.Context, *StatusPageRequest) (*StatusPageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PageStatus not implemented")
}
func (UnimplementedStatusServer) mustEmbedUnimplementedStatusServer() {}
func (UnimplementedStatusServer) testEmbeddedByValue()                {}

// UnsafeStatusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatusServer will
// result in compilation errors.
type UnsafeStatusServer interface {
	mustEmbedUnimplementedStatusServer()
}

func RegisterStatusServer(s grpc.ServiceRegistrar, srv StatusServer) {
	// If the following call pancis, it indicates UnimplementedStatusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Status_ServiceDesc, srv)
}

func _Status_SaveStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServer).SaveStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Status_SaveStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServer).SaveStatus(ctx, req.(*StatusSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Status_ModifyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusModifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServer).ModifyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Status_ModifyStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServer).ModifyStatus(ctx, req.(*StatusModifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Status_RemoveStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServer).RemoveStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Status_RemoveStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServer).RemoveStatus(ctx, req.(*StatusRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Status_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Status_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServer).GetStatus(ctx, req.(*StatusGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Status_PageStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServer).PageStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Status_PageStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServer).PageStatus(ctx, req.(*StatusPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Status_ServiceDesc is the grpc.ServiceDesc for Status service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Status_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.stellar.interface.v1.status.proto.Status",
	HandlerType: (*StatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveStatus",
			Handler:    _Status_SaveStatus_Handler,
		},
		{
			MethodName: "ModifyStatus",
			Handler:    _Status_ModifyStatus_Handler,
		},
		{
			MethodName: "RemoveStatus",
			Handler:    _Status_RemoveStatus_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Status_GetStatus_Handler,
		},
		{
			MethodName: "PageStatus",
			Handler:    _Status_PageStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stellar/interface/v1/status/proto/status.proto",
}
