// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: stellar/interface/v1/status/proto/status_get.proto

package generate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取星体状态请求
type StatusGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusId      string                 `protobuf:"bytes,1,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusGetRequest) Reset() {
	*x = StatusGetRequest{}
	mi := &file_stellar_interface_v1_status_proto_status_get_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusGetRequest) ProtoMessage() {}

func (x *StatusGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_interface_v1_status_proto_status_get_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusGetRequest.ProtoReflect.Descriptor instead.
func (*StatusGetRequest) Descriptor() ([]byte, []int) {
	return file_stellar_interface_v1_status_proto_status_get_proto_rawDescGZIP(), []int{0}
}

func (x *StatusGetRequest) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

// 获取星体状态响应
type StatusGetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *StatusGetReply_Status `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusGetReply) Reset() {
	*x = StatusGetReply{}
	mi := &file_stellar_interface_v1_status_proto_status_get_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusGetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusGetReply) ProtoMessage() {}

func (x *StatusGetReply) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_interface_v1_status_proto_status_get_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusGetReply.ProtoReflect.Descriptor instead.
func (*StatusGetReply) Descriptor() ([]byte, []int) {
	return file_stellar_interface_v1_status_proto_status_get_proto_rawDescGZIP(), []int{1}
}

func (x *StatusGetReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StatusGetReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *StatusGetReply) GetData() *StatusGetReply_Status {
	if x != nil {
		return x.Data
	}
	return nil
}

// 星体状态
type StatusGetReply_Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusId      string                 `protobuf:"bytes,1,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	FileUrl       string                 `protobuf:"bytes,2,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	Flag          int32                  `protobuf:"varint,4,opt,name=flag,proto3" json:"flag,omitempty"`
	Check         int32                  `protobuf:"varint,5,opt,name=check,proto3" json:"check,omitempty"`
	CreateBy      int64                  `protobuf:"varint,6,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	CreateTime    string                 `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateBy      int64                  `protobuf:"varint,8,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Remark        string                 `protobuf:"bytes,10,opt,name=remark,proto3" json:"remark,omitempty"`
	Version       int32                  `protobuf:"varint,11,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusGetReply_Status) Reset() {
	*x = StatusGetReply_Status{}
	mi := &file_stellar_interface_v1_status_proto_status_get_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusGetReply_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusGetReply_Status) ProtoMessage() {}

func (x *StatusGetReply_Status) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_interface_v1_status_proto_status_get_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusGetReply_Status.ProtoReflect.Descriptor instead.
func (*StatusGetReply_Status) Descriptor() ([]byte, []int) {
	return file_stellar_interface_v1_status_proto_status_get_proto_rawDescGZIP(), []int{1, 0}
}

func (x *StatusGetReply_Status) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

func (x *StatusGetReply_Status) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *StatusGetReply_Status) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *StatusGetReply_Status) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *StatusGetReply_Status) GetCheck() int32 {
	if x != nil {
		return x.Check
	}
	return 0
}

func (x *StatusGetReply_Status) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *StatusGetReply_Status) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *StatusGetReply_Status) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *StatusGetReply_Status) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *StatusGetReply_Status) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *StatusGetReply_Status) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_stellar_interface_v1_status_proto_status_get_proto protoreflect.FileDescriptor

const file_stellar_interface_v1_status_proto_status_get_proto_rawDesc = "" +
	"\n" +
	"2stellar/interface/v1/status/proto/status_get.proto\x12%api.stellar.interface.v1.status.proto\"/\n" +
	"\x10StatusGetRequest\x12\x1b\n" +
	"\tstatus_id\x18\x01 \x01(\tR\bstatusId\"\xb9\x03\n" +
	"\x0eStatusGetReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12P\n" +
	"\x04data\x18\x03 \x01(\v2<.api.stellar.interface.v1.status.proto.StatusGetReply.StatusR\x04data\x1a\xae\x02\n" +
	"\x06Status\x12\x1b\n" +
	"\tstatus_id\x18\x01 \x01(\tR\bstatusId\x12\x19\n" +
	"\bfile_url\x18\x02 \x01(\tR\afileUrl\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12\x12\n" +
	"\x04flag\x18\x04 \x01(\x05R\x04flag\x12\x14\n" +
	"\x05check\x18\x05 \x01(\x05R\x05check\x12\x1b\n" +
	"\tcreate_by\x18\x06 \x01(\x03R\bcreateBy\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\tR\n" +
	"createTime\x12\x1b\n" +
	"\tupdate_by\x18\b \x01(\x03R\bupdateBy\x12\x1f\n" +
	"\vupdate_time\x18\t \x01(\tR\n" +
	"updateTime\x12\x16\n" +
	"\x06remark\x18\n" +
	" \x01(\tR\x06remark\x12\x18\n" +
	"\aversion\x18\v \x01(\x05R\aversionB(Z&api/stellar/interface/v1/status;statusb\x06proto3"

var (
	file_stellar_interface_v1_status_proto_status_get_proto_rawDescOnce sync.Once
	file_stellar_interface_v1_status_proto_status_get_proto_rawDescData []byte
)

func file_stellar_interface_v1_status_proto_status_get_proto_rawDescGZIP() []byte {
	file_stellar_interface_v1_status_proto_status_get_proto_rawDescOnce.Do(func() {
		file_stellar_interface_v1_status_proto_status_get_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stellar_interface_v1_status_proto_status_get_proto_rawDesc), len(file_stellar_interface_v1_status_proto_status_get_proto_rawDesc)))
	})
	return file_stellar_interface_v1_status_proto_status_get_proto_rawDescData
}

var file_stellar_interface_v1_status_proto_status_get_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_stellar_interface_v1_status_proto_status_get_proto_goTypes = []any{
	(*StatusGetRequest)(nil),      // 0: api.stellar.interface.v1.status.proto.StatusGetRequest
	(*StatusGetReply)(nil),        // 1: api.stellar.interface.v1.status.proto.StatusGetReply
	(*StatusGetReply_Status)(nil), // 2: api.stellar.interface.v1.status.proto.StatusGetReply.Status
}
var file_stellar_interface_v1_status_proto_status_get_proto_depIdxs = []int32{
	2, // 0: api.stellar.interface.v1.status.proto.StatusGetReply.data:type_name -> api.stellar.interface.v1.status.proto.StatusGetReply.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stellar_interface_v1_status_proto_status_get_proto_init() }
func file_stellar_interface_v1_status_proto_status_get_proto_init() {
	if File_stellar_interface_v1_status_proto_status_get_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stellar_interface_v1_status_proto_status_get_proto_rawDesc), len(file_stellar_interface_v1_status_proto_status_get_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stellar_interface_v1_status_proto_status_get_proto_goTypes,
		DependencyIndexes: file_stellar_interface_v1_status_proto_status_get_proto_depIdxs,
		MessageInfos:      file_stellar_interface_v1_status_proto_status_get_proto_msgTypes,
	}.Build()
	File_stellar_interface_v1_status_proto_status_get_proto = out.File
	file_stellar_interface_v1_status_proto_status_get_proto_goTypes = nil
	file_stellar_interface_v1_status_proto_status_get_proto_depIdxs = nil
}
