syntax = "proto3";

package api.resource.service.v1.file.proto;

import "resource/service/v1/file/proto/file_save.proto";
import "resource/service/v1/file/proto/file_modify.proto";
import "resource/service/v1/file/proto/file_remove.proto";
import "resource/service/v1/file/proto/file_get.proto";
import "resource/service/v1/file/proto/file_page.proto";

option go_package = "api/resource/service/v1/file;file";

// 文件服务
service File {
  // 新增文件
  rpc SaveFile(FileSaveRequest) returns (FileSaveReply) {}

  // 修改文件
  rpc ModifyFile(FileModifyRequest) returns (FileModifyReply) {}

  // 删除文件
  rpc RemoveFile(FileRemoveRequest) returns (FileRemoveReply) {}

  // 获取文件
  rpc GetFile(FileGetRequest) returns (FileGetReply) {}

  // 分页查询文件列表
  rpc PageFile(FilePageRequest) returns (FilePageReply) {}
}
