// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"lersosa/app/resource/interface/internal/client/file"
	"lersosa/app/resource/interface/internal/client/ossconfig"
	"lersosa/app/resource/interface/internal/controller/web"
	file2 "lersosa/app/resource/interface/internal/executor/file"
	ossconfig2 "lersosa/app/resource/interface/internal/executor/ossconfig"
	"lersosa/app/resource/interface/internal/infrastructure/conf"
	"lersosa/app/resource/interface/internal/server"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, client *conf.Client, logger log.Logger) (*kratos.App, func(), error) {
	ossConfigClient, err := ossconfig.ProvideClient(client)
	if err != nil {
		return nil, nil, err
	}
	ossconfigClient := ossconfig.NewClient(ossConfigClient)
	executor := ossconfig2.NewExecutor(ossconfigClient)
	ossConfigController := web.NewOssConfigController(executor)
	fileClient, err := file.ProvideClient(client)
	if err != nil {
		return nil, nil, err
	}
	client2 := file.NewClient(fileClient)
	fileExecutor := file2.NewExecutor(client2, ossconfigClient)
	fileController := web.NewFileController(fileExecutor)
	grpcServer := server.NewGRPCServer(confServer, ossConfigController, fileController, logger)
	httpServer := server.NewHTTPServer(confServer, ossConfigController, fileController, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
