lersosa-version: ${lersosa.version}
spring-cloud-version: ${spring-cloud.version}
spring-cloud-alibaba-version: ${spring-cloud-alibaba.version}

# Tomcat
server:
  port: ${SERVER-PORT:9120}

# Spring
spring:
  application:
    # 应用名称
    name: @pom.artifactId@
  profiles:
    # 环境配置
    active: @PROFILE-ACTIVE@
