// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// StellarInfoColumns holds the columns for the "stellar_info" table.
	StellarInfoColumns = []*schema.Column{
		{Name: "info_id", Type: field.TypeUUID, Unique: true, Comment: "天体信息 ID"},
		{Name: "tenant_id", Type: field.TypeUUID, Comment: "租户编号"},
		{Name: "create_by", Type: field.TypeInt64, Nullable: true, Comment: "创建者"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_by", Type: field.TypeInt64, Nullable: true, Comment: "更新者"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Size: 500, Comment: "备注"},
		{Name: "version", Type: field.TypeInt32, Comment: "版本", Default: 0},
		{Name: "file_url", Type: field.TypeString, Comment: "文件 URL"},
		{Name: "name", Type: field.TypeString, Size: 100, Comment: "天体名称"},
		{Name: "period", Type: field.TypeFloat64, Nullable: true, Comment: "周期"},
		{Name: "dispersion_measure", Type: field.TypeFloat64, Nullable: true, Comment: "色散量"},
		{Name: "ra_deg", Type: field.TypeFloat64, Comment: "赤经（度）"},
		{Name: "dec_deg", Type: field.TypeFloat64, Comment: "赤纬（度）"},
		{Name: "galactic_longitude", Type: field.TypeFloat64, Nullable: true, Comment: "银经"},
		{Name: "galactic_latitude", Type: field.TypeFloat64, Nullable: true, Comment: "银纬"},
		{Name: "survey_name", Type: field.TypeString, Nullable: true, Size: 50, Comment: "巡天项目名称"},
	}
	// StellarInfoTable holds the schema information for the "stellar_info" table.
	StellarInfoTable = &schema.Table{
		Name:       "stellar_info",
		Comment:    "星体信息表",
		Columns:    StellarInfoColumns,
		PrimaryKey: []*schema.Column{StellarInfoColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_info_name",
				Unique:  false,
				Columns: []*schema.Column{StellarInfoColumns[9]},
			},
			{
				Name:    "idx_info_survey",
				Unique:  false,
				Columns: []*schema.Column{StellarInfoColumns[16]},
			},
			{
				Name:    "idx_info_ra_dec",
				Unique:  false,
				Columns: []*schema.Column{StellarInfoColumns[12], StellarInfoColumns[13]},
			},
			{
				Name:    "idx_info_gal_lon_lat",
				Unique:  false,
				Columns: []*schema.Column{StellarInfoColumns[14], StellarInfoColumns[15]},
			},
			{
				Name:    "idx_info_period",
				Unique:  false,
				Columns: []*schema.Column{StellarInfoColumns[10]},
			},
			{
				Name:    "idx_info_dm",
				Unique:  false,
				Columns: []*schema.Column{StellarInfoColumns[11]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		StellarInfoTable,
	}
)

func init() {
	StellarInfoTable.Annotation = &entsql.Annotation{
		Table: "stellar_info",
	}
}
