// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lersosa/app/stellar/service/internal/infrastructure/info/gatewayimpl/database/ent/info"
	"lersosa/app/stellar/service/internal/infrastructure/info/gatewayimpl/database/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InfoUpdate is the builder for updating Info entities.
type InfoUpdate struct {
	config
	hooks    []Hook
	mutation *InfoMutation
}

// Where appends a list predicates to the InfoUpdate builder.
func (_u *InfoUpdate) Where(ps ...predicate.Info) *InfoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *InfoUpdate) SetCreateBy(v int64) *InfoUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *InfoUpdate) SetNillableCreateBy(v *int64) *InfoUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *InfoUpdate) AddCreateBy(v int64) *InfoUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *InfoUpdate) ClearCreateBy() *InfoUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *InfoUpdate) SetUpdateBy(v int64) *InfoUpdate {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *InfoUpdate) SetNillableUpdateBy(v *int64) *InfoUpdate {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *InfoUpdate) AddUpdateBy(v int64) *InfoUpdate {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *InfoUpdate) ClearUpdateBy() *InfoUpdate {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *InfoUpdate) SetUpdateTime(v time.Time) *InfoUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *InfoUpdate) ClearUpdateTime() *InfoUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *InfoUpdate) SetRemark(v string) *InfoUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *InfoUpdate) SetNillableRemark(v *string) *InfoUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *InfoUpdate) ClearRemark() *InfoUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetVersion sets the "version" field.
func (_u *InfoUpdate) SetVersion(v int32) *InfoUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *InfoUpdate) SetNillableVersion(v *int32) *InfoUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *InfoUpdate) AddVersion(v int32) *InfoUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetFileURL sets the "file_url" field.
func (_u *InfoUpdate) SetFileURL(v string) *InfoUpdate {
	_u.mutation.SetFileURL(v)
	return _u
}

// SetNillableFileURL sets the "file_url" field if the given value is not nil.
func (_u *InfoUpdate) SetNillableFileURL(v *string) *InfoUpdate {
	if v != nil {
		_u.SetFileURL(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *InfoUpdate) SetName(v string) *InfoUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *InfoUpdate) SetNillableName(v *string) *InfoUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPeriod sets the "period" field.
func (_u *InfoUpdate) SetPeriod(v float64) *InfoUpdate {
	_u.mutation.ResetPeriod()
	_u.mutation.SetPeriod(v)
	return _u
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_u *InfoUpdate) SetNillablePeriod(v *float64) *InfoUpdate {
	if v != nil {
		_u.SetPeriod(*v)
	}
	return _u
}

// AddPeriod adds value to the "period" field.
func (_u *InfoUpdate) AddPeriod(v float64) *InfoUpdate {
	_u.mutation.AddPeriod(v)
	return _u
}

// ClearPeriod clears the value of the "period" field.
func (_u *InfoUpdate) ClearPeriod() *InfoUpdate {
	_u.mutation.ClearPeriod()
	return _u
}

// SetDispersionMeasure sets the "dispersion_measure" field.
func (_u *InfoUpdate) SetDispersionMeasure(v float64) *InfoUpdate {
	_u.mutation.ResetDispersionMeasure()
	_u.mutation.SetDispersionMeasure(v)
	return _u
}

// SetNillableDispersionMeasure sets the "dispersion_measure" field if the given value is not nil.
func (_u *InfoUpdate) SetNillableDispersionMeasure(v *float64) *InfoUpdate {
	if v != nil {
		_u.SetDispersionMeasure(*v)
	}
	return _u
}

// AddDispersionMeasure adds value to the "dispersion_measure" field.
func (_u *InfoUpdate) AddDispersionMeasure(v float64) *InfoUpdate {
	_u.mutation.AddDispersionMeasure(v)
	return _u
}

// ClearDispersionMeasure clears the value of the "dispersion_measure" field.
func (_u *InfoUpdate) ClearDispersionMeasure() *InfoUpdate {
	_u.mutation.ClearDispersionMeasure()
	return _u
}

// SetRaDeg sets the "ra_deg" field.
func (_u *InfoUpdate) SetRaDeg(v float64) *InfoUpdate {
	_u.mutation.ResetRaDeg()
	_u.mutation.SetRaDeg(v)
	return _u
}

// SetNillableRaDeg sets the "ra_deg" field if the given value is not nil.
func (_u *InfoUpdate) SetNillableRaDeg(v *float64) *InfoUpdate {
	if v != nil {
		_u.SetRaDeg(*v)
	}
	return _u
}

// AddRaDeg adds value to the "ra_deg" field.
func (_u *InfoUpdate) AddRaDeg(v float64) *InfoUpdate {
	_u.mutation.AddRaDeg(v)
	return _u
}

// SetDecDeg sets the "dec_deg" field.
func (_u *InfoUpdate) SetDecDeg(v float64) *InfoUpdate {
	_u.mutation.ResetDecDeg()
	_u.mutation.SetDecDeg(v)
	return _u
}

// SetNillableDecDeg sets the "dec_deg" field if the given value is not nil.
func (_u *InfoUpdate) SetNillableDecDeg(v *float64) *InfoUpdate {
	if v != nil {
		_u.SetDecDeg(*v)
	}
	return _u
}

// AddDecDeg adds value to the "dec_deg" field.
func (_u *InfoUpdate) AddDecDeg(v float64) *InfoUpdate {
	_u.mutation.AddDecDeg(v)
	return _u
}

// SetGalacticLongitude sets the "galactic_longitude" field.
func (_u *InfoUpdate) SetGalacticLongitude(v float64) *InfoUpdate {
	_u.mutation.ResetGalacticLongitude()
	_u.mutation.SetGalacticLongitude(v)
	return _u
}

// SetNillableGalacticLongitude sets the "galactic_longitude" field if the given value is not nil.
func (_u *InfoUpdate) SetNillableGalacticLongitude(v *float64) *InfoUpdate {
	if v != nil {
		_u.SetGalacticLongitude(*v)
	}
	return _u
}

// AddGalacticLongitude adds value to the "galactic_longitude" field.
func (_u *InfoUpdate) AddGalacticLongitude(v float64) *InfoUpdate {
	_u.mutation.AddGalacticLongitude(v)
	return _u
}

// ClearGalacticLongitude clears the value of the "galactic_longitude" field.
func (_u *InfoUpdate) ClearGalacticLongitude() *InfoUpdate {
	_u.mutation.ClearGalacticLongitude()
	return _u
}

// SetGalacticLatitude sets the "galactic_latitude" field.
func (_u *InfoUpdate) SetGalacticLatitude(v float64) *InfoUpdate {
	_u.mutation.ResetGalacticLatitude()
	_u.mutation.SetGalacticLatitude(v)
	return _u
}

// SetNillableGalacticLatitude sets the "galactic_latitude" field if the given value is not nil.
func (_u *InfoUpdate) SetNillableGalacticLatitude(v *float64) *InfoUpdate {
	if v != nil {
		_u.SetGalacticLatitude(*v)
	}
	return _u
}

// AddGalacticLatitude adds value to the "galactic_latitude" field.
func (_u *InfoUpdate) AddGalacticLatitude(v float64) *InfoUpdate {
	_u.mutation.AddGalacticLatitude(v)
	return _u
}

// ClearGalacticLatitude clears the value of the "galactic_latitude" field.
func (_u *InfoUpdate) ClearGalacticLatitude() *InfoUpdate {
	_u.mutation.ClearGalacticLatitude()
	return _u
}

// SetSurveyName sets the "survey_name" field.
func (_u *InfoUpdate) SetSurveyName(v string) *InfoUpdate {
	_u.mutation.SetSurveyName(v)
	return _u
}

// SetNillableSurveyName sets the "survey_name" field if the given value is not nil.
func (_u *InfoUpdate) SetNillableSurveyName(v *string) *InfoUpdate {
	if v != nil {
		_u.SetSurveyName(*v)
	}
	return _u
}

// ClearSurveyName clears the value of the "survey_name" field.
func (_u *InfoUpdate) ClearSurveyName() *InfoUpdate {
	_u.mutation.ClearSurveyName()
	return _u
}

// Mutation returns the InfoMutation object of the builder.
func (_u *InfoUpdate) Mutation() *InfoMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InfoUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InfoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InfoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InfoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InfoUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok && !_u.mutation.UpdateTimeCleared() {
		v := info.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InfoUpdate) check() error {
	if v, ok := _u.mutation.Remark(); ok {
		if err := info.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "Info.remark": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := info.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Info.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileURL(); ok {
		if err := info.FileURLValidator(v); err != nil {
			return &ValidationError{Name: "file_url", err: fmt.Errorf(`ent: validator failed for field "Info.file_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := info.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Info.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SurveyName(); ok {
		if err := info.SurveyNameValidator(v); err != nil {
			return &ValidationError{Name: "survey_name", err: fmt.Errorf(`ent: validator failed for field "Info.survey_name": %w`, err)}
		}
	}
	return nil
}

func (_u *InfoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(info.Table, info.Columns, sqlgraph.NewFieldSpec(info.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(info.FieldCreateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(info.FieldCreateBy, field.TypeInt64, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(info.FieldCreateBy, field.TypeInt64)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(info.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(info.FieldUpdateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(info.FieldUpdateBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(info.FieldUpdateBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(info.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(info.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(info.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(info.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(info.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(info.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.FileURL(); ok {
		_spec.SetField(info.FieldFileURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(info.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Period(); ok {
		_spec.SetField(info.FieldPeriod, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPeriod(); ok {
		_spec.AddField(info.FieldPeriod, field.TypeFloat64, value)
	}
	if _u.mutation.PeriodCleared() {
		_spec.ClearField(info.FieldPeriod, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DispersionMeasure(); ok {
		_spec.SetField(info.FieldDispersionMeasure, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDispersionMeasure(); ok {
		_spec.AddField(info.FieldDispersionMeasure, field.TypeFloat64, value)
	}
	if _u.mutation.DispersionMeasureCleared() {
		_spec.ClearField(info.FieldDispersionMeasure, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RaDeg(); ok {
		_spec.SetField(info.FieldRaDeg, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRaDeg(); ok {
		_spec.AddField(info.FieldRaDeg, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DecDeg(); ok {
		_spec.SetField(info.FieldDecDeg, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDecDeg(); ok {
		_spec.AddField(info.FieldDecDeg, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GalacticLongitude(); ok {
		_spec.SetField(info.FieldGalacticLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGalacticLongitude(); ok {
		_spec.AddField(info.FieldGalacticLongitude, field.TypeFloat64, value)
	}
	if _u.mutation.GalacticLongitudeCleared() {
		_spec.ClearField(info.FieldGalacticLongitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.GalacticLatitude(); ok {
		_spec.SetField(info.FieldGalacticLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGalacticLatitude(); ok {
		_spec.AddField(info.FieldGalacticLatitude, field.TypeFloat64, value)
	}
	if _u.mutation.GalacticLatitudeCleared() {
		_spec.ClearField(info.FieldGalacticLatitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SurveyName(); ok {
		_spec.SetField(info.FieldSurveyName, field.TypeString, value)
	}
	if _u.mutation.SurveyNameCleared() {
		_spec.ClearField(info.FieldSurveyName, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{info.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InfoUpdateOne is the builder for updating a single Info entity.
type InfoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InfoMutation
}

// SetCreateBy sets the "create_by" field.
func (_u *InfoUpdateOne) SetCreateBy(v int64) *InfoUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *InfoUpdateOne) SetNillableCreateBy(v *int64) *InfoUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *InfoUpdateOne) AddCreateBy(v int64) *InfoUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *InfoUpdateOne) ClearCreateBy() *InfoUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *InfoUpdateOne) SetUpdateBy(v int64) *InfoUpdateOne {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *InfoUpdateOne) SetNillableUpdateBy(v *int64) *InfoUpdateOne {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *InfoUpdateOne) AddUpdateBy(v int64) *InfoUpdateOne {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *InfoUpdateOne) ClearUpdateBy() *InfoUpdateOne {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *InfoUpdateOne) SetUpdateTime(v time.Time) *InfoUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *InfoUpdateOne) ClearUpdateTime() *InfoUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *InfoUpdateOne) SetRemark(v string) *InfoUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *InfoUpdateOne) SetNillableRemark(v *string) *InfoUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *InfoUpdateOne) ClearRemark() *InfoUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetVersion sets the "version" field.
func (_u *InfoUpdateOne) SetVersion(v int32) *InfoUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *InfoUpdateOne) SetNillableVersion(v *int32) *InfoUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *InfoUpdateOne) AddVersion(v int32) *InfoUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetFileURL sets the "file_url" field.
func (_u *InfoUpdateOne) SetFileURL(v string) *InfoUpdateOne {
	_u.mutation.SetFileURL(v)
	return _u
}

// SetNillableFileURL sets the "file_url" field if the given value is not nil.
func (_u *InfoUpdateOne) SetNillableFileURL(v *string) *InfoUpdateOne {
	if v != nil {
		_u.SetFileURL(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *InfoUpdateOne) SetName(v string) *InfoUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *InfoUpdateOne) SetNillableName(v *string) *InfoUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPeriod sets the "period" field.
func (_u *InfoUpdateOne) SetPeriod(v float64) *InfoUpdateOne {
	_u.mutation.ResetPeriod()
	_u.mutation.SetPeriod(v)
	return _u
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_u *InfoUpdateOne) SetNillablePeriod(v *float64) *InfoUpdateOne {
	if v != nil {
		_u.SetPeriod(*v)
	}
	return _u
}

// AddPeriod adds value to the "period" field.
func (_u *InfoUpdateOne) AddPeriod(v float64) *InfoUpdateOne {
	_u.mutation.AddPeriod(v)
	return _u
}

// ClearPeriod clears the value of the "period" field.
func (_u *InfoUpdateOne) ClearPeriod() *InfoUpdateOne {
	_u.mutation.ClearPeriod()
	return _u
}

// SetDispersionMeasure sets the "dispersion_measure" field.
func (_u *InfoUpdateOne) SetDispersionMeasure(v float64) *InfoUpdateOne {
	_u.mutation.ResetDispersionMeasure()
	_u.mutation.SetDispersionMeasure(v)
	return _u
}

// SetNillableDispersionMeasure sets the "dispersion_measure" field if the given value is not nil.
func (_u *InfoUpdateOne) SetNillableDispersionMeasure(v *float64) *InfoUpdateOne {
	if v != nil {
		_u.SetDispersionMeasure(*v)
	}
	return _u
}

// AddDispersionMeasure adds value to the "dispersion_measure" field.
func (_u *InfoUpdateOne) AddDispersionMeasure(v float64) *InfoUpdateOne {
	_u.mutation.AddDispersionMeasure(v)
	return _u
}

// ClearDispersionMeasure clears the value of the "dispersion_measure" field.
func (_u *InfoUpdateOne) ClearDispersionMeasure() *InfoUpdateOne {
	_u.mutation.ClearDispersionMeasure()
	return _u
}

// SetRaDeg sets the "ra_deg" field.
func (_u *InfoUpdateOne) SetRaDeg(v float64) *InfoUpdateOne {
	_u.mutation.ResetRaDeg()
	_u.mutation.SetRaDeg(v)
	return _u
}

// SetNillableRaDeg sets the "ra_deg" field if the given value is not nil.
func (_u *InfoUpdateOne) SetNillableRaDeg(v *float64) *InfoUpdateOne {
	if v != nil {
		_u.SetRaDeg(*v)
	}
	return _u
}

// AddRaDeg adds value to the "ra_deg" field.
func (_u *InfoUpdateOne) AddRaDeg(v float64) *InfoUpdateOne {
	_u.mutation.AddRaDeg(v)
	return _u
}

// SetDecDeg sets the "dec_deg" field.
func (_u *InfoUpdateOne) SetDecDeg(v float64) *InfoUpdateOne {
	_u.mutation.ResetDecDeg()
	_u.mutation.SetDecDeg(v)
	return _u
}

// SetNillableDecDeg sets the "dec_deg" field if the given value is not nil.
func (_u *InfoUpdateOne) SetNillableDecDeg(v *float64) *InfoUpdateOne {
	if v != nil {
		_u.SetDecDeg(*v)
	}
	return _u
}

// AddDecDeg adds value to the "dec_deg" field.
func (_u *InfoUpdateOne) AddDecDeg(v float64) *InfoUpdateOne {
	_u.mutation.AddDecDeg(v)
	return _u
}

// SetGalacticLongitude sets the "galactic_longitude" field.
func (_u *InfoUpdateOne) SetGalacticLongitude(v float64) *InfoUpdateOne {
	_u.mutation.ResetGalacticLongitude()
	_u.mutation.SetGalacticLongitude(v)
	return _u
}

// SetNillableGalacticLongitude sets the "galactic_longitude" field if the given value is not nil.
func (_u *InfoUpdateOne) SetNillableGalacticLongitude(v *float64) *InfoUpdateOne {
	if v != nil {
		_u.SetGalacticLongitude(*v)
	}
	return _u
}

// AddGalacticLongitude adds value to the "galactic_longitude" field.
func (_u *InfoUpdateOne) AddGalacticLongitude(v float64) *InfoUpdateOne {
	_u.mutation.AddGalacticLongitude(v)
	return _u
}

// ClearGalacticLongitude clears the value of the "galactic_longitude" field.
func (_u *InfoUpdateOne) ClearGalacticLongitude() *InfoUpdateOne {
	_u.mutation.ClearGalacticLongitude()
	return _u
}

// SetGalacticLatitude sets the "galactic_latitude" field.
func (_u *InfoUpdateOne) SetGalacticLatitude(v float64) *InfoUpdateOne {
	_u.mutation.ResetGalacticLatitude()
	_u.mutation.SetGalacticLatitude(v)
	return _u
}

// SetNillableGalacticLatitude sets the "galactic_latitude" field if the given value is not nil.
func (_u *InfoUpdateOne) SetNillableGalacticLatitude(v *float64) *InfoUpdateOne {
	if v != nil {
		_u.SetGalacticLatitude(*v)
	}
	return _u
}

// AddGalacticLatitude adds value to the "galactic_latitude" field.
func (_u *InfoUpdateOne) AddGalacticLatitude(v float64) *InfoUpdateOne {
	_u.mutation.AddGalacticLatitude(v)
	return _u
}

// ClearGalacticLatitude clears the value of the "galactic_latitude" field.
func (_u *InfoUpdateOne) ClearGalacticLatitude() *InfoUpdateOne {
	_u.mutation.ClearGalacticLatitude()
	return _u
}

// SetSurveyName sets the "survey_name" field.
func (_u *InfoUpdateOne) SetSurveyName(v string) *InfoUpdateOne {
	_u.mutation.SetSurveyName(v)
	return _u
}

// SetNillableSurveyName sets the "survey_name" field if the given value is not nil.
func (_u *InfoUpdateOne) SetNillableSurveyName(v *string) *InfoUpdateOne {
	if v != nil {
		_u.SetSurveyName(*v)
	}
	return _u
}

// ClearSurveyName clears the value of the "survey_name" field.
func (_u *InfoUpdateOne) ClearSurveyName() *InfoUpdateOne {
	_u.mutation.ClearSurveyName()
	return _u
}

// Mutation returns the InfoMutation object of the builder.
func (_u *InfoUpdateOne) Mutation() *InfoMutation {
	return _u.mutation
}

// Where appends a list predicates to the InfoUpdate builder.
func (_u *InfoUpdateOne) Where(ps ...predicate.Info) *InfoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InfoUpdateOne) Select(field string, fields ...string) *InfoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Info entity.
func (_u *InfoUpdateOne) Save(ctx context.Context) (*Info, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InfoUpdateOne) SaveX(ctx context.Context) *Info {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InfoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InfoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InfoUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok && !_u.mutation.UpdateTimeCleared() {
		v := info.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InfoUpdateOne) check() error {
	if v, ok := _u.mutation.Remark(); ok {
		if err := info.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "Info.remark": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := info.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Info.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileURL(); ok {
		if err := info.FileURLValidator(v); err != nil {
			return &ValidationError{Name: "file_url", err: fmt.Errorf(`ent: validator failed for field "Info.file_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := info.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Info.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SurveyName(); ok {
		if err := info.SurveyNameValidator(v); err != nil {
			return &ValidationError{Name: "survey_name", err: fmt.Errorf(`ent: validator failed for field "Info.survey_name": %w`, err)}
		}
	}
	return nil
}

func (_u *InfoUpdateOne) sqlSave(ctx context.Context) (_node *Info, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(info.Table, info.Columns, sqlgraph.NewFieldSpec(info.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Info.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, info.FieldID)
		for _, f := range fields {
			if !info.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != info.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(info.FieldCreateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(info.FieldCreateBy, field.TypeInt64, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(info.FieldCreateBy, field.TypeInt64)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(info.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(info.FieldUpdateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(info.FieldUpdateBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(info.FieldUpdateBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(info.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(info.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(info.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(info.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(info.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(info.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.FileURL(); ok {
		_spec.SetField(info.FieldFileURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(info.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Period(); ok {
		_spec.SetField(info.FieldPeriod, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPeriod(); ok {
		_spec.AddField(info.FieldPeriod, field.TypeFloat64, value)
	}
	if _u.mutation.PeriodCleared() {
		_spec.ClearField(info.FieldPeriod, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DispersionMeasure(); ok {
		_spec.SetField(info.FieldDispersionMeasure, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDispersionMeasure(); ok {
		_spec.AddField(info.FieldDispersionMeasure, field.TypeFloat64, value)
	}
	if _u.mutation.DispersionMeasureCleared() {
		_spec.ClearField(info.FieldDispersionMeasure, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RaDeg(); ok {
		_spec.SetField(info.FieldRaDeg, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRaDeg(); ok {
		_spec.AddField(info.FieldRaDeg, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DecDeg(); ok {
		_spec.SetField(info.FieldDecDeg, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDecDeg(); ok {
		_spec.AddField(info.FieldDecDeg, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GalacticLongitude(); ok {
		_spec.SetField(info.FieldGalacticLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGalacticLongitude(); ok {
		_spec.AddField(info.FieldGalacticLongitude, field.TypeFloat64, value)
	}
	if _u.mutation.GalacticLongitudeCleared() {
		_spec.ClearField(info.FieldGalacticLongitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.GalacticLatitude(); ok {
		_spec.SetField(info.FieldGalacticLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGalacticLatitude(); ok {
		_spec.AddField(info.FieldGalacticLatitude, field.TypeFloat64, value)
	}
	if _u.mutation.GalacticLatitudeCleared() {
		_spec.ClearField(info.FieldGalacticLatitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SurveyName(); ok {
		_spec.SetField(info.FieldSurveyName, field.TypeString, value)
	}
	if _u.mutation.SurveyNameCleared() {
		_spec.ClearField(info.FieldSurveyName, field.TypeString)
	}
	_node = &Info{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{info.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
