spring:
  application:
    name: @pom.artifactId@
  profiles:
    active: @PROFILE-ACTIVE@
  main:
    lazy-initialization: true

server:
  port: ${SERVER_PORT:6000}

grpc:
  server:
    port: ${SERVER_GRPC_PORT:6001}
