# Tomcat
server:
  port: 8080
  servlet:
    context-path: /

# Spring
spring:
  application:
    # 应用名称
    name: @pom.artifactId@
  profiles:
    # 环境配置
    active: @PROFILE-ACTIVE@
  main:
    lazy-initialization: true
