// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SysFileColumns holds the columns for the "sys_file" table.
	SysFileColumns = []*schema.Column{
		{Name: "oss_id", Type: field.TypeUUID, Unique: true, Comment: "对象存储主键"},
		{Name: "tenant_id", Type: field.TypeUUID, Comment: "租户编号"},
		{Name: "create_by", Type: field.TypeInt64, Nullable: true, Comment: "创建者"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_by", Type: field.TypeInt64, Nullable: true, Comment: "更新者"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Size: 500, Comment: "备注"},
		{Name: "version", Type: field.TypeInt32, Comment: "版本", Default: 0},
		{Name: "file_name", Type: field.TypeString, Size: 255, Comment: "文件名", Default: ""},
		{Name: "original_name", Type: field.TypeString, Size: 255, Comment: "原名", Default: ""},
		{Name: "file_suffix", Type: field.TypeString, Size: 10, Comment: "文件后缀名", Default: ""},
		{Name: "url", Type: field.TypeString, Size: 500, Comment: "URL 地址", Default: ""},
		{Name: "ext1", Type: field.TypeString, Nullable: true, Size: 500, Comment: "扩展字段", Default: ""},
		{Name: "create_dept", Type: field.TypeInt64, Nullable: true, Comment: "创建部门"},
		{Name: "service", Type: field.TypeString, Size: 20, Comment: "服务商", Default: "minio"},
	}
	// SysFileTable holds the schema information for the "sys_file" table.
	SysFileTable = &schema.Table{
		Name:       "sys_file",
		Comment:    "系统文件表",
		Columns:    SysFileColumns,
		PrimaryKey: []*schema.Column{SysFileColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SysFileTable,
	}
)

func init() {
	SysFileTable.Annotation = &entsql.Annotation{
		Table: "sys_file",
	}
}
