// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: stellar/interface/v1/info/proto/info_get.proto

package generate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取星体信息请求
type InfoGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoId        string                 `protobuf:"bytes,1,opt,name=info_id,json=infoId,proto3" json:"info_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoGetRequest) Reset() {
	*x = InfoGetRequest{}
	mi := &file_stellar_interface_v1_info_proto_info_get_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoGetRequest) ProtoMessage() {}

func (x *InfoGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_interface_v1_info_proto_info_get_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoGetRequest.ProtoReflect.Descriptor instead.
func (*InfoGetRequest) Descriptor() ([]byte, []int) {
	return file_stellar_interface_v1_info_proto_info_get_proto_rawDescGZIP(), []int{0}
}

func (x *InfoGetRequest) GetInfoId() string {
	if x != nil {
		return x.InfoId
	}
	return ""
}

// 获取星体信息响应
type InfoGetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *InfoGetReply_Info     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoGetReply) Reset() {
	*x = InfoGetReply{}
	mi := &file_stellar_interface_v1_info_proto_info_get_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoGetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoGetReply) ProtoMessage() {}

func (x *InfoGetReply) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_interface_v1_info_proto_info_get_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoGetReply.ProtoReflect.Descriptor instead.
func (*InfoGetReply) Descriptor() ([]byte, []int) {
	return file_stellar_interface_v1_info_proto_info_get_proto_rawDescGZIP(), []int{1}
}

func (x *InfoGetReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InfoGetReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *InfoGetReply) GetData() *InfoGetReply_Info {
	if x != nil {
		return x.Data
	}
	return nil
}

// 星体信息
type InfoGetReply_Info struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InfoId            string                 `protobuf:"bytes,1,opt,name=info_id,json=infoId,proto3" json:"info_id,omitempty"`
	FileUrl           string                 `protobuf:"bytes,2,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Period            float64                `protobuf:"fixed64,4,opt,name=period,proto3" json:"period,omitempty"`
	DispersionMeasure float64                `protobuf:"fixed64,5,opt,name=dispersion_measure,json=dispersionMeasure,proto3" json:"dispersion_measure,omitempty"`
	RaDeg             float64                `protobuf:"fixed64,6,opt,name=ra_deg,json=raDeg,proto3" json:"ra_deg,omitempty"`
	DecDeg            float64                `protobuf:"fixed64,7,opt,name=dec_deg,json=decDeg,proto3" json:"dec_deg,omitempty"`
	GalacticLongitude float64                `protobuf:"fixed64,8,opt,name=galactic_longitude,json=galacticLongitude,proto3" json:"galactic_longitude,omitempty"`
	GalacticLatitude  float64                `protobuf:"fixed64,9,opt,name=galactic_latitude,json=galacticLatitude,proto3" json:"galactic_latitude,omitempty"`
	SurveyName        string                 `protobuf:"bytes,10,opt,name=survey_name,json=surveyName,proto3" json:"survey_name,omitempty"`
	CreateBy          int64                  `protobuf:"varint,11,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	CreateTime        string                 `protobuf:"bytes,12,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateBy          int64                  `protobuf:"varint,13,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	UpdateTime        string                 `protobuf:"bytes,14,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Remark            string                 `protobuf:"bytes,15,opt,name=remark,proto3" json:"remark,omitempty"`
	Version           int32                  `protobuf:"varint,16,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InfoGetReply_Info) Reset() {
	*x = InfoGetReply_Info{}
	mi := &file_stellar_interface_v1_info_proto_info_get_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoGetReply_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoGetReply_Info) ProtoMessage() {}

func (x *InfoGetReply_Info) ProtoReflect() protoreflect.Message {
	mi := &file_stellar_interface_v1_info_proto_info_get_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoGetReply_Info.ProtoReflect.Descriptor instead.
func (*InfoGetReply_Info) Descriptor() ([]byte, []int) {
	return file_stellar_interface_v1_info_proto_info_get_proto_rawDescGZIP(), []int{1, 0}
}

func (x *InfoGetReply_Info) GetInfoId() string {
	if x != nil {
		return x.InfoId
	}
	return ""
}

func (x *InfoGetReply_Info) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *InfoGetReply_Info) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoGetReply_Info) GetPeriod() float64 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *InfoGetReply_Info) GetDispersionMeasure() float64 {
	if x != nil {
		return x.DispersionMeasure
	}
	return 0
}

func (x *InfoGetReply_Info) GetRaDeg() float64 {
	if x != nil {
		return x.RaDeg
	}
	return 0
}

func (x *InfoGetReply_Info) GetDecDeg() float64 {
	if x != nil {
		return x.DecDeg
	}
	return 0
}

func (x *InfoGetReply_Info) GetGalacticLongitude() float64 {
	if x != nil {
		return x.GalacticLongitude
	}
	return 0
}

func (x *InfoGetReply_Info) GetGalacticLatitude() float64 {
	if x != nil {
		return x.GalacticLatitude
	}
	return 0
}

func (x *InfoGetReply_Info) GetSurveyName() string {
	if x != nil {
		return x.SurveyName
	}
	return ""
}

func (x *InfoGetReply_Info) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *InfoGetReply_Info) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *InfoGetReply_Info) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *InfoGetReply_Info) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *InfoGetReply_Info) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *InfoGetReply_Info) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_stellar_interface_v1_info_proto_info_get_proto protoreflect.FileDescriptor

const file_stellar_interface_v1_info_proto_info_get_proto_rawDesc = "" +
	"\n" +
	".stellar/interface/v1/info/proto/info_get.proto\x12#api.stellar.interface.v1.info.proto\")\n" +
	"\x0eInfoGetRequest\x12\x17\n" +
	"\ainfo_id\x18\x01 \x01(\tR\x06infoId\"\xf3\x04\n" +
	"\fInfoGetReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12J\n" +
	"\x04data\x18\x03 \x01(\v26.api.stellar.interface.v1.info.proto.InfoGetReply.InfoR\x04data\x1a\xf0\x03\n" +
	"\x04Info\x12\x17\n" +
	"\ainfo_id\x18\x01 \x01(\tR\x06infoId\x12\x19\n" +
	"\bfile_url\x18\x02 \x01(\tR\afileUrl\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06period\x18\x04 \x01(\x01R\x06period\x12-\n" +
	"\x12dispersion_measure\x18\x05 \x01(\x01R\x11dispersionMeasure\x12\x15\n" +
	"\x06ra_deg\x18\x06 \x01(\x01R\x05raDeg\x12\x17\n" +
	"\adec_deg\x18\a \x01(\x01R\x06decDeg\x12-\n" +
	"\x12galactic_longitude\x18\b \x01(\x01R\x11galacticLongitude\x12+\n" +
	"\x11galactic_latitude\x18\t \x01(\x01R\x10galacticLatitude\x12\x1f\n" +
	"\vsurvey_name\x18\n" +
	" \x01(\tR\n" +
	"surveyName\x12\x1b\n" +
	"\tcreate_by\x18\v \x01(\x03R\bcreateBy\x12\x1f\n" +
	"\vcreate_time\x18\f \x01(\tR\n" +
	"createTime\x12\x1b\n" +
	"\tupdate_by\x18\r \x01(\x03R\bupdateBy\x12\x1f\n" +
	"\vupdate_time\x18\x0e \x01(\tR\n" +
	"updateTime\x12\x16\n" +
	"\x06remark\x18\x0f \x01(\tR\x06remark\x12\x18\n" +
	"\aversion\x18\x10 \x01(\x05R\aversionB$Z\"api/stellar/interface/v1/info;infob\x06proto3"

var (
	file_stellar_interface_v1_info_proto_info_get_proto_rawDescOnce sync.Once
	file_stellar_interface_v1_info_proto_info_get_proto_rawDescData []byte
)

func file_stellar_interface_v1_info_proto_info_get_proto_rawDescGZIP() []byte {
	file_stellar_interface_v1_info_proto_info_get_proto_rawDescOnce.Do(func() {
		file_stellar_interface_v1_info_proto_info_get_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stellar_interface_v1_info_proto_info_get_proto_rawDesc), len(file_stellar_interface_v1_info_proto_info_get_proto_rawDesc)))
	})
	return file_stellar_interface_v1_info_proto_info_get_proto_rawDescData
}

var file_stellar_interface_v1_info_proto_info_get_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_stellar_interface_v1_info_proto_info_get_proto_goTypes = []any{
	(*InfoGetRequest)(nil),    // 0: api.stellar.interface.v1.info.proto.InfoGetRequest
	(*InfoGetReply)(nil),      // 1: api.stellar.interface.v1.info.proto.InfoGetReply
	(*InfoGetReply_Info)(nil), // 2: api.stellar.interface.v1.info.proto.InfoGetReply.Info
}
var file_stellar_interface_v1_info_proto_info_get_proto_depIdxs = []int32{
	2, // 0: api.stellar.interface.v1.info.proto.InfoGetReply.data:type_name -> api.stellar.interface.v1.info.proto.InfoGetReply.Info
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stellar_interface_v1_info_proto_info_get_proto_init() }
func file_stellar_interface_v1_info_proto_info_get_proto_init() {
	if File_stellar_interface_v1_info_proto_info_get_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stellar_interface_v1_info_proto_info_get_proto_rawDesc), len(file_stellar_interface_v1_info_proto_info_get_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stellar_interface_v1_info_proto_info_get_proto_goTypes,
		DependencyIndexes: file_stellar_interface_v1_info_proto_info_get_proto_depIdxs,
		MessageInfos:      file_stellar_interface_v1_info_proto_info_get_proto_msgTypes,
	}.Build()
	File_stellar_interface_v1_info_proto_info_get_proto = out.File
	file_stellar_interface_v1_info_proto_info_get_proto_goTypes = nil
	file_stellar_interface_v1_info_proto_info_get_proto_depIdxs = nil
}
