// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: interface/internal/infrastructure/conf/proto/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Client        *Client                `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_interface_internal_infrastructure_conf_proto_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_interface_internal_infrastructure_conf_proto_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_interface_internal_infrastructure_conf_proto_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_interface_internal_infrastructure_conf_proto_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_interface_internal_infrastructure_conf_proto_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_interface_internal_infrastructure_conf_proto_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grpc          *Client_GRPC           `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_interface_internal_infrastructure_conf_proto_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_interface_internal_infrastructure_conf_proto_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_interface_internal_infrastructure_conf_proto_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Client) GetGrpc() *Client_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	TlsEnable     bool                   `protobuf:"varint,4,opt,name=tls_enable,json=tlsEnable,proto3" json:"tls_enable,omitempty"`
	CertFile      string                 `protobuf:"bytes,5,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile       string                 `protobuf:"bytes,6,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	CaFile        string                 `protobuf:"bytes,7,opt,name=ca_file,json=caFile,proto3" json:"ca_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_interface_internal_infrastructure_conf_proto_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_interface_internal_infrastructure_conf_proto_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_interface_internal_infrastructure_conf_proto_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Server_HTTP) GetTlsEnable() bool {
	if x != nil {
		return x.TlsEnable
	}
	return false
}

func (x *Server_HTTP) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *Server_HTTP) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *Server_HTTP) GetCaFile() string {
	if x != nil {
		return x.CaFile
	}
	return ""
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	TlsEnable     bool                   `protobuf:"varint,4,opt,name=tls_enable,json=tlsEnable,proto3" json:"tls_enable,omitempty"`
	CertFile      string                 `protobuf:"bytes,5,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile       string                 `protobuf:"bytes,6,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	CaFile        string                 `protobuf:"bytes,7,opt,name=ca_file,json=caFile,proto3" json:"ca_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_interface_internal_infrastructure_conf_proto_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_interface_internal_infrastructure_conf_proto_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_interface_internal_infrastructure_conf_proto_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Server_GRPC) GetTlsEnable() bool {
	if x != nil {
		return x.TlsEnable
	}
	return false
}

func (x *Server_GRPC) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *Server_GRPC) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *Server_GRPC) GetCaFile() string {
	if x != nil {
		return x.CaFile
	}
	return ""
}

type Client_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          []string               `protobuf:"bytes,2,rep,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	TlsEnable     bool                   `protobuf:"varint,4,opt,name=tls_enable,json=tlsEnable,proto3" json:"tls_enable,omitempty"`
	CertFile      string                 `protobuf:"bytes,5,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile       string                 `protobuf:"bytes,6,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	CaFile        string                 `protobuf:"bytes,7,opt,name=ca_file,json=caFile,proto3" json:"ca_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client_GRPC) Reset() {
	*x = Client_GRPC{}
	mi := &file_interface_internal_infrastructure_conf_proto_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_GRPC) ProtoMessage() {}

func (x *Client_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_interface_internal_infrastructure_conf_proto_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_GRPC.ProtoReflect.Descriptor instead.
func (*Client_GRPC) Descriptor() ([]byte, []int) {
	return file_interface_internal_infrastructure_conf_proto_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Client_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Client_GRPC) GetAddr() []string {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *Client_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Client_GRPC) GetTlsEnable() bool {
	if x != nil {
		return x.TlsEnable
	}
	return false
}

func (x *Client_GRPC) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *Client_GRPC) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *Client_GRPC) GetCaFile() string {
	if x != nil {
		return x.CaFile
	}
	return ""
}

var File_interface_internal_infrastructure_conf_proto_conf_proto protoreflect.FileDescriptor

const file_interface_internal_infrastructure_conf_proto_conf_proto_rawDesc = "" +
	"\n" +
	"7interface/internal/infrastructure/conf/proto/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"c\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12*\n" +
	"\x06client\x18\x02 \x01(\v2\x12.kratos.api.ClientR\x06client\"\x9a\x04\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1a\xd9\x01\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1d\n" +
	"\n" +
	"tls_enable\x18\x04 \x01(\bR\ttlsEnable\x12\x1b\n" +
	"\tcert_file\x18\x05 \x01(\tR\bcertFile\x12\x19\n" +
	"\bkey_file\x18\x06 \x01(\tR\akeyFile\x12\x17\n" +
	"\aca_file\x18\a \x01(\tR\x06caFile\x1a\xd9\x01\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1d\n" +
	"\n" +
	"tls_enable\x18\x04 \x01(\bR\ttlsEnable\x12\x1b\n" +
	"\tcert_file\x18\x05 \x01(\tR\bcertFile\x12\x19\n" +
	"\bkey_file\x18\x06 \x01(\tR\akeyFile\x12\x17\n" +
	"\aca_file\x18\a \x01(\tR\x06caFile\"\x91\x02\n" +
	"\x06Client\x12+\n" +
	"\x04grpc\x18\x01 \x01(\v2\x17.kratos.api.Client.GRPCR\x04grpc\x1a\xd9\x01\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x03(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1d\n" +
	"\n" +
	"tls_enable\x18\x04 \x01(\bR\ttlsEnable\x12\x1b\n" +
	"\tcert_file\x18\x05 \x01(\tR\bcertFile\x12\x19\n" +
	"\bkey_file\x18\x06 \x01(\tR\akeyFile\x12\x17\n" +
	"\aca_file\x18\a \x01(\tR\x06caFileBCZAlersosa/app/resource/interface/internal//infrastructure/conf;confb\x06proto3"

var (
	file_interface_internal_infrastructure_conf_proto_conf_proto_rawDescOnce sync.Once
	file_interface_internal_infrastructure_conf_proto_conf_proto_rawDescData []byte
)

func file_interface_internal_infrastructure_conf_proto_conf_proto_rawDescGZIP() []byte {
	file_interface_internal_infrastructure_conf_proto_conf_proto_rawDescOnce.Do(func() {
		file_interface_internal_infrastructure_conf_proto_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interface_internal_infrastructure_conf_proto_conf_proto_rawDesc), len(file_interface_internal_infrastructure_conf_proto_conf_proto_rawDesc)))
	})
	return file_interface_internal_infrastructure_conf_proto_conf_proto_rawDescData
}

var file_interface_internal_infrastructure_conf_proto_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_interface_internal_infrastructure_conf_proto_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.api.Bootstrap
	(*Server)(nil),              // 1: kratos.api.Server
	(*Client)(nil),              // 2: kratos.api.Client
	(*Server_HTTP)(nil),         // 3: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),         // 4: kratos.api.Server.GRPC
	(*Client_GRPC)(nil),         // 5: kratos.api.Client.GRPC
	(*durationpb.Duration)(nil), // 6: google.protobuf.Duration
}
var file_interface_internal_infrastructure_conf_proto_conf_proto_depIdxs = []int32{
	1, // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2, // 1: kratos.api.Bootstrap.client:type_name -> kratos.api.Client
	3, // 2: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	4, // 3: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	5, // 4: kratos.api.Client.grpc:type_name -> kratos.api.Client.GRPC
	6, // 5: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	6, // 6: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	6, // 7: kratos.api.Client.GRPC.timeout:type_name -> google.protobuf.Duration
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_interface_internal_infrastructure_conf_proto_conf_proto_init() }
func file_interface_internal_infrastructure_conf_proto_conf_proto_init() {
	if File_interface_internal_infrastructure_conf_proto_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interface_internal_infrastructure_conf_proto_conf_proto_rawDesc), len(file_interface_internal_infrastructure_conf_proto_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_interface_internal_infrastructure_conf_proto_conf_proto_goTypes,
		DependencyIndexes: file_interface_internal_infrastructure_conf_proto_conf_proto_depIdxs,
		MessageInfos:      file_interface_internal_infrastructure_conf_proto_conf_proto_msgTypes,
	}.Build()
	File_interface_internal_infrastructure_conf_proto_conf_proto = out.File
	file_interface_internal_infrastructure_conf_proto_conf_proto_goTypes = nil
	file_interface_internal_infrastructure_conf_proto_conf_proto_depIdxs = nil
}
