name: Build Spring Cloud Project

on:
  push:
    branches:
      - v2.0.0
  pull_request:
    branches:
      - v2.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Set up JDK 22
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Maven packages
        id: cache-maven-packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B clean package --file ./lersosa-java/pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: spring-cloud-jar
          path: target/*.jar
